### ISSUE TITLE
feat: Support for predictive text in Desktop plarforms

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#11915] opened 2024-07-02 21:55 UTC
### Is your feature request related to a problem? Please describe.

Web and mobile platforms have predictive text capabilities. Please add the same feature in Desktop platforms, Windows, Mac and Linux 

### Describe the solution you'd like

Please add the same feature in Desktop platforms, Windows, Mac and Linux 

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [X] Keyman for Linux
- [X] Keyman for macOS
- [X] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

**Comment by mcdurdin** [comment] 2024-07-02 23:49
This is a duplicate of #344

**Comment by mcdurdin** [comment] 2024-07-02 23:50
Also:

> We still don't have the developer resources to investigate this, let alone implement, at this time, sorry.

**Closed by mcdurdin** 2024-07-02 23:49 UTC
Labels: common/, feat

**Comment by MayuraVerma** [comment] 2024-07-03 12:12
Hello @mcdurdin 

If one resource would work exclusively on enabling predictive text on desktop platforms, Windows, Mac and Linux

What skills are needed

How long do you think his/her commitment is needed, let's say he/she is committing 40 hours a week

Would you accept contributions as pull request to merge into master

I will look for friends who are willing to contribute

**Comment by mcdurdin** [comment] 2024-07-03 12:25
We don't want to even consider doing this until the on screen keyboard component is re-engineered, which is currently scheduled for v19.

Predictive text for desktop is not an small project. The predictive text component runs in Javascript. So we need to deploy a Javascript engine on each platform (a significant effort); we would need to support the lexical model package type on each platform, including search, download, install, enumeration, uninstall, management, etc; we would need UX for each platform for the suggestion interface, plus UX for configuration etc. The assumptions we have made around mobile devices in the predictive text codebase would also need to be significantly revisited for desktop devices.

It would require extensive interaction with the leads for each platform, and I don't think it's really feasible for an external resource to attempt it without significant design input from us -- and we just don't have capacity to do that at present.

So I really cannot estimate how long it would take to design and build an implementation for each platform, for a new remote contributor, who also has to come up to speed with the Keyman code base and all the intricacies of the operating system interactions.

Finally, this is not a feature that is getting a lot of requests from other users, so I don't want to prioritise it over other projects which are really more urgently required.
