### ISSUE TITLE
bug(linux): installation fails in Ubuntu 22.04 jammy indicating .deb files are not 'Debian binary archives'

### ISSUE THREAD

**Issue by rik-shaw** [keymanapp/keyman#7029] opened 2022-08-03 15:40 UTC
**Describe the bug**
Installing Keyman in Ubuntu 22.04 jammy fails indicating `.deb` files are not Debian binary archives

**To Reproduce**

1. Add keyman ppa
2. sudo apt install keyman
3. output:
```
$ sudo apt install keyman
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  ibus-keyman libkmnkbp0-0 python3-keyman-config
The following NEW packages will be installed:
  ibus-keyman keyman libkmnkbp0-0 python3-keyman-config
0 upgraded, 4 newly installed, 0 to remove and 3 not upgraded.
Need to get 304 kB of archives.
After this operation, 2,591 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://packages.sil.org/ubuntu jammy/main amd64 libkmnkbp0-0 amd64 15.0.267-1+jammy1 [50.9 kB]
Get:2 http://packages.sil.org/ubuntu jammy/main amd64 ibus-keyman amd64 15.0.267-1+jammy1 [22.5 kB]
Get:3 http://packages.sil.org/ubuntu jammy/main amd64 python3-keyman-config all 15.0.267-1+jammy1 [163 kB]
Get:4 http://packages.sil.org/ubuntu jammy/main amd64 keyman all 15.0.267-1+jammy1 [67.5 kB]
Fetched 304 kB in 1s (368 kB/s)
dpkg-deb: error: file '/var/cache/apt/archives/libkmnkbp0-0_15.0.267-1+jammy1_am
d64.deb' is not a Debian binary archive (try dpkg-split?)
dpkg: error processing archive /var/cache/apt/archives/libkmnkbp0-0_15.0.267-1+j
ammy1_amd64.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
dpkg-deb: error: file '/var/cache/apt/archives/ibus-keyman_15.0.267-1+jammy1_amd
64.deb' is not a Debian binary archive (try dpkg-split?)
dpkg: error processing archive /var/cache/apt/archives/ibus-keyman_15.0.267-1+ja
mmy1_amd64.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
dpkg-deb: error: file '/var/cache/apt/archives/python3-keyman-config_15.0.267-1+
jammy1_all.deb' is not a Debian binary archive (try dpkg-split?)
dpkg: error processing archive /var/cache/apt/archives/python3-keyman-config_15.
0.267-1+jammy1_all.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
dpkg-deb: error: file '/var/cache/apt/archives/keyman_15.0.267-1+jammy1_all.deb'
 is not a Debian binary archive (try dpkg-split?)
dpkg: error processing archive /var/cache/apt/archives/keyman_15.0.267-1+jammy1_
all.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
```

**Related issues**

---

**Keyman for Linux:**
   Device: Lenovo Thinkpad T470            
 - OS: Ubuntu / Wasta-Linux 22.04                
 - Keyman version: 15.0.267

**Comment by ermshiperete** [comment] 2022-08-04 16:40
Actually, these packages are from packages.sil.org, and in deed it seems that the files for jammy and kinetic are corrupt. :eyes:

**Comment by ermshiperete** [comment] 2022-08-04 17:45
OK, found the problem. Will be fixed in the next version (> 15.0.267-1+{jammy,kinetic}1). As a workaround you can install the version from the ppa.

The corrupt packages were caused by a bug in a repackage script. Because pso doesn't support the zstd compression that Ubuntu >= 21.10 use by default, we have to repackage the .deb files before uploading to pso. This involves unzipping and rezipping the .deb file. Turns out that the order in which the files from the .deb file get added to the zip matters...

**Comment by rik-shaw** [comment] 2022-08-04 19:36
@ermshiperete thanks, I intended to dig a bit more to confirm the package source, etc. but neglected to do. Regardless thanks for digging into it. Interesting finding to say the least! :-)

**Comment by ermshiperete** [comment] 2022-08-05 09:05
@rik-shaw This should work now with the packages for Keyman 15.0.268.

**Closed by ermshiperete** 2022-08-05 09:05 UTC
Labels: bug, linux/
