### ISSUE TITLE
bug(iOS): Galaxie Hebrew keyboard is not working in Safari browser

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#8248] opened 2023-02-17 13:20 UTC
### Describe the bug

After installing Galaxie Hebrew keyboard in iPhone Simulator, I tried to type in that language and noticed that it is showing english letters in the text area. 

### Reproduce the bug

1. Install Keyman 17.0.50-alpha build. 
2. Open Keyman app. 
3. Install Galaxie Hebrew keyboard. 
4. Set Keyman as the System Keyboard.
5. Open Safari browser. 
6. Set Galaxie Hebrew keyboard as the active keyboard. 
7. In the Search bar, type b \ = r @ a v ! y t.

Here, I noticed that even though the typing is from right-to-left direction, it showing the same English letters instead of Hebrew letters. Seems to be an issue. 

I have attached video file (HebrewKBNotworking.MP4) for reference. 

https://user-images.githubusercontent.com/19683143/219661458-65b787fd-d052-47a1-affc-02d899e92633.mp4

### Expected behavior

Typing  b \ = r @ a v ! y t should output בְּרֵאשִׁית . 

### Related issues

#7979

### Keyman apps

- [ ] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.50-alpha

### Operating system

iOS 16.2

### Device

iPhone 14 Pro Max Simulator

### Browser

Safari 

### Keyboard name

Galaxie Hebrew (Positional)

### Keyboard version

1.1

### Language name

Hebrew

**Comment by mcdurdin** [comment] 2023-02-19 00:53
This is a duplicate of #6768

**Closed by mcdurdin** 2023-02-19 00:53 UTC
Labels: bug
