### ISSUE TITLE
bug(ios): Keyman or FirstVoices keyboard does not function as the system keyboard on the iPad after being installed as a secondary keyboard

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#10572] opened 2024-01-31 10:36 UTC
### Describe the bug

After installing the Keyman or FirstVoices keyboard on the iPad app, I noticed that the latter is not working.

### Reproduce the bug

Test 1
1. Install Keyman 16.0.144 build in iPad. 
2. Set Keyman as the system-wide keyboard. 
3. Open Safari browser. 
4. Click the Search bar. 
5. Select 'Keyman' from the OSK menu list. (using globe key) 
6. Install FirstVoices 16.0.144 keyboard in iPad. 
7. Set 'FirstVoices' as the system-wide keyboard. 
8. Open Safari browser. 
9. Click the Search bar. 
10. Click the Keyboard menu list from the OSK. (using globe key)
Here, I noticed that the secondary keyboard 'FirstVoices' was missing from the menu list. 

Test 2
1. Install Keyman 16.0.144 build in iPad. 
2. Set Keyman as the system-wide keyboard. 
3. Open Safari browser. 
4. Click the Search bar. 
5. Select 'FirstVoices' from the OSK menu list. (using globe key) 
6. Install Keyman 16.0.144 keyboard in iPad. 
7. Set 'Keyman' as the system-wide keyboard. 
8. Open Safari browser. 
9. Click the Search bar. 
10. Click the Keyboard menu list from the OSK. (using globe key)
Here, I noticed that the secondary keyboard 'Keyman' was missing from the menu list. 

Workaround: 
1. Restart iPad after installing the two keyboards (ie., Keyman and FirstVoices). 
2. Open Safari browser. 
3. Click the Search bar. 
4. Click the Keyboard menu list from the OSK. (using globe key)
Here, we may notice that both keyboards are in the keyman menu list. We can select either the Keyman or FirstVoices keyboard as the System-wide keyboard. 

..FirstVoices Keyboard missing

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/c1007552-0f36-4b9f-b5d1-b57acdddeac0">

..Keyman Keyboard missing

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/3d48e146-fd15-41ce-ae71-eb55972b4ace">

..both keyboards are displaying in the menu list after restarting the iPad

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/de475bb2-4657-4333-9dc8-77ee1545ba90">

..after workaround

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/a60ccb38-bb15-4dc5-bbbd-2c7bc575540c">

### Expected behavior

If the system-wide keyboards, namely Keyman and FirstVoices, are installed and configured, they should both function within the Safari browser.

### Related issues

#10479

### Keyman apps

- [ ] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0.144 stable

### Operating system

ios 15.5, ios 17.0

### Device

iPad 15.5 (9th generation)

### Browser

Safari browser

**Comment by sgschantz** [comment] 2024-02-05 07:09
@bharanidharanj: is this the same as #10479?

**Comment by sgschantz** [comment] 2024-02-08 09:01
moving to future as this is not reproducible on a real device but still may indicate some timing issue

**Comment by bharanidharanj** [comment] 2024-02-08 09:09
> @bharanidharanj: is this the same as #10479?

@sgschantz 10479 issue represents the FirstVoices keyboard is not working if it is set as a default system keyboard. But, 10572 issue describes the keyboards (ie., Keyman or FirstVoices) whichever is installed later don't work as a system keyboard. I have correlated these issues since they appear to share similarities.

**Comment by bharanidharanj** [comment] 2024-02-14 06:57
@sgschantz Retested this issue with iPad device and here is my observation: 1. This issue only happens with Safari browser. 2. In Chrome browser, it is working fine. Seems to be browser related.

**Comment by sgschantz** [comment] 2024-02-20 07:12
Closing, could not reproduce with Keyman. Could reproduce with FV on simulator with version 16 of Keyman, and that is represented by #10479

**Closed by sgschantz** 2024-02-20 07:12 UTC
Labels: bug, ios/
