### ISSUE TITLE
[iOS] Banner not displaying properly

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#2833] opened 2020-03-16 23:34 UTC
**Describe the bug**
In my testing, upgrading from an earlier version of Keyman defaulted to having the banner switched off after the update. This was confusing and difficult for longpress in particular.

---
  
**iPhone/iPad:**
 - Device: iPhone 7, iPhone 6
 - OS: iOS 12.4.1 (iPhone 7), iOS 12.4.5 (iPhone 6).
 - Keyman version 13.0.104 (iPhone 7), 13.0.103 (iPhone 6)
 - Target application: any (system keyboard, not tested on in-app)

**Comment by jahorton** [comment] 2020-03-17 00:48
This isn't an option that even exists.

So, the issue banner isn't displaying properly.  Based on the video in #2832, it appears that the banner should be displaying, but isn't - the space is very much still allocated for it.  Then, based on the description of that issue, the most likely case is that the banner isn't displaying, causing the handlers for the keyboard to operate in a situation where they should not due to the OSK's element hierarchy.

It'll take some investigation to confirm, of course.

**Comment by jahorton** [comment] 2020-03-17 08:37
This was introduced with 14.0.25-alpha (and its corresponding cherrypick 13.0.103-or-so).  The cause was easily traced to a certain line of #2822, which is addressed by #2840.

**Closed** 2020-03-18 05:07 UTC
Labels: bug, ios
