### ISSUE TITLE
bug(developer): Key code is never fired for Mobile devices

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4346] opened 2021-01-27 02:16 UTC
**Describe the bug**

Keyman developer does not compile successfully for mobile devices when a Touch Layout is created based on the On Screen.

This is what happen when compile fails:

![image](https://user-images.githubusercontent.com/28331388/105931442-ccea0780-607d-11eb-94a7-d2b342c6d746.png)

Keyboard project folder for testing:
[sil_hebrew.zip](https://github.com/keymanapp/keyman/files/5877239/sil_hebrew.zip)

**To Reproduce**

1. Unzip and open the keyboard project folder provide above
2. Click on 'Touch Layout' tab
3. Click on "Import from On Screen" to the right of "Template..." button
4. Save and compile
5. See error

**Expected behavior**

The compile should be successful ignoring the issue that `The rule will never be matched because its key code is never fired.` because the rule is not applicable on touch layout. It is included to account to the "illegal" (or unexpected) output in macOS.

---

**Keyman Developer:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman Developer version: 14.0.224-beta

---

**Keyboard**
 - Keyboard name: sil_hebrew
 - Keyboard version: 1.7.2
 - Language name: Hebrew

**Additional context**

This is to note that the changes made to the Touch Layout does not stay after restarting Keyman Developer. This is why the ZIP folder may show you the English layout of the Touch Layout rather than the imported version done during testing.

**Comment by mcdurdin** [comment] 2021-01-29 03:12
If the rule is desktop-only, then perhaps change the rule as follows:

```
platform('desktop native') + any(illegalkey) > beep
```

**Comment by mcdurdin** [comment] 2021-03-02 06:08
Closing this issue; it is by design and there is a workaround.

**Closed by mcdurdin** 2021-03-02 06:08 UTC
Labels: bug, developer/, developer/compilers/
