### ISSUE TITLE
Incorrect positioning of fixed elements on Android 4.1.2 native browser

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#286] opened 2017-09-01 04:13 UTC
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Friday Feb 21, 2014 at 04:34 GMT_
_Originally opened as KD-129_

----

OSK keycap text displays correctly, but the keycap Latin letter labels and pop-up display icons get positioned incorrectly on Android native browser. This would not be very important, but it also affects the appearance of the Keyman for Android app.

The letter labels are absolutely positioned within fixed DIV elements, but are sized, positioned and scroll wrongly. It should be possible to resolve this, but it does not affect Android 4.2 or iOS, so is of questionable value.

At this point it will be put on hold.

**Comment by jahorton** [comment] 2017-10-13 07:40
Is effectively a duplicate of #291.

**Closed by jahorton** 2017-10-13 07:40 UTC
Labels: android, bug, web
