### ISSUE TITLE
bug: GFF Gurage v0.8.1 Keyboard Info Not Display in MacOS

### ISSUE THREAD

**Issue by dyacob** [keymanapp/keyman#5378] opened 2021-06-27 19:48 UTC
**Describe the bug**
This is a follow up to https://github.com/keymanapp/keyman/issues/5316 , I set the keyboard VERSION field to "10" and the keyboard icon and title now appears under configuration.  However, the keyboard details do not appear in the information dialog as expected (see screenshot).

The issue with the Info details is observed with Keyman 14, if the info issue has been resolved in the previous bug fix, please ignore and close.

**To Reproduce**
1. Go to Keyman > Configuration ... > Download ክeyboard...
2. Install GFF Amharic, then GFF Gurage and GFF Geez (the order may not be important)
3. The broken view of the GFF Gurage keyboard should not be visible in the Configuration dialog.
4. Click Info (i) to review dialog contents.

**Expected behavior**
All fields should be populated as per the Keyman for Windows and other GFF keyboards.

**Screenshots**
<img width="813" alt="GFF-Gurage-macOS-Info-Bug" src="https://user-images.githubusercontent.com/8098333/123557468-ee4f3c80-d75e-11eb-8f3b-633b35073138.png">

---

**Keyman for macOS:**
- OS: Big Sur Version 11.4
- Keyman version: 14.0.276
- Target Application: Keyman Configuration

---

**Keyboard**
- Keyboard name: GFF Gurage
- Keyboard version: 0.8
- Language name: Gurage (sgw-Ethi)

**Additional context**

**Comment by mcdurdin** [comment] 2021-06-27 19:52
Is this a duplicate of #5316? Note that we have fixed the bug there but the stable-14.0 release containing the patch is pending.

**Comment by dyacob** [comment] 2021-06-27 20:00
Sorry about that, I hit something and the editor committed prematurely.

The previous ticket reported several issues that appeared with the Configuration dialog with the VERSION number.  Lowering the version from "14" to "10" the display of the keyboard icon and name works correctly, as does the Help contents, but the Info dialog still appears empty.

**Comment by mcdurdin** [comment] 2021-06-27 20:03
Yes, that secondary issue should be fixed also with that patch. See #5328.

If you like, you can test this with the 15.0.75 alpha release which already contains the patch.

**Closed** 2021-06-28 00:09 UTC
Labels: bug
