### ISSUE TITLE
bug(developer): Keyman Developer Debugger drops '[' at start of a string in `outs()`

### ISSUE THREAD

**Issue by dyacob** [keymanapp/keyman#12348] opened 2024-09-02 17:19 UTC
### Describe the bug

I'll add more detail later, I wanted to get this noted before I had a chance to forget it.

for a `store` like:

```
store(XyzChoices) "[A₁|B₂|C₃]"
  ⋮
'X' + '@' > outs(XyzChoices)
```

the code works as expected in applications like MS Word.  But in the debugger typing window, the first "[" does not appear.  This may be specific to "[" or applies to any symbol at the start of the store (I'll check on this)

### Reproduce the bug

```
store(XyzChoices) "[A₁|B₂|C₃]"
  ⋮
'X' + '@' > outs(XyzChoices)
```

Only `A₁|B₂|C₃]` appears in the debugger window.

### Expected behavior

The output `[A₁|B₂|C₃]` should fully appear.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.328

### Operating system

Windows 11 Pro (22621.1702)

### Device

Windows Laptop

### Target application

N/A

### Browser

N/A

### Keyboard name

Any

### Keyboard version

Any

### Language name

Any

**Comment by mcdurdin** [comment] 2024-09-02 23:00
I cannot reproduce this -- can you give attach a full project where this is going wrong (and the relevant key sequence)?

**Comment by mcdurdin** [comment] 2024-09-12 05:47
@dyacob I'm going to go ahead and close this as no-repro. Please feel free to re-open if you can give more detail for reproduction!

**Closed by mcdurdin** 2024-09-12 05:47 UTC
Labels: bug, developer/
