### ISSUE TITLE
Definitions of K_EQUAL does not work in KeymanWeb

### ISSUE THREAD

**Issue by rimas-kudelis** [keymanapp/keyman#1694] opened 2019-03-24 21:04 UTC
**Describe the bug**
While testing keymanapp/keyboards#652, I noticed that the definitions of `KP_EQUAL` in my layout file are ignored. I checked with https://keymanweb.com/#lt,Keyboard_lithuanian, and the same problem is reproducible there with the current Lithuanian layout too.
For the reference, I'm using Firefox on Linux.

**To Reproduce**
1. Go to https://keymanweb.com/#lt,Keyboard_lithuanian
2. Press the =+ key
3. See what appears in the textarea

**Expected behavior**
Letter "ž" should have appeared.

**Actual behavior**
A character "=" appears.

---
**KeymanWeb (please complete the following information):**
 - OS: Debian Linux, Ubuntu 18.04.2
 - Browser: Firefox Nightly, Firefox 66
 - KeymanWeb Version: 10.0.97 (locally), 10.0.103 (keymanweb.com)
 - URL: https://keymanweb.com/#lt,Keyboard_lithuanian
 
---
 
**Keyboard**
 - Keyboard name: lithuanian
 - Keyboard version: 1.0
 - Language name: Lithuanian

**Comment by jahorton** [comment] 2019-03-26 01:57
Cannot reproduce in Windows 10, Firefox 65, but I can reproduce this in macOS Mojave with Firefox 66.

When using Chrome instead, I cannot reproduce the error in either Win 10 or Mojave.  Mojave's Safari also fails to reproduce the issue.

Looks like it's a combination of OS + browser at play.  Firefox has been known to use slightly different keycodes, so investigating that may prove useful to resolving the issue.

**Comment by rimas-kudelis** [comment] 2019-03-26 20:10
I could provide some debug output from Firefox Console or elsewhere, especially if you have a tool or something that would output stuff there thus making it easier for me to do that. :)

**Comment by rimas-kudelis** [comment] 2019-03-26 20:45
I could provide some debug output from Firefox Console or elsewhere, especially if you have a tool or something that would output stuff there thus making it easier for me to do that. :)

**Closed** 2019-09-23 04:48 UTC
Labels: bug, web
