### ISSUE TITLE
[Developer] Lower-case Lexical model projects paths when creating from template

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#2513] opened 2020-01-22 03:42 UTC
**Describe the bug**
A lexical model was generated by Keyman Developer 12 project template. See keymanapp/lexical-models#64. The BCP 47 tag `bcc-Arab` resulted in the project being created in a directory `/release/sil/sil.bcc-Arab.upp_ptw11`.

To avoid file-casing conflicts, the created folders should be lower-cased. (e.g. `sil.bcc-arab.upp_ptw11`)

### Configuration:
Keyman Developer 12.0.64.0
Windows 10

**Comment by mcdurdin** [comment] 2020-02-10 22:42
I'm unable to reproduce this issue -- the code already lower-cases the model id and in testing I can't make it go wrong. The fix was made in #2050 which landed in Windows beta 12.0.26.

**Comment by mcdurdin** [comment] 2020-02-10 22:43
Please re-open if you find a repro.

**Closed by mcdurdin** 2020-02-10 22:43 UTC
Labels: bug, developer
