### ISSUE TITLE
Chrome Keyboard Tester Display Out of Sync With Installed Mobile Version

### ISSUE THREAD

**Issue by dyacob** [keymanapp/keyman#3028] opened 2020-04-25 15:14 UTC
**Describe the bug**
The "Keyboard Test" web page that Keyman Developer launches shows the longpress options without the pressed letter appearing at the start of the popup list (1st screenshot).  Once installed on a mobile phone the pressed key will appear at the start of the list (2nd screenshot):

**To Reproduce**
1. Test a keyboard with KMD and Chrome and press a key that contains a longpress sequence.
2. Compare against the same longpress sequence with the keyboard installed on a mobile phone.

**Expected behavior**
The Chrome tester will present the pressed key at the start of the popup list.

**Screenshots**

Form Chrome: "ፍ" is pressed and _**does not**_ appear at the start of the popup list.
![Ethiopic-Fe-Keyboard-Test](https://user-images.githubusercontent.com/8098333/80282963-6eed5580-86e2-11ea-8e80-298facbad34b.png)

From Android: "ፍ" is pressed and _**does**_ appear at the start of the popup list.
![Ethiopic-Fe-Keyboard-Android-Installed](https://user-images.githubusercontent.com/8098333/80282965-73b20980-86e2-11ea-813f-5a41be66c8d5.png)

---

  
**iPhone/iPad/Android:**
 - Device: Samsung S9
 - OS: Android 10
 - Keyman version: 13.0.6209
 - Target application: Any
 
**Keyman Developer:**
 - OS: Windows 10 18362
 - Keyman Developer version: 13.0.107.0 (and earlier)
 
---
 
**Keyboard**
 - Keyboard name: Any, Screenshots are from Tigrinya-ET 1.3.9

**Comment by darcywong00** [comment] 2020-04-26 03:27
See #1113

The longpress previews in Developer match the behavior of the iOS app.
The Android app (on phone) is the one with "different" longpress behavior.
btw, the Android app on tablet also doesn't display the base key.

**Comment by mcdurdin** [comment] 2020-04-26 20:26
Closing as duplicate of #1113.

**Closed by mcdurdin** 2020-04-26 20:26 UTC
Labels: bug, duplicate
