### ISSUE TITLE
bug(web): Pressing spacebar or backspace key affects the predictive texts displayed in the suggestion bar

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#10980] opened 2024-03-12 12:43 UTC
### Describe the bug

I noticed that pressing space bar or backspace key multiple times affects the predictive texts displayed in the suggestion bar. 

### Reproduce the bug

1. Install Keyman 17.0.286-beta
2. Open Keyman In-app. 
3. Add a Khmer Angkor keyboard. 
4. Switch to English - EuroLatin (SIL) keyboard. 
5. Press the spacebar key three times. 
6. We may notice that the predictive text does not appear on the suggestion bar. 
7. Press the backspace key. 
8. Here, we may notice that the predictive text again appears. 
9. Switch to the Khmer Angkor keyboard. 
10. Press the space bar key multiple times. 

We might observe that predictive text appears after one press of the space bar but disappears after another press. Seems to be an issue. I have attached the video file for reference. 

Note: Able to reproduce in iPhone 13 mobile device (iOS 17.4)

https://github.com/keymanapp/keyman/assets/19683143/0cd1626e-e774-47b2-8c2a-47a534e1ce5b

### Expected behavior

Pressing spacebar key or backspace key should not affect the functionality of the suggestion bar. 

### Keyman apps

- [X] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.826-beta

### Operating system

Android 12, 13, iOS 17.4

### Device

Samsung Mobile 13 AG23 device, iPhone 13 Mobile

### Keyboard name

khmer_angkor

### Keyboard version

1.3

### Language name

Khmer

**Comment by mcdurdin** [comment] 2024-03-12 21:44
Moving this to web because it is reproducible in both android and ios.

**Comment by jahorton** [comment] 2024-04-04 07:23
Starting investigation now.

The first thing I notice - it appears that when the bug triggers, the predictive-text engine is trying to predict based upon a single space as if it were the start to a word.  I know that part of the codebase is responsible... the key is just to determine why it happens.  Either way, _definitely_ a bug, so thanks for reporting this!

**Closed** 2024-04-12 03:59 UTC
Labels: bug, web/
