### ISSUE TITLE
bug(android): The Keyman banner flickers on the keyboard after clicking the globe key in the Android 7.1.1 and Android 9.0 OS

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#11034] opened 2024-03-21 09:07 UTC
### Describe the bug

I noticed that the keyman banner flashes on the keyboard while switching the keyboard using the globe key. 

### Reproduce the bug

1. Install Keyman 17.0.291-beta
2. Open keyman app in Android 7.1.1 / API 25 emulator. 
3. Install Cameroon Qwerty and SIL (IPA) keyboard. 
4. Switch Cameroon - Bafanji keyboard or SIL (IPA) keyboard using the globe key.

Here, I noticed the Keyman banner flashes on the OSK. Seems to be an issue.

I have attached the video file for reference. 

https://github.com/keymanapp/keyman/assets/19683143/f9b0a6eb-0041-4c8f-b5aa-842a03821c63

### Expected behavior

The Keyman banner should not briefly appear when clicking the globe key.

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.291-beta

### Operating system

Android 7.1.1

### Device

API 25 emulator (Android Studio - Iguana)

**Comment by mcdurdin** [comment] 2024-03-21 21:16
I have also observed this, in a few situations.

**Comment by darcywong00** [comment] 2024-03-25 04:19
Paused the frame during the flicker.
![image](https://github.com/keymanapp/keyman/assets/7358010/e9910bd7-ece3-46ca-b26e-8ea2f3361712)


Looks like the image banner is being displayed (100% of the image) before the OSK is ready. 

Is there an intermittent time in KeymanWeb when the banner is filling the entire OSK dimension (before OSK is ready)?

**Comment by mcdurdin** [comment] 2024-03-25 04:37
Nice capture @darcywong00.

I reckon this is related to #10054 too -- it's all about the initialization sequence for the web container. Rotation just makes it all much harder as well.

**Comment by darcywong00** [comment] 2024-03-27 02:34
@jahorton - I've halted in KeymanWeb at l.157

https://github.com/keymanapp/keyman/blob/a084fcfbb8542b00965a47cf78979eb540b279d6/web/src/engine/main/src/keymanEngine.ts#L139-L159

```
this.osk.activeKeyboard = kbd;
```
creates this flicker

![image](https://github.com/keymanapp/keyman/assets/7358010/2fba147e-7007-417e-9931-43848be8526b)

Any suggestions? 

This is the transition from a keyboard with suggestions  to a keyboard without suggestions (html banner)

**Comment by jahorton** [comment] 2024-03-27 02:53
Yep, that's pretty much an expected intermediate state given the existing code.  So, it sounds like Android's updating the WebView's render while the JS code is still evaluating, pushing out a frame between `osk.startHide(false)` and `this.osk.present()`.  Ideally, it'd happen so fast that you wouldn't get that flash... but here we are.

Part of the intent, I believe, was to ensure that users can't type a key with a no-longer-current keyboard.  That said... I believe we now _do_ have the ability to properly evaluate keystrokes from the old keyboard were they to occur within this brief interval of time.  (That said, we might prefer to block such keystrokes outright.)

**Comment by jahorton** [comment] 2024-03-27 07:51
... it is interesting how the VisualKeyboard is actually fully-hidden here; I don't think that should be happening.   That's something for me to look at.

**Comment by jahorton** [comment] 2024-03-28 02:42
It took me a while to get a reproduction of this; it's certainly not consistent for me.  But, I did eventually land something.

Some observations:

![image](https://github.com/keymanapp/keyman/assets/25213402/1fcd726e-0bc1-4fe5-8d14-d2379e6a2bfc)

The parent of the `#shadow-root` has the correct banner height.  It's the _insides_ that have the height wrong, interestingly.  That said...

![image](https://github.com/keymanapp/keyman/assets/25213402/dbd6c0ed-537a-4275-98da-a2631e06a026)

After manually editing the height to a precise pixel value, the keyboard area is blank.  This may be a contributor to the banner gaining the extra height at this moment.

So, why is _that_ happening?

![image](https://github.com/keymanapp/keyman/assets/25213402/70d9943a-c5cf-421d-b85a-ed5c4326c5f1)

It's pretty clear that the loading keyboard hasn't yet had its proper style data become active.  Note:  `K_W` is showing up positionally as if it were the first key in the second row, rather than the second key of the first row.  This is quite indicative of how KMW acts when the OSK stylesheet is missing.  Thing is... the stylesheet's totally attached at the time.

I suspect that the way we reset the OSK whenever loading a new keyboard is part of the issue here:

https://github.com/keymanapp/keyman/blob/acc38fea588986c70036571acdf2f334f83bf7b2/web/src/engine/osk/src/views/oskView.ts#L701-L726

In particular, note that we discard all OSK HTML contents - including the stylesheets - and then re-link them.  Perhaps the stylesheet's not being applied due to being temporarily discarded... in which case, performing a less-destructive keyboard-loading process may perform better.

**Comment by darcywong00** [comment] 2024-04-03 04:42
Fixed by #11108

**Closed by darcywong00** 2024-04-03 04:42 UTC
Labels: bug, android/
