### ISSUE TITLE
bug(iOS): Keyman is frozen when trying to add a keyboard

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4319] opened 2021-01-22 06:58 UTC
**Describe the bug**

Keyman stop responding after an attempt to add a new keyboard was made. The new keyboard didn't get added either.

**To Reproduce**

1. On Keyman, tab on the three dots on the top right corner
2. Tab on 'Installed Language' and then the plus sign on the top right corner to add a new keyboard
3. Type in to search for a keyboard, say "Kayah Li"
4. Install the keyboard

**Expected behavior**

The keyboard should be added and Keyman should not be frozen.

---

**Keyman for iPad:**
 - Device: Ipad
 - OS: iOS 9.3.5
 - Keyman version <!-- e.g. 14.0.224-beta
 - Target application: Keyman

---

**Keyboard**
 - Keyboard name: sil_kayah_li
 - Keyboard version: 1.2
 - Language name: Kayah

**Comment by jahorton** [comment] 2021-01-26 07:35
I'm currently unable to replicate the error... using what was likely the test device.

That said, I can't help but note that when there's a poor internet connection, it's easy to think that nothing's happening.  (Also, during the keyboard search, when navigating between search + detail pages.)  I do see a flash of "Downloading keyboard," but there's a notable delay between that and when the installer presents itself.

**Comment by jahorton** [comment] 2021-02-02 04:49
This may have been caused by a combo of #4281's underlying bug and #4387's underlying bug.
- The former would cause the installation to fail.
- The latter could (possibly) cause a deadlock within the package-installation failure event's handler.
    - This later part is harder to verify, though.

**Comment by jahorton** [comment] 2021-02-08 06:37
As numerous highly-related issues have recently been resolved and this cannot currently be reproduced, I'm going to go ahead and close this for now.  Feel free to make a new issue if/when this shows back up.

**Closed by jahorton** 2021-02-08 06:37 UTC
Labels: bug, ios/, ios/app/
