### ISSUE TITLE
bug(common/models): LM replaces left quote and character(s) with the selected option

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#6900] opened 2022-06-30 04:03 UTC
https://user-images.githubusercontent.com/28331388/176589116-07c5b8b2-39bb-42a1-8455-ff3f7a9d935f.mov

The clip above shows that the left quote and a character being typed get replaced with the word selected off of the suggestion banner. 

This behavior is not unique to the language script being used. EuroLatin (SIL) keyboard also exhibits this behavior when testing on mobile devices, i.e. iOS and Android. In the Keyman app with the default keyboard on, type a double quote `"` and then <kbd>t</kbd>, now select `the` of of the suggestion banner to see that `the` replace both `"` and `t`.

**Comment by jahorton** [comment] 2022-09-13 08:11
Possible duplicate of #6024?  In which case, the mentioned #7205 probably fixes that too.

**Comment by MakaraSok** [comment] 2023-05-11 08:51
Tested with Keyman for iOS 17.0.104-alpha on iOS 16.4 on iPhone 14 Pro Max Simulator
https://github.com/keymanapp/keyman/assets/28331388/20387f09-506b-4e4f-81be-31aa3c43ca23

**Comment by jahorton** [comment] 2023-12-04 03:04
See https://github.com/keymanapp/keyman/issues/8759#issuecomment-1837728731; the issue is with the model, not KMW.

**Closed** 2023-12-04 03:03 UTC
Labels: bug, common/, common/models/
