### ISSUE TITLE
Header in Example app tiling

### ISSUE THREAD

**Issue by jacobbullock** [keymanapp/keyman#424] opened 2017-11-17 23:43 UTC
Header image is tiled on iPhone SE.

![simulator screen shot - iphone se - 2017-11-17 at 16 42 05](https://user-images.githubusercontent.com/296827/32973704-5ffbe76a-cbb6-11e7-8886-11142642d3af.png)

**Comment by gabrielwong** [comment] 2017-11-20 07:56
Related to #333 I believe from @jahorton's comment

**Comment by gabrielwong** [comment] 2017-12-14 04:02
Closing since duplicate of #333

**Closed by gabrielwong** 2017-12-14 04:02 UTC
Labels: bug, duplicate, ios
