### ISSUE TITLE
bug(windows): Keyboard Menu not Synced Across Windows User Accounts

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4296] opened 2021-01-19 08:40 UTC
**Describe the bug**

I have two separate Windows user accounts. Account A was used to test #4294 and account B is for testing this issue. 10 keyboards were installed and shown in the Keyboard Layouts tab of the Configuration and Keyboard Menu on the taskbar in account A. In account B, however, only the default keyboard is shown in the Keyboard Menu while all 10 are found in the Keyboard Layouts tab of the Configuration (see the screenshot below).

![VirtualBox_Windows 10_19_01_2021_14_29_53](https://user-images.githubusercontent.com/28331388/105002513-feeae080-5a63-11eb-80e0-73f701425449.png)

Unchecking and rechecking a keyboard in the Keyboard Layouts tab of the Configuration do not make any different to the Keyboard Menu on the taskbar. Restarting the machine did not make any different either.

**Expected behavior**

All 10 keyboards shown in the Keyman Configuration of account B are checked, but none of them are enabled/shown in the Keyboard Menu on the taskbar.

Since they are not enabled, they should probably not be checked, should they? 
If they are checked, they are supposed to be enabled, aren't they?

**Screen Recording**

After unchecking and rechecking these keyboards, only two keyboards may be shown in the Keyboard Menu, i.e. the Cameroon and Khmer Angkor keyboards. Please see the video recording in the zip file below of how other keyboards are not shown regardless of how many times they were unchecked and rechecked.

[Windows 10-2021-01-19T08-04-30-828565200Z.zip](https://github.com/keymanapp/keyman/files/5834566/Windows.10-2021-01-19T08-04-30-828565200Z.zip)

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 14.0.224-beta
 - Target Application: self

**Additional context**

https://github.com/keymanapp/keyman/issues/4294

**Comment by mcdurdin** [comment] 2021-01-19 21:04
Can you expand out each of the keyboard details to see associated languages? I am guessing none of them have associated languages, which would be the expected behaviour by default at present.

It might be better for newly installed keyboards to get a default language association as well for other users on the system when Keyman starts, but the way Keyman works currently is that the keyboard is "installed" for all users (appearing in Keyman Configuration) but "associated" with a language only for the user that installs the keyboard.

It's a little difficult, because on a true multi-user system, each user may have different keyboard preferences.

**Comment by MakaraSok** [comment] 2021-01-20 02:25
Yes, 8 of those keyboards do not have any language association. 

> It might be better for newly installed keyboards to get a default language association as well for other users on the system when Keyman starts, but the way Keyman works currently is that the keyboard is "installed" for all users (appearing in Keyman Configuration) but "associated" with a language only for the user that installs the keyboard.

Do we have this documented somewhere in our help?

> It's a little difficult, because on a true multi-user system, each user may have different keyboard preferences.

It is just confusing to those who use multiple user accounts on one machine. It is cumbersome to have to set everything (i.e. the keyboards and hotkeys) up each time Keyman is updated.

**Comment by mcdurdin** [comment] 2021-01-27 03:52
I am going to close this as "by design". Windows user accounts are deliberately configured separately. There may be something we can do in the future to streamline the configuration but for now it should still be working.

Note that a Keyman update (if you don't uninstall) should not change hotkeys and language associations. If this is happening, please do open another issue with a repro.

**Closed by mcdurdin** 2021-01-27 03:52 UTC
Labels: bug, windows/, windows/config/
