### ISSUE TITLE
[Developer] kmlmi crashes when Author email missing in .kps file

### ISSUE THREAD

**Issue by eddieantonio** [keymanapp/keyman#2373] opened 2019-11-22 15:44 UTC
This prevented the build in keymanapp/lexical-models#60.

I think `kmlmi` just ignored an `undefined` check -- easy workaround.

**Comment by darcywong00** [comment] 2019-11-25 04:08
Maybe a duplicate of #2370

**Comment by eddieantonio** [comment] 2019-11-25 04:11
It's more of an extension of #2370. Both can be fixed in one PR. @mcdurdin Should a missing author email emit a warning, or is it no big deal?

**Comment by mcdurdin** [comment] 2019-11-27 23:29
Missing author email is not a problem. Packages without an email address are perfectly valid.

**Closed** 2019-11-27 23:36 UTC
Labels: bug, developer
