### ISSUE TITLE
[Developer] Create build/ and source/ folders when creating new project

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#777] opened 2018-04-25 02:06 UTC
From the KCT workshop
It would be nice when Developer creates a project to generate the `build/` and `source/` folders that will be expected for submissions to the keyboard repo.

Maybe also set the default Project Settings --> Output path--> `$PROJECTPATH\build`

**Comment by mcdurdin** [comment] 2018-04-25 07:31
Duplicate of #755

**Closed by mcdurdin** 2018-04-25 07:31 UTC
Labels: developer, enhancement
