### ISSUE TITLE
bug(mac): 2021 iPad Mini 6 8.3 inch does not appear correctly when running full screen

### ISSUE THREAD

**Issue by sgschantz** [keymanapp/keyman#6097] opened 2022-01-12 02:01 UTC
**Describe the bug**
In September 2021, Apple introduced the iPad Mini 6 with a new screen resolution. Apps that are not updated to support the new resolution will not appear correctly when running fullscreen. (We have no screenshot for Keyman running on this device, but I believe black bars appear at the top and bottom of the screen.)

To gain iPad Mini 6 support, recompile the app using Xcode 13.

------------

This issue was reported by Apple:

Dear Developer,

We identified one or more issues with a recent delivery for your app, "Keyman" 15.0.175 (15.0.175). Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90901: Missing full-screen support for the latest iPad mini display. The “Keyman.app” bundle includes UIRequiresFullScreen=YES in the Info.plist or supports only a subset of UISupportedInterfaceOrientations, and is built with the 14.4 SDK. To take advantage of the full screen size, recompile with Xcode 13 and the SDK for iPadOS 15 or later.

After you’ve corrected the issues, you can upload a new binary to App Store Connect.

Best regards,

The App Store Team

--------

[Get ready for the new iPad mini display](https://developer.apple.com/news/?id=oefg5bhp)
September 27, 2021
The new iPad mini introduces a new screen resolution and aspect ratio with an edge-to-edge 8.3-inch Liquid Retina display, enabling even more immersive app and game experiences. If you’re following best practices with Auto Layout and size classes, your app’s interface will dynamically adapt to the new dimensions. However, if you’ve added UIRequiresFullScreen=YES to your app’s Info.plist in order to keep your app full screen during multitasking, you’ll need to recompile with Xcode 13 and the SDK for iPadOS 15 to take advantage of the full screen size. Test and submit your updated app in App Store Connect today.

**Comment by mcdurdin** [comment] 2022-01-12 02:13
FWIW, I now have an iPad Mini 6 for Keyman testing, and I can see the issue; it's a minor visual imperfection and not a high priority -- the app doesn't use quite 100% of the display, but the gaps look reasonably natural.

**Comment by mcdurdin** [comment] 2022-01-12 02:59
Duplicate of #6056

**Closed by mcdurdin** 2022-01-12 02:59 UTC
Labels: bug, duplicate, ios/, ios/app/
