### ISSUE TITLE
[developer] Keyboard versions must be consistent

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#2555] opened 2020-01-30 08:27 UTC
**Describe the bug**
The package build was not successful notifying that the keyboard versions are not consistent even though a check box `Package version follows keyboard version` has been checked.

![image](https://user-images.githubusercontent.com/28331388/73431957-39033400-4374-11ea-870d-733eaaba4708.png)

**To Reproduce**
1. Go to 'https://github.com/keymanapp/keyboards/pull/1052'
2. Go to the keyboard package
3. Compile the keyboard

---

**Keyman Desktop:**
 - OS: Windows 10 Pro 1909
 - Keyman version: 12.0.66.0
  
**Keyman Developer:
 - OS: Windows 10 Pro 1909
 - Keyman Developer version: 12.0.66.0
 
---
 
**Keyboard**
 - Keyboard name: rac_wadiyara
 - Keyboard version: 1.0
 - Language name: Wadiyara Koli

**Comment by mcdurdin** [comment] 2020-01-31 01:49
This would arise if the compiled keyboard version cannot be determined. Can you attach a zip of the keyboard project?

**Comment by MakaraSok** [comment] 2020-01-31 03:45
Here is the keyboard: [rac_wadiyara.zip](https://github.com/keymanapp/keyman/files/4137486/rac_wadiyara.zip).

**Comment by mcdurdin** [comment] 2020-02-10 22:23
Okay, so this is a misleading error. The problem is actually that the `.kmx` file within the package (and the `.kvk`) is referenced in the wrong place -- in the `source` folder instead of the `build` folder. When Keyman Developer tries to find the `.kmx` to read its version number, it fails. I will update the message.

**Comment by mcdurdin** [comment] 2020-02-11 18:19
Fixed in #2619 (beta 13.0.71)

**Closed by mcdurdin** 2020-02-11 18:19 UTC
Labels: bug, developer
