### ISSUE TITLE
[Windows] Sporadic erratic keyboard feedback with Word 365

### ISSUE THREAD

**Issue by orewJ** [keymanapp/keyman#2216] opened 2019-10-20 07:07 UTC
Using my Farsi phonetic keyboard In MS Word 365, the shift+key combinations occasionally fail. for example, shift+s which normally renders ش fails and I just get S.  on a second try, it gets corrected!
 'h' followed by 'a' which should render ها returns 'ha'. this anomaly corrects after a couple of tries.
Generally, fewer key register errors happen if I type very slowly. Hope Mark Keyman reads this post!
I am using the latest Windows 10 Pro and Office 365 on a Dell XPS 15 75590  for the issues I am posting.

**Comment by mcdurdin** [comment] 2019-10-20 09:30
Can you let me know which release of Keyman you are using and the version information from Word's About dialog (accessible from Account menu item)?

This may be the same issue as reported in #2143.

Keyman and Word historically worked very reliably with Word. Nothing has changed in Keyman in this respect, so it seems that something has changed with Word.

We are trying to get to the bottom of the issue but I am not able to reproduce the issue on my computer or my test computers. We'd like to run some debug logging on a computer where the issue does arise. Would you be willing to help with that?

**Comment by orewJ** [comment] 2019-10-20 09:56
Hello, Marc!

Keyman developer Ver 11.0.1356.0
Andrew

**Comment by orewJ** [comment] 2019-10-20 10:05
Marc,

Missed he second part of your question:
MS word for office 365 1909 build 12026:20334        word for Office MSO 16.0.12026.20334 64bit
andrew

**Comment by mcdurdin** [comment] 2019-10-24 00:37
@orewJ thank you for the feedback. This appears to be the same version I have.

Perhaps try updating to the very latest Keyman Desktop which has some potential mitigations for the issue (12.0 is now available). As I have been unable to reproduce the issue myself, I am not sure that the fixes are actually sufficient.

**Comment by mcdurdin** [comment] 2019-11-07 07:11
@orewJ Is this issue still coming up for you? If so, I'd like to work directly with you to diagnose it further.

>Using my Farsi phonetic keyboard In MS Word 365, the shift+key combinations occasionally fail. for example, shift+s which normally renders ش fails and I just get S. on a second try, it gets corrected!
'h' followed by 'a' which should render ها returns 'ha'. this anomaly corrects after a couple of tries.
Generally, fewer key register errors happen if I type very slowly

**Comment by orewJ** [comment] 2019-11-07 23:23
I updated Keyman Desktop on Windows *today* and tried to duplicate the issue in MS Word 365. I am happy to report that the key-presses returned the expected chars both in isolation and ligatures. 
Keyman 12 for Windows performs as expected in MS Word 365 under Windows 10.

**Comment by orewJ** [comment] 2019-11-07 23:50
I can use some help in knowing a clean uninstall routine to reinstall the latest Keyman in macOS Catalina. Overriding doesn't work and I'm stuck. Thank  you.

**Comment by mcdurdin** [comment] 2019-11-07 23:58
> I updated Keyman Desktop on Windows _today_ and tried to duplicate the issue in MS Word 365. I am happy to report that the key-presses returned the expected chars both in isolation and ligatures.
> Keyman 12 for Windows performs as expected in MS Word 365 under Windows 10.

That's great news -- I'm going to go ahead and close this issue.

> I can use some help in knowing a clean uninstall routine to reinstall the latest Keyman in macOS Catalina. Overriding doesn't work and I'm stuck. Thank you.

Can we continue this conversation in the [Keyman Community](https://community.software.sil.org/t/fixing-issues-with-keyman-and-macos-catalina/2745/2) as it doesn't belong under this issue?

**Closed by mcdurdin** 2019-11-07 23:58 UTC
Labels: bug, compatibility, windows
