### ISSUE TITLE
bug(windows): Keyman stop working in Slack 

### ISSUE THREAD

**Issue by Nnyny** [keymanapp/keyman#12018] opened 2024-07-25 09:03 UTC
### Describe the bug

Whenever I switch keyboards while writing in Slack, Keyman stop output anything. But it works fine on other applications like Chrome or Notepad. I have to restart my computer for it to work again. 

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [X] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.327

### Operating system

Windows 11 Home Single Language 22H2

### Target application

Slack 4.39.93

**Comment by Nnyny** [comment] 2024-08-09 05:10
I tried to reproduce this issue again but it seems like the problem has resolved.

**Comment by mcdurdin** [comment] 2024-08-12 03:20
Okay, we'll close this as "can't reproduce". If we encounter again, we can reopen!

**Closed by mcdurdin** 2024-08-12 03:20 UTC
Labels: bug, windows/

**Comment by Nnyny** [comment] 2024-08-19 09:09
This one just occur again! 🙂
