### ISSUE TITLE
[Mac] When a Powerpoint text box is active, user can't switch to a different Keyboard

### ISSUE THREAD

**Issue by tombogle** [keymanapp/keyman#457] opened 2017-11-30 05:30 UTC
If I click over into the left pane on a particular slide so that the text box no longer has focus, then I can switch keyboards. With a text box active, I _can_ switch from Keyman to a different input method, but any attempt to select a different keyboard has no effect.

**Comment by mcdurdin** [comment] 2018-12-10 22:33
Duplicate of #687

**Closed by mcdurdin** 2018-12-10 22:33 UTC
Labels: bug, compatibility, mac
