### ISSUE TITLE
[windows] Missing font causing crash when displaying OSK

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#741] opened 2018-04-19 13:23 UTC
@DavidLRowe ran into this while testing an SIL Tai Dam keyboard [PR](keymanapp/keyboards/pull/230) .

### Steps ###
1. Installed sil_tai_dam.kmx (in attached .zip file).
2. Used Keyman Configuration "Add language" to include blt language.
3. Because **Tai Heritage Pro** font not installed, typing with keyboard produces boxes.
4. Used Shift+Alt+K to bring up OSK, resulting in crash

### Keyman Desktop Version ###
10.0.1057.0

Crash report [trace](sillsdev/keyman-issues/issues/5607)

[sil_tai_dam-kmx.zip](https://github.com/keymanapp/keyman/files/1928230/sil_tai_dam-kmx.zip)

**Comment by mcdurdin** [comment] 2018-05-07 11:51
Duplicate of sillsdev/keyman-issues#5607

**Comment by mcdurdin** [comment] 2018-05-07 11:52
Note: this is not related to the missing font; it relates to the OSK dereferencing a null pointer after installing a keyboard.

**Closed by mcdurdin** 2018-05-07 11:51 UTC
Labels: bug, windows
