### ISSUE TITLE
Localization request for Keyboard App Builder app

### ISSUE THREAD

**Issue by ngaretou** [keymanapp/keyman#3120] opened 2020-05-12 10:57 UTC
**Describe the bug**
In Keyboard App Builder the “Close Keyman” option doesn’t show up in translations and I’d like to be able to contextualize that for our audience.

This is a problem experienced in KAB, not in Keyman. Marc_Keyman requested I post a duplicate of the feature request posted here: https://community.software.sil.org/t/close-keyman-translation/3287

**To Reproduce**
With a KAB app installed on Android, try to change keyboards by clicking on the globe button. The Close Keyboard option is only in English and no localization available in KAB. 

**Expected behavior**
KAB users should be able to provide a local translation for this string. 
![kab bug](https://user-images.githubusercontent.com/58198267/81676113-0f5fab80-943f-11ea-880a-adaedc27df31.png)

**Comment by darcywong00** [comment] 2020-05-14 07:07
The request to localize the "Close Keyman" button is a duplicate of #2035

Keyman for Android will have support for localization via #809 when Keyman 14 is released (eta end of 2020)

**Closed by darcywong00** 2020-05-14 07:07 UTC
Labels: android, bug
