### ISSUE TITLE
iOS: iPhone X rotation issue

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#914] opened 2018-05-28 23:41 UTC
iOS keyboard has issues when rotated.
device: iPhone X
iOS version: 11.3.1
app version: 10.0.152

Keyboard changed to keyman in portrait mode and device rotated to landscape
![img_5447](https://user-images.githubusercontent.com/14062593/40631864-596f23a8-62a6-11e8-91e4-0435eed0e1b3.PNG)

Keyboard changed to keyman in landscape mode 
![image](https://user-images.githubusercontent.com/14062593/40631874-7845c048-62a6-11e8-833f-0fb6b17fec11.png)

Keyboard changed to keyman in landscape mode and rotation to portrait
![img_5449](https://user-images.githubusercontent.com/14062593/40631857-43074b54-62a6-11e8-9b93-2ea8edb9bd36.PNG)

**Comment by darcywong00** [comment] 2018-05-29 00:39
This is a duplicate of issue #248

There's a potential solution in PR #789 but needs more investigation

**Closed by darcywong00** 2018-05-29 00:39 UTC
