### ISSUE TITLE
bug(developer): Cannot test within Keyman Developer

### ISSUE THREAD

**Issue by LornaSIL** [keymanapp/keyman#9885] opened 2023-10-27 19:53 UTC
### Describe the bug

Within Keyman Developer 17.0.198-alpha if I click on **Keyboard** / **Test Keyboard** I get the following message:

![image](https://github.com/keymanapp/keyman/assets/7071907/e04ba7a0-560f-46bc-b3fa-3632d54590a1)

I can't test within Developer, but I can still test on the web.

My Keyman Configuration window looks like this:
![image](https://github.com/keymanapp/keyman/assets/7071907/c45d2ffe-6fdb-4306-bbdc-4070998ed8c7)

I thought there was supposed to be a debug keyboard that automatically got installed with Keyman.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [X] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.198-alpha

### Operating system

Windows 11

### Device

Windows Dell laptop

### Target application

Keyman Developer

**Comment by mcdurdin** [comment] 2023-10-31 00:51
I have reproduced the issue -- debug symbols not being added even when the debug flag is checked -- and am working on resolving it.

> I thought there was supposed to be a debug keyboard that automatically got installed with Keyman.

This is no longer required since Keyman 16 -- Keyman Developer 16 uses Keyman Core internally to power the debugger, and Keyman for Windows is not even required to be installed in order for the debugger to run.

**Closed** 2023-11-02 03:49 UTC
Labels: bug, developer/, developer/ide/
