### ISSUE TITLE
Keyman Developer: Unify "Compile" and "Build" Terms

### ISSUE THREAD

**Issue by dyacob** [keymanapp/keyman#2769] opened 2020-03-01 01:50 UTC
**Is your feature request related to a problem? Please describe.**

Not a functional problem but a simplification of vocabulary in the interface that may also be more consistent and clear for the user.

In KMD on a KMN editor tab, there is a "Build" button on the left side bar, it opens a view with a "Compile Keyboard" button.  The KPJ tab has a "Keyboards" tab with a "Build Keyboards" button.

This is in contrast the KPS editor tab where there is a "Compile" button on the left side bar which opens a view with "Compile Package" and "Compile Installer" buttons.  The KPJ tab has a "Packaging" view which uses "Build Packages" for the same action.

**Describe the solution you'd like**

Use "Compile" everywhere and drop the use of "Build".  I think the meaning of the two are close enough in KMD that just using one term is sufficient.

**Describe alternatives you've considered**

The alternative is to unify around the word "Build" instead of "Compile".  Or keeping things as they are.  Once you notice the discrepancy you can't un-see it.

**Product context**
Windows.

**Comment by mcdurdin** [comment] 2020-03-08 19:51
Thank you! Yes, this is an issue with consistency (see also "code" vs "source"). We've chosen not to do i18n for Keyman Developer in 14.0 (hopefully 15.0) and would aim to tackle this then.

**Comment by mcdurdin** [comment] 2020-03-08 19:52
I'll close this as a duplicate of #2636

**Closed by mcdurdin** 2020-03-08 19:52 UTC
Labels: developer, enhancement
