### ISSUE TITLE
bug(developer): node js window is running behind the Keyman Developer dialog after opening Keyman Developer in Windows 11 OS

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#7954] opened 2022-12-28 12:55 UTC
### Describe the bug

I noticed that there is another Command Prompt window is running behind the Keyman Developer dialog after opening the Keyman Developer 17.0 alpha build in Windows 11 OS.  Note: I am not seeing this behavior while running the same in Windows 10 OS. 

### Reproduce the bug

1. Install Keyman Developer 17.0.21-alpha build in Windows 11 OS.
2. Double Click on the Keyman Developer icon from the Desktop.
3. Verify that the Keyman Developer build opens. 
4. Minimize the Keyman Developer dialog. 
5. Here, I noticed that there is a command prompt opens and running behind the Keyman Developer dialog. 

Note: I am not seeing this behavior while running the same in Windows 10 OS. 

I have attached the Screenshots for reference. 

..in Windows 11 OS
  
   <img width="300" src="https://user-images.githubusercontent.com/19683143/209815667-8ba3d139-410e-45e4-a3a9-98a52640f912.PNG">

   <img width="300" src="https://user-images.githubusercontent.com/19683143/209818951-2616b97d-0954-44ee-8cb6-02bae729ad8b.PNG">

..in Windows 10 OS

     
   <img width="300" src="https://user-images.githubusercontent.com/19683143/209815697-ac1149f3-be74-4d58-a4ac-ff0903697ff8.PNG">

### Expected behavior

I just want to bring to developer's attention. It would be better to clarify that this command prompt running behind the Keyman Developer dialog is an expected one or not. Thanks. 

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.21-alpha

### Operating system

Windows 11 OS

### Device

Windows Desktop

### Target application

Keyman Developer

**Comment by mcdurdin** [comment] 2023-11-01 03:12
@bharanidharanj I cannot reproduce this in version 17.0.203-alpha. Can you try and reproduce please?

**Comment by bharanidharanj** [comment] 2023-11-02 09:11
@mcdurdin I can reproduce this issue with the latest Keyman 17.0 build on Windows 11 OS (VM). 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/4f6cc362-5dee-4ffc-bca8-e4ef8a6ac017">

**Comment by mcdurdin** [comment] 2023-11-02 09:17
@bharanidharanj do you have the setting 'Show Server console window on start' switched on in Keyman Developer/Tools/Options/Server?

![image](https://github.com/keymanapp/keyman/assets/4498365/89621320-9621-46ed-aa8c-73cd8a7b9791)

**Comment by bharanidharanj** [comment] 2023-11-02 09:27
> @bharanidharanj do you have the setting 'Show Server console window on start' switched on in Keyman Developer/Tools/Options/Server?
> 
> ![image](https://user-images.githubusercontent.com/4498365/279927164-89621320-9621-46ed-aa8c-73cd8a7b9791.png)

Yes, @mcdurdin This option is enable in the 'Keyman Developer Server Options' dilaog.

**Comment by bharanidharanj** [comment] 2023-11-02 09:30
@mcdurdin Retested this issue as per your guidance on Windows 11 OS (VM) and this time, I did not see the node.js window after opening the Keyman Developer. Seems to be working fine. Thanks.

**Comment by mcdurdin** [comment] 2023-11-02 10:14
Great, thanks, I'll close this as by-design :grin:

**Closed by mcdurdin** 2023-11-02 10:14 UTC
Labels: bug, developer/, developer/ide/
