### ISSUE TITLE
bug(android): Keyboard installation problem occurs after enabling and setting keyman as the default keyboard

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#8306] opened 2023-02-23 14:16 UTC
### Describe the bug

I noticed that I was not able to add any keyboard (since the keyboard freezes after the installation) after enabling and setting Keyman as the system and default keyboard. 

### Reproduce the bug

1. Install Keyman 17.0.54-alpha build. 
2. Open Keyman In-App.
3. Open Settings menu.
4. Enable Keyman as system-wide keyboard. 
5. Enable 'Set Keyman as default keyboard'.
6 Add 'Khmer Angkor' Keyboard using 'Install Keyboard or Dictionary' option. 

Here, I noticed that after the installation, the keyboard are appear to be blank. 

I have attached the Screenshot for reference. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/220932280-3e8ccef5-05b2-494e-b9cf-653c4b9e4828.jpg">

 

### Expected behavior

Enabling and setting Keyman as the system and default keyboard should not affect the keyboard installation. 

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.54-alpha

### Operating system

Android 11.0

### Device

Redmi Note 8 Pro

**Comment by darcywong00** [comment] 2023-02-24 08:07
Sigh, this looks like a regression introduced from #8291 

Per standup, I'll revert #8291 which can close this issue, but then re-open #8291

**Closed** 2023-02-25 23:17 UTC
Labels: bug, android/, android/app/
