### ISSUE TITLE
bug(linux): Keyboard switching did not occur after pressing Control+Spacebar keys in Wasta Linux OS

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#11081] opened 2024-03-26 13:52 UTC
### Describe the bug

I observed that when using the On-Screen Keyboard in the Windows desktop, keyboard switching did not occur after pressing the Control+Spacebar keys.

### Reproduce the bug

1. Install Keyman 17.0.293-beta.
2. Open Keyman Configuration dialog. 
3. Install Khmer Angkor, Tamil99Basic and SIL_IPA keyboards. 
4. Click the Windows Search bar. 
5. Type 'Onboard' 
6. Select 'Onboard' from the options menu. 
7. Verify that an On Screen Keyboard appear at the bottom of the desktop. 
8. Press Control + Spacebar key
9. Select 'Khmer Angkor' from the keyboard list. 

Here, I noticed that the Keyboard Switching did not occur after pressing the shortcut keys. 

   <img width="600" src="https://github.com/keymanapp/keyman/assets/19683143/c386cd44-b612-421c-9f9b-15adc456325c">

### Expected behavior

Pressing Control + Spacebar key should switch to some other keyboards and the OSK should be changed to that corresponding keyboard.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [X] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.293-beta

### Operating system

Wasta 20.04 Linux OS

### Device

Desktop

**Comment by ermshiperete** [comment] 2024-03-26 17:06
Hmm, I can't reproduce this.

Does the keyboard picker show up when you press Ctrl+Space?

![image](https://github.com/keymanapp/keyman/assets/181336/9cc217f1-292c-4092-ad48-622b5e1df89f)

When you run the command in a terminal, does `ps -ef | grep keyman` show a line that contains `/usr/libexec/ibus-engine-keyman` ?

**Comment by bharanidharanj** [comment] 2024-04-03 15:19
@ermshiperete Yes, the Keyboard picker shows up when I press Ctrl+Space. Able to see the line that contains /usr/libexec/ibus-engine-keyman on the terminal. 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/3268a427-3692-4ffe-9dd5-17615d5464d5">

**Comment by ermshiperete** [comment] 2024-04-23 15:25
@bharanidharanj Is this still happening with the latest beta version?

**Comment by dinakaranr** [comment] 2024-05-07 16:11
@ermshiperete I tested this issue in Keyman 17.0.319-beta (package version 17.0.319-1~sil1~focal) on Linux Wasta. I have followed the above comment instructions. Keyboard Picker shows up when pressing the CTRL + spacebar, and then the keyboard switches to the next keyboard. It reflected on the "on-screen keyboard" too. It works well. Thanks.

**Comment by ermshiperete** [comment] 2024-05-08 09:28
Closing, since it seems things are working.

**Closed by ermshiperete** 2024-05-08 09:28 UTC
Labels: bug, linux/
