### ISSUE TITLE
[Web] OSK displays keys that it shouldn't

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#1460] opened 2019-01-01 23:13 UTC
Moving from https://github.com/sillsdev/keyman-keyman.com/issues/216

Keyman OSK files do not have a keystroke assigned and don't show anything on Keycap
![capture](https://user-images.githubusercontent.com/7071907/48724026-d057ed80-ebed-11e8-8c71-13114b767366.PNG)

When I go to the KeymanWeb page (https://keymanweb.com/?_ga=2.140668978.1275583547.1542643542-227799419.1521670190#ug-Arab,Keyboard_basic_kbdughr):
I see this:
![image](https://user-images.githubusercontent.com/7071907/48723112-676f7600-ebeb-11e8-8d26-a056babd576d.png)
where QWERTY... is displayed even though those keys do not work (intentionally).
Is this a bug in the keyboard or in the KeymanWeb site? It affects quite a few keyboards.

**Comment by jahorton** [comment] 2019-01-02 02:46
That's been a part of KeymanWeb's design since I joined the project - if there is no keycap specified for a key on either the 'default' or basic 'shift' layer of the keyboard, KeymanWeb will automatically assign it a default keycap _and_ default key output based on US English.

I believe the reasoning was something like this:  when the user physically types the 'a' key with the Uyghur keyboard active within KeymanWeb, there's no code to handle that key, so control reverts to the browser - which will automatically output the default character for that key.  To ensure equality between physical keystrokes and those of the OSK, we make the OSK reflect this - but since KeymanWeb can't auto-detect the user's keyboard system settings, we have to assume a default... and US English was selected for that.

**Comment by jahorton** [comment] 2019-01-02 02:48
Also, it'd take me a while to dig up specific examples, but I'm near-positive that removing this would break other existing keyboards that rely upon this 'feature' within KeymanWeb.

**Comment by DavidLRowe** [comment] 2019-08-01 18:53
@jahorton Can you unpack "...without deliberate keycap specifications..."? 
If a keyboard is using  `+ [K_Z] > nul` to block a key from generating output, what more does it need to do to make the keycap blank for that blocked key?
(ref: keyboards PR #838 (https://github.com/keymanapp/keyboards/pull/838), now merged as release/basic/basic_kbdinbe2)

**Comment by jahorton** [comment] 2019-08-02 00:03
@DavidLRowe Unfortunately, at present I don't believe that the keyboard compiler actually looks at keyboard rules to determine this information.  It's solely based on whatever the developer has assigned for a keycap; leaving the keycap empty won't help.

That said, if it's possible to assign the keycap the non-breaking space character as text, that should pass through KMW without issue.  A tweak to allow standard spaces as key text might be possible, but I'm not sure if Developer would support compiling that in keyboard layouts; that'd take investigation on our end.

**Comment by mcdurdin** [comment] 2019-08-02 00:31
I think there is some misunderstanding here. The original issue arose because the .kvks file specifies a blank key cap, then KeymanWeb should be respecting that spec. However, it doesn't seem to be following that. Whether that's an issue in the compiler or in the loading of the KVK data, I don't know. It doesn't relate to the keyboard rules at all.

**Comment by DavidLRowe** [comment] 2019-08-31 12:06
@jahorton Can you confirm my understanding, or correct me if I'm mistaken? IIUC the current design requires the keyboard author to explicitly assign (for the default and shift layers in the OSK) a U+00A0 (No-break space) to a keycap whose output has been blocked, otherwise the character from the en-US keyboard will be displayed.

These undesired keycaps show up in the OSK displayed when using the keyboard in a browser and when the keyboard image is displayed by `<div id='osk-tablet' data-states='default shift'>` in the .php help files.

**Comment by mcdurdin** [comment] 2019-09-02 01:05
Let's try and get this fixed in 12.0 beta (or else early in 13.0) rather than pushing more work into keyboard maintenance that we then want to undo in the future.

**Comment by jahorton** [comment] 2019-09-02 08:54
We'll need to make extra sure this doesn't break any existing keyboards; I believe some exist that rely on this functionality, as it was originally considered a feature, not a bug.  I'll be sure to run the regression test suite and do a before-and-after to check for this.

**Comment by jahorton** [comment] 2019-09-04 06:23
OK, ran the KMW batch renderer.  It wasn't able to process every keyboard, and there was a lot of data that passed by, but I was able to document the following:

Relies on the bug:
- `deneunicode` - has a LOT of empty keycaps.
- `isis_bangla` - the symbol keys
- `isis_devanagiri` - same
- Actually, all `isis_*` keyboards rely on this.
- `kannada_kab`, for a couple of symbols
- `klallam2` - has a LOT of empty keycaps
- `krung` - the symbol keys
- `mozhi_1_1_0`, `mozhi_5_1` - numbers + some symbols
- `orviet10` - a colossal amount of missing keycaps.
- `phoneticmalayalam` - symbols
- `sabdalipiunicode` - symbols
- `sil_cameroon_qwerty` - a couple of symbols
- `tamil99m` - numbers, symbols
- `tir_er_uni_ez` - numbers, symbols
- `venetian` - almost no specified keycaps
- `yolngu21` - very few specified keycaps

Considers issue to be a bug
- `dlia25bas`
- `greenlandic` a couple.
- `sil_bengali_phonetic` - affects a couple of keys
- There were a significant number of other keyboards with just a couple missing keycaps; they often provided 'beep' feedback or similar.

Since it does seem that the way forward is to eliminate reliance upon the default keycaps, I prioritized documenting the keyboards reliant upon it.  Please do not use construe this limited, incomplete documentation as an intentional argument against changing the existing behavior, although it does imply a lot of work will be needed before we can safely implement the change.

**Comment by jahorton** [comment] 2019-09-05 04:50
As decided in alternate communication channels:

> We could check the compiler version of the compiled keyboard
> 
> If earlier than 12, use old behaviour. Because we aren’t the only people distributing keyboards.
>
> Yeah. Breaking version change for keyboard interpretation will only apply to keyboards compiled with a later version of compiler. Of course we still need to fix the keyboards in the repo but avoids breaking deployed ones.

**Comment by mcdurdin** [comment] 2019-09-06 01:17
So, with the version check, only 1 keyboard needs fixing in the keyboards repo! Krung :) I checked all the others; see https://github.com/keymanapp/keyboards/pull/878 for details.

Note that this fix won't impact the keyboards repo until after 12.0 release anyway, when we update the compiler in the keyboards repo to the stable-12.0 version.

**Closed** 2019-09-06 05:21 UTC
Labels: bug, modification, web
