### ISSUE TITLE
bug(android): Predictive text functionality is not available after installing a new keyboard in Android 5.0 OS

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#9946] opened 2023-11-06 13:21 UTC
### Describe the bug

After the installation of a new keyboard, the predictive text no longer appears on the suggestion banner.

### Reproduce the bug

1. Install Keyman 17.0.205 build. 
2. Open Keyman In-App. 
3. Install Khmer Angkor keyboard. 

Here, I noticed that after the installation, the predictive text was missing on the suggestion banner. 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/817785b4-2a58-40ff-b7eb-c2ba3da6a911">

### Expected behavior

After the installation of the new keyboard, the predictive text should be available on the suggestion banner. 

### Related issues

#9894

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.205 alpha 

### Operating system

Android 5.0 lollipop

**Comment by bharanidharanj** [comment] 2023-11-06 14:59
After installing Khmer_Angkor keyboard, an error message appear on the screen. I have attached the Screenshot for reference. 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/11f27364-3e7b-41e3-a815-2229936dbe8f">

**Comment by jahorton** [comment] 2023-11-08 07:36
Duplicate of #9443.  The underlying cause is the same.

**Closed by jahorton** 2023-11-08 07:36 UTC
Labels: bug, android/
