### ISSUE TITLE
feat(touch): select default long-press key when no movement detected

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#8519] opened 2023-03-27 01:49 UTC
### Describe the solution you'd like

Currently in version 16.0.138 of Keyman for Android, long-pressing a particular key shows key(s) as pop-ups to select one.

After focusing the pop-up key using touch, releasing the touch will trigger that key.

If we can make focus to the first key among the pop-up keys set by simply long-pressing only, it will be useful to users to type using keys that have one option under long-press.

Kind attention is invited to this matter to add to a future milestone.

### Keyman apps

- [X] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0.138

**Comment by mcdurdin** [comment] 2023-03-28 08:03
Closely related to #1025

**Comment by darcywong00** [comment] 2023-08-08 00:51
> If we can make focus to the first key among the pop-up keys set by simply long-pressing only, it will be useful to users to type using keys that have one option under long-press.

My concern is if we default the focus to the first key among the pop-up keys, how would the user "cancel" the long-press? I can see a common case where a user is discovering what the longpress on each key is, and likely won't want that output by default.

**Comment by mcdurdin** [comment] 2023-08-08 00:58
* Default will be selectable by keyboard designer -- _not_ necessarily the first, and may be _none_.
* Where there is a default will be indicated by highlighting it in the longpress -- the normal selection highlight.
* Given that cancel is _not_ the preferred default action for a longpress, the user can cancel the longpress default by sliding outside the 'acceptance' area -- e.g. south of the key cap, which would then unhighlight the default and indicate visually that no output would occur when they release their finger.

**Comment by mcdurdin** [comment] 2023-08-08 00:59
This is a duplicate of #9416.

**Comment by mcdurdin** [comment] 2023-08-08 04:10
Will track in #9416.

**Closed by mcdurdin** 2023-08-08 04:10 UTC
Labels: duplicate, web/, android/, ios/, feat
