### ISSUE TITLE
Code text box can't be pasted to or copied from

### ISSUE THREAD

**Issue by rmlockwood** [keymanapp/keyman#2804] opened 2020-03-10 12:22 UTC
The Code text box in the Touch Layout design view can't be pasted to or copied from using the common Windows copy-paste shortcuts. It would help development greatly if this could be working.

**Comment by mcdurdin** [comment] 2020-03-11 09:03
Duplicate of #2676.

Please follow there (you can subscribe to notifications on the right hand side of the issue).

**Closed by mcdurdin** 2020-03-11 09:03 UTC
Labels: bug, developer
