### ISSUE TITLE
If KeymanMac (or LaoScript) is active when Mac is locked, then cannot switch to other keyboard for unlock

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#172] opened 2017-08-16 08:52 UTC
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Sunday May 28, 2017 at 02:12 GMT_
_Originally opened as https://github.com/sillsdev/keyman/issues/25_

----
For the password thing, what I actually mean is there is a bug (I think) 
when using the latest version of LaoScript on older version of OSX (in my 
case 10.8.5). 
I normally set my mac to lock itself after it is sleep or begin the screen 
saver. 
So when I wake my mac or leave the screen saver, I will see the login 
screen. 
Then I must enter the password in order to login to my mac. 
The problem is, if I leave my current keyboard layout to LaoScript before 
my mac go to sleep or begin the screensaver. 
The password will be incorrect. 
I think it is because my keyboard layout doesn't change back to english for 
me to enter the correct password. 
Keyboard shortcut combinations to change the keyboard layout on the login 
screen doesn't work. 
Only way to login to my mac again is to restart the machine. 
This problem doesn't occur on my newer mac using OSX 10.11.5. 

(See case 72576)

**Comment by tombogle** [comment] 2017-09-12 13:21
I see something similar on Sierra. It **appears** to change back to the English system keyboard, but it doesn't actually. However, it _is_ possible to go up to the little icon and click the US flag icon to (re)force the keyboard back to English. However, since it already shows that that keyboard is selected, it might not very very apparent to many users that this would fix it.

**Comment by tombogle** [comment] 2017-10-27 02:47
Wow, it looks like Apple has made it crazy hard to get older versions of the OS. A few older posts suggest that registered developers can get them, but newer posts suggest it's impossible and I can't find any download link. The entry in the AppStore won't work because it detects that I have a new machine that already has Sierra.

**Comment by tombogle** [comment] 2017-10-30 20:10
I've now got 10.8.5 running in a VM in Parallels. I did a simple test using my test Input Method, and I have no trouble entering the password. So far, I haven't been able to get a keyboard to install in Keyman, so I haven't been able to try that yet.

**Comment by tombogle** [comment] 2017-10-30 21:04
Okay, I found and fixed the thing that was causing Keyman to crash (silently) when trying to install a keyboard. I've tested it with both Amharic and Lao 2008 Basic and it works fine. Based on what I see when I change the password in Settings, it seems the OS actually forces it back to the US English keyboard when it detects that it is working with a password field. I did find another bug that prevents  downloading keyboards on 10.8.5, so it seems that Keyman is only minimally usable on versions of the OS before 10.9 anyway. I'm going to close this as not-reproducible.

**Closed by tombogle** 2017-10-30 21:04 UTC
Labels: mac
