### ISSUE TITLE
bug(ios): Keyman won't stop backspacing 

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#6735] opened 2022-06-09 09:14 UTC
**Describe the bug**

https://user-images.githubusercontent.com/28331388/172810240-7e77c3d2-1156-41d0-b7a9-8aaeecc63f13.mp4

In-app, Keyman won't stop backspacing after several backspacing was triggered.

---

**Keyman for iPhone/iPad/Android:**
 - Device: iPod 7th 
 - OS: 15.4.1
 - Keyman version: 15.0.258 of https://github.com/keymanapp/keyman/pull/6714
 - Target application: Keyman

---

**Keyboard**
 - Keyboard name: EuroLatin (SIL)
 - Keyboard version: 1.9.6
 - Language name: English

**Comment by jahorton** [comment] 2022-06-10 06:43
Duplicate of #1930, even if noted on a different platform.

**Comment by mcdurdin** [comment] 2022-06-11 00:03
If this happens, in the past it has been because a javascript error has caused the backspace touchend to fail to cancel the timer. I wonder if there are any JS errors we can locate on sentry?

**Comment by jahorton** [comment] 2022-06-16 04:47
Managed to get a repro by super-rapid clicking the backspace key in Simulator - with both the left AND right mouse buttons.  (Both are translated into plain touches, so it works.)

------

And, well, _that_'s fascinating...

![image](https://user-images.githubusercontent.com/25213402/173993170-bd4dbc4b-7d36-42e9-89f4-53bfd7612df1.png)

The repeated-deletion is being triggered by the instance that is not currently set as `keyman.osk.vkbd`.  But... why on earth are there two separate, live instances?

**Comment by jahorton** [comment] 2022-06-16 05:02
Oh wow.  So it actually triggered _on_ the repro!

_After_ the app and keyboard fully loaded, I set a breakpoint in `VisualKeyboard`'s constructor to attempt to catch the culprit.  The result?

![image](https://user-images.githubusercontent.com/25213402/173994451-eba5e951-057e-4596-a4d9-364b025ab076.png)

So, for... whatever reason... some aspect of the interaction with WebKit (I'm guessing) triggered Swift code that in turn triggered a call to set the keyboard's height.  Here's the thing, though...

![image](https://user-images.githubusercontent.com/25213402/173994663-6f07e2f8-0fe4-4524-8680-718a1ae7c1be.png)

And guess what `osk.Load()` does?  _It rebuilds the keyboard completely._

So, since this happens literally _on_ a backspace trigger... well... we get a resistant, sticky backspace!

The most unclear part of this, obviously, is:

> So, for... whatever reason... some aspect of the interaction with WebKit (I'm guessing) triggered Swift code that in turn triggered a call to set the keyboard's height.

... why _did_ this get triggered?  Is it something we can deactivate on the WebView?  But, even then... we ought be able to work around this.

**Comment by jahorton** [comment] 2022-06-16 05:37
Alas, this repro doesn't seem to be triggering the issue on Android, or at least not in Android Studio.

**Closed** 2022-06-29 06:28 UTC
Labels: bug, web/, ios/
