### ISSUE TITLE
bug(developer): Typed capital letter displaying as small letter in the preview panel while using the sil_cameroon_qwerty keyboard

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#11325] opened 2024-04-30 12:18 UTC
### Describe the bug

I noticed that the typed capital letter appeared as a small letter in the preview panel while using sil_cameroon_qwerty keyboard. 

### Reproduce the bug

Steps to Reproduce:
1. Install Keyman Developer 18.0.24 on Windows 11 OS.
2. Open sil_cameroon_qwerty project. 
3. Compile it. 
4. Click the build tab. 
5. Click Test Keyboard on Web button. 
6. Click the localhost web address. 
7. Click Open in browser button. 
8. Select "sil_cameroon_qwerty" from Keyboard list and Select "iPhone S5" from the Device list. 
9. Click the tricolor button. 
10. Enable the Shift key. 
11. Press any letter key from the keyboard. 

I noticed that the typed capital letter appeared as a small letter on the preview panel. 

I have attached the video file for reference. 

https://github.com/keymanapp/keyman/assets/19683143/bab1b3f7-b3ee-4bd7-9257-35343e6a0f2e

### Expected behavior

The capital letter should be displayed after typing the letter from the Shift layer.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

18.0.24

### Operating system

Windows 11 OS (VM)

### Keyboard name

sil_cameroon_qwerty

### Language name

sil_cameroon_qwerty

**Comment by mcdurdin** [comment] 2024-05-01 04:22
I am unsure if this is a bug in the keyboard or Keyman Engine. Will investigate.

**Comment by mcdurdin** [comment] 2024-05-01 04:34
@bharanidharanj I am unable to reproduce this problem. Are you using the latest version of sil_cameroon_qwerty (6.1.0)?

**Comment by bharanidharanj** [comment] 2024-05-03 11:55
> @bharanidharanj I am unable to reproduce this problem. Are you using the latest version of sil_cameroon_qwerty (6.1.0)?

@mcdurdin I am using sil_cameroon_qwerty (6.0.6) Version. Okay, I will retest it and add my comment. Thanks.

**Comment by bharanidharanj** [comment] 2024-05-03 12:38
@mcdurdin I observed that Keyman Developer is linked to the older version of the sil_cameroon_qwerty keyboard file, which is causing the problem mentioned above. I tested this with the latest Keyman Developer 18.0.26 and encountered the same issue.

**Comment by mcdurdin** [comment] 2024-05-06 01:55
Okay, I have reproduced this with sil_cameroon_qwerty 6.0.6 and have verified that it is already resolved in 6.1.0 -- this is a keyboard bug, not a Keyman bug in this instance.

Will go ahead and close this issue :grin:

**Closed by mcdurdin** 2024-05-06 01:55 UTC
Labels: bug, developer/
