### ISSUE TITLE
bug(iOS): 'Click here' link button is not working in Welcome to Keyman Help page

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#6678] opened 2022-05-30 14:41 UTC
**Describe the bug**
Clicking on the 'Click here' link does not open the Getting Started page. 

**To Reproduce**
1. Go to Keyman In-App. 
2. Click on Info button from the view. 
3. Verify that the Keyman for iPhone and iPad 15.0 Help page opens. 
4. Click 'Welcome to Keyman' link. 
5. Verify that the Welcome to Keyman page opens. 
6. Click on the 'Click here' link. 

I noticed that the page does not open the Getting Started page. 

**Expected behavior**
By clicking the "Click here' link should open the corresponding page. 

**Screenshots**
..iPhone 13 Pro Max
<img width="300" src="https://user-images.githubusercontent.com/19683143/171014873-4fa31a68-cef8-4294-8793-7b5f36705c55.png"> 

..iPad 9th generation
<img width="300" src="https://user-images.githubusercontent.com/19683143/171014996-fad11a2c-2b1e-4879-8a8d-e4f5161e561e.png"> 

---

**Keyman for iPhone/iPad:**
 - Device:  iPhone 13 Pro Max, iPad (9th generation) Simulators
 - OS: iOS 15.0
 - Keyman version Keyman 15.0.253-beta
 - Target application:  Keyman In-App

---

**Keyboard**
 - Keyboard name: English (EuroLatin)
 - Keyboard version: 1.9.6
 - Language name: English

**Additional context**
I am not seeing this issue in Android OS (API emulators).

**Comment by jahorton** [comment] 2022-06-01 05:40
Duplicate of #6653.

**Closed by jahorton** 2022-06-01 05:40 UTC
Labels: bug
