### ISSUE TITLE
bug(android): Shift Key acts as Capslock key in Keyman 15.0.259 beta

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#7209] opened 2022-09-05 14:58 UTC
**Describe the bug**
I noticed that after clicking the Shift Key then pressing any character keys results the output with all capital letters on the text pane. 

**To Reproduce**
1. Install Keyman 15.0.259 beta build. 
2. Open Keyman app. 
3. Here, I noticed that the Shift key appears in the disabled state. (All letters appears in the lower character)
4. Press or Enable the Shift Key. 
5. Start typing some words using OSK. (eg., Testing)
6. Here, I noticed that all letters appearing in upper characters. (eg., TESTING)
7. Press or Disable the Shift Key. 
8. Start typing some words. 
9. Here, I noticed all the letters are appearing in lower characters. 

It seems that the Shift Key acts as a Capslock Key in Keyman 15.0.259 Beta build. Also, I got an Keyboard error message while randomly typing using the OSK. 

**Expected behavior**
The Shift Key automatically changes to its default layer after I press a character key. 

**Screenshots**
Shift Key as Capslock Key:

   <img width="300" src="https://user-images.githubusercontent.com/19683143/188476664-6316ad36-20c3-418c-85f3-b20739d993cb.jpg">

Random Error message:

   <img width="300" src="https://user-images.githubusercontent.com/19683143/188476675-fe8ec0e8-522e-4798-8a42-95da4c4a70cf.jpg">

---

**Keyman for Android:**
   Device:        Redmi Note 8 Pro
 - OS:            Android 11.0 
 - Keyman version:     15.0.259-beta
 - Target Application: Keyman In-app

---

**Keyboard**
 - Keyboard name:    English - EuroLatin(SIL)
 - Keyboard version: 2.0
 - Language name:    English

**Additional context**
I noticed that 'Install updates' option is available in the Keyman menu list. After I upgraded the Egnlish - EuroLatin (SIL) Keyboard, I am not able to reproduce the above issue.

**Comment by mcdurdin** [comment] 2022-09-05 22:03
We don't need to test the 15.0 beta series any more, because 15.0 is now in stable release. I expect both of these issues have been addressed in the latest 15.0 stable; if you reproduce them in 15.0.269, please re-open this issue :grin:

**Closed by mcdurdin** 2022-09-05 22:03 UTC
Labels: bug

**Comment by bharanidharanj** [comment] 2022-09-06 14:40
@mcdurdin Okay. I have tested this issue in 15.0.269 build and it seems to be working fine. Thanks Marc for your comments. :-)
