### ISSUE TITLE
bug(android): the keyboard disappears when switching between keyboards

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4476] opened 2021-02-11 07:34 UTC
**Describe the bug**

When Keyman is set as a system and default keyboard, try and switch between keyboard would make the keyboard disappear until the user touch the input area.

**Expected behavior**

The keyboard should be switched to the one the user want right after s/he chooses off of the keyboard menu.

---

**Keyman for Android:**
 - Device: Pixel 2 API 29
 - OS: Android
 - Keyman version 14.0.241-beta
 - Target application: 
    - Email (Google) v2019.05.12.250526289, 
    - Google Calendar v2020.44.1-340608778
    - Youtube.com search box on Chrome v74.0.3729.185

**Additional Context**
This behavior does not occur when testing with the Google Omni box, Youtube and Message apps.

**Comment by mcdurdin** [comment] 2022-03-11 06:18
If we have time in B15 I would like to bring this forward.

**Comment by darcywong00** [comment] 2022-10-28 07:05
I can't reproduce this with 16.0.90 alpha, possible due to our globe key changes.
* When 1 Keyman system keyboard is installed, short-pressing the globe key now advances to the next system keyboard (e.g. Gboard)
* When 1 Keyman system keyboard is installed, long-pressing the globe key displays the Keyman keyboard picker menu. Dismissing that menu brings the Keyman keyboard OSK back.
* When 2+ Keyman system keyboards are installed, short-pressing the globe key toggles betwen the Keyman keyboards

@MakaraSok  - can you verify?

**Comment by bharanidharanj** [comment] 2022-11-04 13:20
@darcywong00 Retested this issue with the latest Keyman 16.0.96-beta build in my Android mobile (Redmi Note 8 Pro) Ver 11.0 and I was not able to reproduce the same. Able to switching between different keyboards in various applications like Youtube (Search bar), Google Calender and Email (Google) etc., Seems to be working fine in the latest build. Thanks.

**Comment by darcywong00** [comment] 2022-11-04 13:45
Closing as unable to repro

**Closed by darcywong00** 2022-11-04 13:45 UTC
Labels: bug, android/, android/app/
