### ISSUE TITLE
bug(windows): update already and check again?

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4834] opened 2021-03-31 10:08 UTC
**Describe the bug**

Check for Updates was triggered and an update for one of the keyboard was found. OK to initiate the update, once it complete, a dialog popped as notifying there is "No updates are currently available" as if the user was trying to check for the update again. It sounds counter intuitive, for an update has just been checked and made.

![image](https://user-images.githubusercontent.com/28331388/113127188-aa719780-9242-11eb-8787-f7b31b76b6ee.png)

**To Reproduce**

Install an older version of a keyboard, i.e. Khmer Angkor 1.0.7 ([khmer_angkor.zip](https://github.com/keymanapp/keyman/files/6235715/khmer_angkor.zip)).
1. Now go to Configuration > Support then click on 'Check for Updates'
2. Click on OK to update
3. Wait for it to finish the update

**Expected behavior**

The dialog should better inform the user that the keyboard has already been updated rather than what is now shown in the screenshot.
---

**Keyman for Windows:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 14.0.270
 - Target Application: Keyman

---

**Keyboard**
 - Keyboard name: khmer_angkor
 - Keyboard version: 1.0.7 --> 1.0.8
 - Language name: Khmer

**Comment by mcdurdin** [comment] 2021-03-31 21:02
Duplicate of #4746 😁

**Closed by mcdurdin** 2021-03-31 21:02 UTC
Labels: bug, windows/, windows/config/
