### ISSUE TITLE
bug(developer): install update on the fly gives an error

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#5001] opened 2021-04-30 02:41 UTC
**Describe the bug**

While working on Keyman Developer 14.0.272, Check for Updates from the Help menu and Install the update if available. Follow the screen and at the of the process this would appear:

![image](https://user-images.githubusercontent.com/28331388/116641921-e9a51c80-a997-11eb-8e26-e811c7c37698.png)

A little while later, a box popped up asking to restart to complete the setup -- like no error was happening...

![image](https://user-images.githubusercontent.com/28331388/116642207-7bad2500-a998-11eb-9092-f16aeb4de3f9.png)

> Details for error report for Keyman app:
>   Application Identifier: tike-14.0.272
>   Error Identifier: 45BCD1352AB04A52512FCD8B44995421

---

**Keyman Developer:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman Developer version: 14.0.272 updated to 14.0.273

**Comment by mcdurdin** [comment] 2021-05-02 04:49
Duplicate of #4700; will close in favour of that one.

**Closed by mcdurdin** 2021-05-02 04:49 UTC
Labels: bug, developer/
