### ISSUE TITLE
bug(mac): The configuration dialog does not open when clicking the "configuration" button in the "About" pane.

### ISSUE THREAD

**Issue by dinakaranr** [keymanapp/keyman#12544] opened 2024-10-15 12:09 UTC
### Describe the bug

Clicking the "Configuration" button does not bring up the Configuration dialog. The "about" dialog gets closed instead.

### Reproduce the bug

Steps to reproduce:

1. Installed the Keyman 18.0.128-alpha-local daily CI build in the MacOS Sonoma.
2. Select the "keyman" icon on the toolbar.
3. Open the "OSK" by clicking the icon on the "keyman"/On-screen Keyboard.
4. Open the "Keyman Configuration" dialog by clicking the icon on the "keyman"/configuration.
5. Installed the "Tamil99" keyboard by clicking the "Download Keyboard..." button.
6. Select the "Tamil99" keyboard.
7. Open the About dialog by clicking on the "Keyman"/About.
8. Close the  "Keyman Configuration" dialog.
9. Click the "Configuration..." button on the About dialog.
Actual Results: The Configuration dialog does not appear after clicking the "Configuration" button. Instead, the "about" dialog is closed.
Please refer to the video file
https://github.com/user-attachments/assets/97982d04-6602-41f3-9cb4-8e4c8f2aef11

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [X] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

Keyman 18.0.128-alpha-loca

### Operating system

macOS Somona

### Device

mac mini

**Comment by mcdurdin** [comment] 2024-10-18 02:22
Duplicate of #8638

**Closed by mcdurdin** 2024-10-18 02:22 UTC
Labels: bug, duplicate, mac/
