### ISSUE TITLE
[ios] System keyboard banner position is crammed against top of OSK

### ISSUE THREAD

**Issue by rfaramir** [keymanapp/keyman#1955] opened 2019-08-08 21:18 UTC
System keyboard banner position is crammed against top of OSK instead of having small margin:

**To Reproduce**
1. Add Keyman as a System Keyboard (in Apple's Settings->General->Keyboard->Keyboards)
2. Go to a place where the System let you enter text
3. Activate a Keyman keyboard for a language that has a lexical model

**Expected behavior**
The suggestions should have a little bit of buffer space above them.

**Screenshots**
![image](https://user-images.githubusercontent.com/45110266/62738414-e31e8680-b9f7-11e9-9629-5d94308e470b.png)

---
 - Device: iPhone 7
 - OS: iOS version = 12.3.1
 - Keyman version 12.0 beta (very first)
 - Target application: Keyman

**Comment by jahorton** [comment] 2019-08-09 08:43
I'm not sure what we'd have done to fix this since this was posted, but I'm not seeing this, at least not when using it in the Simulator (iPhone 7).

**Comment by jahorton** [comment] 2019-08-26 04:12
We haven't seen this in testing for reproduction since the initial pre-beta test; we'll assume this has been fixed by more recent work.

**Closed by jahorton** 2019-08-26 04:12 UTC
Labels: bug, ios
