### ISSUE TITLE
bug(ios): in iOS system-wide Keyman keyboard not launching

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#9660] opened 2023-10-02 19:44 UTC
### Describe the bug

in iOS system-wide Keyman keyboard not launching 
this started from build 17.0.183
same issue is continuing in 17.0.184

### Keyman apps

- [ ] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.183

### Operating system

iOS 17.0.2

### Device

iPhone 13 pro max

### Target application

notes, mail, any app

### Keyboard name

any keyboard, EuroLatin (SIL)

### Keyboard version

2.0.4

### Language name

English

**Comment by MayuraVerma** [comment] 2023-10-03 20:53
17.0.185-alpha is still failing launch system-wide keyboard

**Comment by mcdurdin** [comment] 2023-10-04 03:32
Can you give some more details? I am not able to reproduce this here. Perhaps a step-by-step or a screen capture?

**Comment by MayuraVerma** [comment] 2023-10-04 03:39
This is notes app, same happens everywhere. Keyman keyboard do not load.

https://github.com/keymanapp/keyman/assets/14062593/a3c9db18-8c54-4d16-8d76-e64542cd9645

**Comment by mcdurdin** [comment] 2023-10-04 05:09
Thanks for the video. Have you tested with an earlier build? Can you try a stable-16.0 or an earlier 17.0 build so we can narrow the issue down? I am wondering if it relates to iOS 17.0?

**Comment by MayuraVerma** [comment] 2023-10-04 09:54
Yes I am using only alpha builds
Upto 17.0.182 alpha, it was running smooth

I have reinstalled 182 after these crashes, 182 still works

**Comment by MayuraVerma** [comment] 2023-10-04 20:47
New build 17.0.186 also same issue

**Comment by sgschantz** [comment] 2023-10-05 06:31
Unable to reproduce on an iPhone Xs Max with Keyman 17.0.186-alpha running on iOS 17.0.1 or 17.0.3.

So a different device and not exactly the same iOS version, but it at least does not look a universal iOS 17 issue.

Also tried with Allow Full Access on and off, but that only reveal the iOS 16 Allow Full Access problem, and I could still switch keyboards.

**Comment by MayuraVerma** [comment] 2023-10-05 23:12
1 updated iOS to 17.0.3
2 Keyman to 17.0.186 alpha
3 restarted the phone

System-wide Keyman keyboard is launching fine now!

Not sure, if it was related to restarting the phone or something else.

**Comment by mcdurdin** [comment] 2023-10-06 01:00
That's great news. Thanks for the update. We will go ahead and close this and hopefully it was just a transient issue.

**Comment by MayuraVerma** [comment] 2023-10-15 02:40
Even the new updates are doing the same. Keyman OSK do not want to launch after update. Restart is required to launch Keyman OSK successfully.

**Comment by mcdurdin** [comment] 2023-10-15 22:46
OK, we'll keep monitoring this. We still cannot reproduce the problem locally though 😢

**Comment by sgschantz** [comment] 2023-11-24 09:32
Still unable to reproduce and have not seen any similar reports. If there are any more detailed steps to consistently reproduce, then please add them here.

**Comment by MayuraVerma** [comment] 2023-11-24 13:16
In 17.0.215 and 216 OSK is launching after installing the update without needing to restart the phone

**Comment by mcdurdin** [comment] 2023-11-24 19:05
Great, thank you for the update, we'll go ahead and close this issue.

**Closed by mcdurdin** 2023-11-24 19:05 UTC
Labels: bug, ios/

**Comment by MayuraVerma** [comment] 2023-12-25 20:53
Same issue is again recurring 

After the update, Keyman system-wide keyboard would not launch

Under system settings, if I remove "Keyman" and add it back, then Keyman launches but without the suggestion bar.

If this helps isolating the issue
