### ISSUE TITLE
bug(developer): changes to touch layout are not kept

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#5105] opened 2021-05-19 05:25 UTC
**Describe the bug**

Longpress keys set on tablet layout does not show on Chrome emulator nor a physical device. The screenshot below shows a keyboard which have longpresses on all vowels on the default layer, but none is shown when testing on the emulator and physical device.

The KD seems to not accepting the changes made to the layout. As soon as it is closed and reopened the changes made to the tablet touch layout vanished and reset to the [version](https://github.com/keymanapp/keyboards/pull/1472) before the changes were made.

![image](https://user-images.githubusercontent.com/28331388/118758138-a227f700-b898-11eb-81eb-52c29fd0cfaa.png)

However, it is interesting that if this [code block](https://docs.google.com/document/d/1xQRu52ufiXUmrK9jeGOdWe9GjdsLrpGx4VUji0KLFvY/edit?usp=sharing) is pasted into the touch layout file `sil_madi.keyman-touch-layout` in the source folder, the longpresses are visible when testing again on Chrome emulator.

The same effect is not experienced when pasting it in the code view in KD though.

**To Reproduce**

1. Get this keyboard source
2. Try and paste the code block above in the code view on Touch Layout tab
3. Change to the design view and verify all longpresses are visible
4. Initiate test keyboard on web
5. See error

---

**Keyman Developer:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman Developer version: 14.0.274

---

**Keyboard**
Keyboard name: [sil_madi](https://github.com/keymanapp/keyboards/pull/1472)
Keyboard version:1.0
Language name: Ma'di

**Comment by mcdurdin** [comment] 2021-05-19 20:28
> The KD seems to not accepting the changes made to the layout. As soon as it is closed and reopened the changes made to the tablet touch layout vanished and reset to the version before the changes were made.

I believe this may be fixed with #5096. Can you test with that version (now in build 15.0.49) and let me know?

**Comment by mcdurdin** [comment] 2021-05-19 20:28
Sorry, #5096 is not yet merged -- so you'd need to install the build artifact instead of 15.0.49.

**Comment by MakaraSok** [comment] 2021-05-20 06:33
Is [this](https://build.palaso.org/buildConfiguration/KeymanDesktop_TestPullRequests/269472?buildTab=artifacts) the right one to test?

**Comment by mcdurdin** [comment] 2021-05-20 22:13
> Is [this](https://build.palaso.org/buildConfiguration/KeymanDesktop_TestPullRequests/269472?buildTab=artifacts) the right one to test?

Yes

**Comment by MakaraSok** [comment] 2021-05-23 02:43
The problem persists. No longpress is shown in the Chrome emulator, even though they are all in the Design view of the Touch Layout tab.

**Comment by MakaraSok** [comment] 2021-05-23 02:44
It is worth noting that when restarting the KD, the longpresses on the touch layout (tablet) is all gone.

**Comment by mcdurdin** [comment] 2021-09-16 01:36
Can you retest this for me and document a set of steps to reproduce this? I cannot reproduce the problem here

**Comment by mcdurdin** [comment] 2021-10-07 19:41
@MakaraSok just checking on this retest?

> Can you retest this for me and document a set of steps to reproduce this? I cannot reproduce the problem here

**Comment by mcdurdin** [comment] 2021-11-10 23:03
Pinging @MakaraSok on this?

**Comment by mcdurdin** [comment] 2022-02-27 23:53
Assuming this is fixed @MakaraSok as I cannot reproduce the problem?

**Closed by mcdurdin** 2022-02-27 23:53 UTC
Labels: bug, developer/, developer/ide/
