### ISSUE TITLE
bug(macos): OSK randomly appeared?

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#6590] opened 2022-05-09 02:53 UTC
**Describe the bug**

The OSK has randomly appeared here and there every now and then, but a noticeable behavior that leads to it being shown is found while testing other PR on the UI language switching.

https://user-images.githubusercontent.com/28331388/167331495-6b31ae55-f0c4-4f9e-ad6d-a093f88ddc68.mov

**To Reproduce**

1. Switch to Keyman from the status menu and ensure that Keyman is running
2. Log out of the current User and log back in
3. Go to Settings > System Preferences
4. See error - the OSK appears briefly and then disappears.

**Expected behavior**

The OSK shouldn't have appeared when not summoned.

---

**Keyman for macOS:**
 - OS: macOS Monterey 12.3.1 / Big Sur 
 - Keyman version: 15.0.241-beta
 - Target Application: N/A

**Comment by mcdurdin** [comment] 2022-11-20 19:20
Duplicate of #5856

**Closed by mcdurdin** 2022-11-20 19:20 UTC
Labels: bug, duplicate, mac/
