### ISSUE TITLE
bug(windows): Set a hotkey for a newly added keyboard after a fresh install of Keyman

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4006] opened 2020-11-30 03:09 UTC
**Describe the bug**
All installed keyboards was removed from the keyboard list one by one in the Keyman Configuration, then Keyman was uninstalled, and then the machine was restarted.

After the reboot, Keyman was installed and then a keyboard was installed, say "Khmer Angkor". Now go to the Hotkeys tab and click on the "(none)" to set a hotkey for the keyboard. Then a crash with this message popped up:

![image](https://user-images.githubusercontent.com/28331388/100564090-977da380-32f2-11eb-9896-047927ffb0ba.png)

```
Details for error report for Keyman app:
  Application Identifier: kmshell-14.0.192-alpha
  Error Identifier: AD90128B99C34CF8B37A7659F75F988B
```

**Expected behavior**
No crash should happened when a hotkey is set after a fresh installation of Keyman.

---

**Keyman for macOS:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 14.0.192-alpha
 - Target Application: Keyman Configuration

---

**Keyboard**
 - Keyboard name: khmer_angkor
 - Keyboard version: 1.0.6
 - Language name: Khmer

**Comment by MakaraSok** [comment] 2020-11-30 03:24
This is also experienced on my Windows 10 Pro 1909 x64 when I was trying to set a hotkey for a keyboard which was just installed:

![image](https://user-images.githubusercontent.com/28331388/100565315-dc570980-32f5-11eb-8892-ca815f6c9b7b.png)

```
Details for error report for Keyman app:
  Application Identifier: kmshell-14.0.192-alpha
  Error Identifier: C9CD0FA2ECFA4D715EF669F107DA92EF
```

**Comment by mcdurdin** [comment] 2020-11-30 03:49
Diagnostic report submitted (I have a copy in projects/keyman/users/4006)

**Comment by MakaraSok** [comment] 2020-11-30 03:57
Tests have been done with various keyboards and that one happens to be for "Khmer Advanced" keyboard.

**Comment by mcdurdin** [comment] 2020-12-17 00:23
```
Exception EOleException in module kmcomapi.dll at 0055545D.
Format 'Index %0:s out of bounds' invalid or incompatible with argument.

  kmcomapi            0x2f941d2a   utilhandleexception.CaptureStackTrace (utilhandleexception.pas:59)
  kmcomapi            0x2f941e54   utilhandleexception.LogException (utilhandleexception.pas:81)
  kmcomapi            0x2f9554dd   keymanautoobject.TKeymanAutoObject.SafeCallException (keymanautoobject.pas:173)
  kmcomapi            0x2f4095bf   System.@HandleAutoException (System.pas:1)
  ntdll               0x772071b3   ExecuteHandler
  ntdll               0x771f3b35   KiUserExceptionDispatcher
  kmcomapi            0x2f95545c   keymanautoobject.TKeymanAutoObject.ErrorFmt (keymanautoobject.pas:165)
  kmcomapi            0x2f95545c   keymanautoobject.TKeymanAutoObject.ErrorFmt (keymanautoobject.pas:165)
  kmcomapi            0x2f9510b1   keymanlanguages.TKeymanLanguages.Get_Items (keymanlanguages.pas:88)
  kmshell             0x2c95bc9b   UfrmMain.TfrmMain.GetHotkeyLanguageFromParams (UfrmMain.pas:423)
  kmshell             0x2c95c87e   UfrmMain.TfrmMain.Hotkey_Set (UfrmMain.pas:645)
  kmshell             0x2c95ae62   UfrmMain.TfrmMain.FireCommand (UfrmMain.pas:323)
  kmshell             0x2c8a9cfe   UfrmWebContainer.TfrmWebContainer.cefCommand (UfrmWebContainer.pas:221)
  kmshell             0x2c81fdfb   Keyman.UI.UframeCEFHost.TframeCEFHost.Handle_CEF_COMMAND (Keyman.UI.UframeCEFHost.pas:481)
  kmshell             0x2c81fa2d   Keyman.UI.UframeCEFHost.TframeCEFHost.CallbackWndProc (Keyman.UI.UframeCEFHost.pas:387)
  kmshell             0x2c4d6db5   System.Classes.StdWndProc (System.Classes.pas:1)
  USER32              0x76ecef6a   _InternalCallWinProc
  USER32              0x76ec5ef9   UserCallWinProcCheckWow
  USER32              0x76ec3c59   DispatchMessageWorker
  USER32              0x76ec3a1f   DispatchMessageW
  kmshell             0x2c651abf   Vcl.Forms.TApplication.ProcessMessage (Vcl.Forms.pas:1)
```

Note that this is a cascading error which is masking the root cause, because the error management had a bug with formatting the error message which caused a secondary exception. Oops.

**Comment by MakaraSok** [comment] 2020-12-21 06:19
This still persists in 14.0.214-beta.

> Details for error report for Keyman app:
>   Application Identifier: kmshell-14.0.214-beta
>   Error Identifier: 14B60C8B50094CD91CE33565ABE2F0DA

**Comment by mcdurdin** [comment] 2020-12-21 06:36
I don't think the fix has been merged yet

**Closed** 2020-12-22 02:45 UTC
Labels: bug, windows/, windows/config/

**Comment by MakaraSok** [comment] 2020-12-23 02:29
Tested with 14.0.215-beta on Windows 10 Pro 20H2 x64. No crash happens when a hotkey is set after a fresh installation of Keyman.
