### ISSUE TITLE
bug(developer): New project didn't appear in 'Recent Projects'

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#10710] opened 2024-02-14 23:20 UTC
### Describe the bug

New project didn't show up in Recent Projects

### Reproduce the bug

Could not repro after first time (don't you love those)

1. Installed Developer and rebooted
2. New Project, LDML of course. Saved to custom location (`c:\projects\keyman\subdir`)
3. Edited .xml files and tested
4. Saved, closed project
5. Attempted to reopen project via home screen Recent Projects list and Project->Recent Projects menu

### Expected behavior

Project should, but did not not appear in 'Recent Projects' on home screen nor in Project->Recent Projects

### Related issues

#1306 

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.267-alpha

### Operating system

Windows 11

### Device

windows laptop

**Comment by srl295** [comment] 2024-02-14 23:23
I need to add, I must have had developer installed before, because the recent items wasn't empty, it had this item: 

![image](https://github.com/keymanapp/keyman/assets/855219/e2ce1e9b-3930-4f1d-94de-34455491f568)

so it may be the 'recent items' was leftover from an old version

**Comment by mcdurdin** [comment] 2024-02-23 04:04
I tried to repro this but was not able. Here's one attempt:

1. Uninstall all versions of Keyman Developer.
2. Remove `%appdata%\Keyman\Keyman Developer` folder, `HKCU\Software\Keyman\Keyman Developer` key.
3. Install 16.0.145 version of Developer
4. Open a project, exit Developer
5. Reopen Developer to see the project is remembered.
6. Close the project, view it in Recent Projects.
7. Exit Developer
8. Upgrade Developer to 17.0.2xx-beta
9. Start Developer, view Recent Projects, should see remembered project
10. Create a new project, close it
11. Exit Developer
12. Restart Developer -- do both projects appear?

I think given it's a one-off, probably relating to upgrade, and resolves by manually reopening the project, I am going to close this. Please feel free to reopen if you find the cause.

Note v16 had bugs in Recent Projects, so it never worked properly previously. (https://github.com/keymanapp/keyman/commit/ccbb00db9b255223d4d89358ce9ce64706e8e87e)

**Closed by mcdurdin** 2024-02-23 04:04 UTC
Labels: bug, developer/, developer/ide/
