### ISSUE TITLE
[ios] Keyman iOS app landscape orientation

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#2260] opened 2019-10-29 04:18 UTC
**Describe the bug**
If the youtube was in landscape, keyman keyboard was preselected before opening youtube app (say notes app). If keyboard is required to share the video link or post comment, keyman starts in landscape. Only the suggestion bar will be in full width, keyboard will be in the size of the portrait.

**To Reproduce**
1. keyman keyboard should be preselected before opening youtube app (say notes app).
2. Open youtube, start a video, orient the video to landscape
3. tap on share the video.
4. choose message to share the video.
5. Keyman keyboard will appear in landscape, but the width of the keys will be in portrait.

I have attached the screenshot.

**Screenshots**
![IMG_BFE59E8B6E32-1](https://user-images.githubusercontent.com/14062593/67737437-30980780-f9d9-11e9-8d97-218bf21babbe.jpeg)

  
**iPhone/iPad/Android (please complete the following information):**
 - iPhone 11 pro mac
 - OS: iOS 13.1.2 and iOS 13.2
 - Keyman version 12.0.53
 - Target application: Notes, mail, ...

**Keyboard**
 - Keyboard name: SIL EUROLATIN
 - Keyboard version: 1.8.1
 - Language name: English

**Comment by mcdurdin** [comment] 2019-10-29 04:53
@jahorton please triage and validate

**Comment by jahorton** [comment] 2019-11-05 02:47
This can be replicated in the iOS Simulator by using the Share feature from within the Keyman app.  (Unfortunately, the YouTube app isn't available for Simulator.)

This doesn't enable direct code debugging of the issue, as we can't add breakpoints to system keyboard code from the in-app context, but it does allow some investigation of the issue.

The most notable detail:  for whatever reason, the system keyboard isn't being given a correct, up-to-date width when initialized in landscape mode, at least in this context - it's still using "portrait" width.  As the keyboard specifies precise pixel coordinates, this means the OSK confines itself as seen in the screenshot above.  The predictive banner uses percentage-based scaling and so is unaffected.  A simple rotate back-and-forth corrects the issue; it's a matter of getting the correct value to the keyboard.

And after a bit more investigation... interesting.  When the WKWebView with the keyboard initializes within this context, `window.orientation == 0` is always true - no matter the actual orientation.  (Obtained via console command in developer mode, so it's still zero after all init has occurred.)  After any rotation of the device, it's correct - just not when first loaded.  Huh.  I also see this within Simulator-based Safari when loading the system keyboard in landscape orientation.

This apparently isn't something completely new to Safari, either:  http://www.williammalone.com/articles/html5-javascript-ios-orientation/  That said, it never corrects back in this context before the device is rotated.

----

Which naturally leads to the next test - how does non-embedded KMW look by default in iOS Safari landscape on load, before rotation?

<img width="964" alt="Screen Shot 2019-11-05 at 9 19 40 AM" src="https://user-images.githubusercontent.com/25213402/68173422-81959600-ffad-11e9-980c-8e26857be3a0.png">

Of course, because of how embedding works, the incorrect sizing issue looks different... but it still doesn't load correctly.  A rotation there also fixes the issue.  There is also no issue if everything is first loaded in portrait mode - just landscape.

That said... `window.orientation` is initialized correctly here, so the size issue is caused by something else.  Huh.

----

So, it seems we may have a WKWebView-only init bug when initializing in landscape.  Of course, this is a bit of a problem - `screen.width` and `screen.height` don't exchange places, and `window.orientation` is the only simple "tell" on the web-based side.  Looks like we'll need a way to either provide the true orientation at the start... or to initialize the OSK dimensions with values from the Swift when the keyboard is loaded.

----

I tested for this a bit within the Keyman app context (as in, in-app keyboard) a bit as well - this particular issue seems limited to the system keyboard.  That said, I've seen something else related occur on occasion, but the root of the issue looks to be different and may be due to Simulator emulation.  I'll make that its own issue.

**Comment by MayuraVerma** [comment] 2019-11-05 04:24
@jahorton this might help your testing, instead of YouTube, please use notes app.
Start the notes app in landscape and initiate the Keyman keyboard.

Same problem can be duplicated.

![6E70F533-6F01-4B7E-9717-7B60FED188BB](https://user-images.githubusercontent.com/14062593/68178499-db687280-ff51-11e9-8c00-492db84094ef.png)

**Comment by jahorton** [comment] 2019-11-22 07:56
It seems that the recent fixes were insufficient; the issue is still occurring in certain scenarios.

**Comment by jahorton** [comment] 2019-12-02 01:24
Further followup with the report where the error still occurs was actually from someone still using a 12.0 beta version of the Keyman app; they hadn't updated to the release, which is where the fix landed.  Re-closing.

**Closed by jahorton** 2019-12-02 01:24 UTC
Labels: bug, ios
