### ISSUE TITLE
bug(windows): Simplified Chinese keyboard only recognizes one letter at a time

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#10240] opened 2023-12-13 03:44 UTC
### Describe the bug

This bug prevents one from typing a word. It only accept the cue one letter at a time. See the issue reported by a user quoted below:

> My keyboard suddenly stopped working properly, it's not the first time, but when that happened before it got fixed after I redownloaded it, now it doesn't.
If I start writing, the consonants don't appear as an option, if I continue it just switches to the next letter as if the last one didn't exist, it only writes single vowels. F.ex. I want to write "lao: "l" will be dismmissed, so will "a", it will write just "o" and offer the options for that and nothing else.

### Reproduce the bug

https://github.com/keymanapp/keyman/assets/28331388/a77eef45-b84e-419c-a636-a47421a5b7c3

### Expected behavior

Don't suggest words one letter at a time, but a word or a string of letters at a time.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [X] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

Keyman 14.0.144 stable

### Operating system

Windows 10 Pro 22H2

### Device

VirtualBox Machine

### Target application

Notepad

### Keyboard name

cs-pinyin

### Keyboard version

1.3

### Language name

Mandarin Chinese

### Additional context

https://keyman.com/keyboards/cs-pinyin

**Comment by rc-swag** [comment] 2023-12-15 05:00
See this issue #6588

**Comment by mcdurdin** [comment] 2024-01-02 04:41
Closing as duplicate of #6588.

**Closed by mcdurdin** 2024-01-02 04:41 UTC
Labels: bug, duplicate, windows/
