### ISSUE TITLE
Problem reaching all functions, when language list is very long

### ISSUE THREAD

**Issue by safolit** [keymanapp/keyman#2245] opened 2019-10-25 02:42 UTC
**Describe the bug**
In Keyman desktop for windows it is not possible to reach the functions Texteditor, Configuration, Help, Exit, if there are too many languges installed.
Happens if screensize is less than the length of language list.

**To Reproduce**
1. Install a lot of languages in keyman
2. Reopen keyman desktop.

**Expected behavior**
Maybe a scrollbar or a more button for a very long language list.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/52272980/67539062-348f0580-f70b-11e9-8f7c-86b378a8017e.PNG)

It is a fake screenshot, because I already removed a lot of languages. But this is what it looked like.
But the window covered the complete height of the screen

---

**Keyman Desktop:**
 - OS: Windows 10 1803,
 - Keyman version: 12

**Comment by darcywong00** [comment] 2019-10-25 04:46
Also see #1843

**Comment by mcdurdin** [comment] 2019-10-25 04:48
Thank you for this report. Will close as it is a duplicate of #1843.

**Closed by mcdurdin** 2019-10-25 04:48 UTC
Labels: bug
