### ISSUE TITLE
bug(windows): OSK shown on Lock Screen

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#6766] opened 2022-06-14 03:00 UTC
**Describe the bug**

In Windows, enable Keyman OSK and then lock the machine to see it still shown.

![image](https://user-images.githubusercontent.com/28331388/173484098-7d401aa6-b91e-41b1-8fcc-4999c98b5615.png)

**Expected behavior**

The OSK should not be shown win the Lock Screen even it has been enabled and left so prior to time when the Lock Screen is enable.

---

**Keyman for Windows/macOS/Linux:**
 - OS: Windows 10 Pro 21H2 x64
 - Keyman version: 15.0.258-beta
 - Target Application: Windows' Lock Screen

**Comment by mcdurdin** [comment] 2022-11-20 20:30
Duplicate of #4055

**Closed by mcdurdin** 2022-11-20 20:30 UTC
Labels: bug, duplicate, windows/
