### ISSUE TITLE
[Web] Accepting first suggestion on blank text then the next suggestion replaces the first: Accept "the", then "there".

### ISSUE THREAD

**Issue by rfaramir** [keymanapp/keyman#1945] opened 2019-08-08 03:29 UTC
Accepting first suggestion on blank text then the next suggestion replaces the first: Accept "the", then "there".

**To Reproduce**
1. Clear the text
2. Click on the 'the' suggestion
3. Click on the 'there' suggestion

**Expected behavior**
'there' should append after the 'the '

**Screenshots**
after clicking 'the':
<img width="358" alt="Screen Shot 2019-08-07 at 10 26 43 PM" src="https://user-images.githubusercontent.com/45110266/62673049-7dcc8600-b962-11e9-9042-508d1542e2c0.png">
after clicking 'there':
<img width="344" alt="Screen Shot 2019-08-07 at 10 28 48 PM" src="https://user-images.githubusercontent.com/45110266/62673114-cab05c80-b962-11e9-91ca-62f8a10a74c6.png">

---
 - Device: iPhone 7
 - OS: iOS version = 12.3.1
 - Keyman version 12.0 beta (very first)
 - Target application: Keyman

**Comment by jahorton** [comment] 2019-08-09 06:23
We're going to need more details on a repro - I'm not getting the error.  Also, there's no "there" suggestion that appears; what is being done to facilitate the suggestion?

**Comment by jahorton** [comment] 2019-08-26 04:12
We haven't seen this in testing for reproduction since the initial pre-beta test; we'll assume this has been fixed by more recent work.

**Comment by mcdurdin** [comment] 2019-08-26 04:20
Got a repro for you on 12.0.11 iOS:

1. Clear text
2. Type [h][a], select `"ha"` option
3. Backspace 3 times, see `"ha"` given as an option again.
4. Select `"ha"` again, no space is emitted, and then `have`, `has`, and `had` are offered.

**Comment by jahorton** [comment] 2019-08-29 02:02
I can reproduce this from the KMW predictive text bootstrapping page - it's a KMW thing, not an iOS thing.  It'll probably show up in Android too, as a result.

**Closed** 2019-09-03 02:19 UTC
Labels: bug, web
