### ISSUE TITLE
bug(windows): Keyboard Layouts under Hotkeys tab not sync with the keyboard menu immediately 

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4294] opened 2021-01-19 07:22 UTC
**Describe the bug**

After installing several keyboards using .kmp files saved on PC, the keyboard menu on the taskbar and Configuration was populated. The Keyboard Layouts under Hotkeys tab, however, does not sync with the list of installed keyboards. See the screenshot below.

![image](https://user-images.githubusercontent.com/28331388/104999669-d365f700-5a5f-11eb-8766-8ff847a710ed.png)

**To Reproduce**

1. Install the latest beta version of Keyman at this point
2. Have the Configuration open and stay on Keyboard Layouts tab
3. Install these keyboards: [several keyboards for testing.zip](https://github.com/keymanapp/keyman/files/5834229/several.keyboards.for.testing.zip)
4. Confirm both the installed keyboards are populated in the Keyboard Layouts tab and the Keyboard Menu on the taskbar
5. Click on the Hotkeys tab and see error as shown in the screenshot above.

**Expected behavior**

The list of keyboards in the Keyboard Layouts under Hotkeys tab should be the same as those on the Keyboard Layouts tab and Keyboard Menu on the taskbar.

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 14.0.224-beta
 - Target Application: self

**Comment by mcdurdin** [comment] 2021-01-31 23:51
This has the same root cause as #4333; closing in favour of that issue.

**Closed by mcdurdin** 2021-01-31 23:51 UTC
Labels: bug, windows/, windows/config/
