### ISSUE TITLE
bug(windows): unexpected behavior when typing in Excel

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#5461] opened 2021-07-15 02:28 UTC
**Describe the bug**

It seems a consonant-vowel cluster gets replaced by the next cluster being typed when using a Sanskrit keyboard to type <kbd>k</kbd><kbd>a</kbd><kbd>k</kbd><kbd>h</kbd><kbd>a</kbd><kbd>g</kbd><kbd>a</kbd> in MS Excel.

1. in Notepad, the output is कखग (expected)
2. in Calc of LibreOffice v7.0.5.2, कखग (expected)
3. in Excel of MS Office Pro Plus 2016 v2106, the output is ग (unexpected)

**Expected behavior**

कखग - expected and correct output of the above keystrokes.

The recently typed cluster should not replace the one preceding it.

---

**Keyman for Windows:**
 - OS: Windows 10 Pro 21H1 x64
 - Keyman version: 14.0.277
 - Target Application: Notepad, MS Excel, LO Calc

---

**Keyboard**
 - https://keyman.com/keyboards/itrans_devanagari_sanskrit_vedic?bcp47=sa-deva
 - https://keyman.com/keyboards/heidelberginputsolution?bcp47=sa

**Additional context**

cf. https://community.software.sil.org/t/sanskrit-veda-devanagiri-keyboard

**Comment by mcdurdin** [comment] 2021-07-15 02:44
Duplicate of #944.

**Closed by mcdurdin** 2021-07-15 02:44 UTC
Labels: bug, duplicate, windows/

**Comment by MakaraSok** [comment] 2021-07-15 03:33
> Duplicate of #944.

Ah, I found this when searching for the existing issue, but didn't look into the detail. Gotta dive into the details next time. Thank you, Marc!
