### ISSUE TITLE
bug(windows) Font not get installed with .KMP or did it?

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#3912] opened 2020-11-20 11:12 UTC
**Describe the bug**
I was trying to test out whether the new keyboard package installed the keyboard together with the fonts included in the .KMP.

1. The existing `KmhmuOT 2.002` and `KmhmuMX 1.003` were deleted manually from the Fonts folder.
2. The existing Kmhmu (SIL) keyboard (v1.5) were removed using the Keyman Configuration.
3. Restarted Windows.
4. Installed Kmhmu (SIL) keyboard (v1.6) given in the attachment of this report here ([diagReportAndKMP.zip](https://github.com/keymanapp/keyman/files/5573043/diagReportAndKMP.zip)).
5. Once completed, the keyboard is shown in the keyboard list, but the fonts were not found in the Fonts folder (see the screenshot).
![image](https://user-images.githubusercontent.com/28331388/99792471-b5604100-2b59-11eb-871a-acdf1b74bbee.png)

![image](https://user-images.githubusercontent.com/28331388/99792678-03754480-2b5a-11eb-8ee6-9a046e5a8194.png)

The fonts however seen in the font list of the MS Office Word drop-down menu and the Fonts Setting under Windows' Settings:
![image](https://user-images.githubusercontent.com/28331388/99793166-d07f8080-2b5a-11eb-8839-e34ee6aa2d97.png)

![image](https://user-images.githubusercontent.com/28331388/99793878-e2155800-2b5b-11eb-9b96-9db9c881e948.png)

**Expected behavior**
The fonts should have been installed together with the KMP and seen in the Fonts folder.

---

**Keyman Desktop:**
 - OS: Windows 10 Pro 1909
 - Keyman version: 13.0.115
 - Target Application: [self]
   
---
 
**Keyboard**
 - Keyboard name: Kmhmu (SIL)
 - Keyboard version: 1.6
 - Language name: Kmhmu

**Additional Context**
The diag report is included in the ZIP folder in the repo steps above.

**Comment by mcdurdin** [comment] 2020-12-20 22:25
I can't reproduce this here -- are you sure the Fonts folder didn't just need a refresh?

**Comment by MakaraSok** [comment] 2020-12-21 02:20
Tested this again with Keyman 14.0.214-beta. Fonts included in the package do get installed together with the keyboard.

**Comment by mcdurdin** [comment] 2020-12-21 02:51
Okay, closing 😁

**Closed by mcdurdin** 2020-12-21 02:51 UTC
Labels: bug, windows/, windows/config/
