### ISSUE TITLE
[Keyman Developer] Occurs when open debugger in local browser and press F5 twice

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#462] opened 2017-12-01 03:04 UTC
![image](https://user-images.githubusercontent.com/28331388/33465978-855b6662-d67d-11e7-9148-441f34e0e3c8.png)

On Google Chrome (Version 62.0.3202.94 (Official Build) (64-bit)), when open debugger in local browser and press F12 and F5, the keyboard works as expected; but when F5 is pressed again, the 'Installing keyboard ???' occurs when one clicks in the text box area.

**Comment by mcdurdin** [comment] 2017-12-21 07:05
Duplicate of #477

**Closed by mcdurdin** 2017-12-21 07:05 UTC
