### ISSUE TITLE
Support for double-tapping shift would be helpful

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#163] opened 2017-08-16 08:38 UTC
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Sunday May 28, 2017 at 02:00 GMT_
_Originally opened as https://github.com/sillsdev/keyman/issues/16_

----

Double-tap of shift would be equivalent of a layer lock. Otherwise, input would return to the default layer after the next keystroke. This may have state implications so we need to think through the model before implementation.

**Comment by jahorton** [comment] 2017-10-18 07:59
The numbering is off due to issue migration, but this is a duplicate of #246, which is better fleshed out.

**Closed by jahorton** 2017-10-18 07:59 UTC
Labels: android

**Comment by mcdurdin** [comment] 2020-09-25 05:13
See also #3620.
