### ISSUE TITLE
[ios] keyman in iOS sometimes stays blank or non-responsive

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#2259] opened 2019-10-29 04:12 UTC
**Describe the bug**
sometimes keyman keyboard doesn't load it remains blank.

**To Reproduce**
I have not found exact method to reproduce. But, you keep changing the keyboards and switching between apps, you will encounter the problem.

I have attached the screenshot.

**Screenshots**
![IMG_2959](https://user-images.githubusercontent.com/14062593/67738765-e1a0a100-f9dd-11e9-84e7-c4afe01fb889.PNG)

  
**iPhone/iPad/Android (please complete the following information):**
 - iPhone 11 pro mac
 - OS: iOS 13.1.2 and iOS 13.2
 - Keyman version 12.0.53
 - Target application: Notes, mail, ...

**Keyboard**
 - Keyboard name: SIL EUROLATIN
 - Keyboard version: 1.8.1
 - Language name: English

**Comment by mcdurdin** [comment] 2019-10-29 04:35
The attached screenshot doesn't show Keyman?

**Comment by MayuraVerma** [comment] 2019-10-29 04:53
Wrong photo was attached, I updated it.
Blank keyboard is very frequently happening. But I am not able to understand the exact sequence to reproduce it.

**Comment by mcdurdin** [comment] 2019-10-29 04:54
@jahorton please triage and validate

**Comment by MayuraVerma** [comment] 2019-10-29 05:27
Video demonstrating the blank keyboard issue.
https://drive.google.com/open?id=1nJnC1reE5WsDfgfCqku9AN_lkeHM8dh1

Also, please notice the keys doesn't load with the keyboard. There is a lag. This should also be resolved and I think its related to the issue.

**Comment by jahorton** [comment] 2019-11-07 03:04
Unfortunately, that lag is very expected due to the app's current architecture - there's some significant sequential loading involved, which we hope to address (reduce) in future versions.  It will be a lot of work to address, though, so the "lag" aspect is work for after version 13.

That said, it's odd that it sometimes loads much slower than usual, and staying permanently blank is an issue worth investigating before then.  There's a chance that whatever's causing the increased lag is related.  Part of the problem is that it's extremely difficult to debug the keyboard's startup when hosted within other apps... partly because attempting to directly debug adds its own lag.

**Comment by mcdurdin** [comment] 2020-02-07 22:08
We believe this is fixed in latest beta 13.0.65.

**Closed by mcdurdin** 2020-02-07 22:08 UTC
Labels: bug, ios
