### ISSUE TITLE
feat(Android/iOS): a toggle setting to show and unshow underlying characters on the OSK on mobile

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#6921] opened 2022-07-11 02:22 UTC
**Is your feature request related to a problem? Please describe.**

> Does Keyman support one language/keyboard pack having multiple layouts like that? Because I think ideally the yiddish_pasekh keyboard would install both overlays and let the user pick which one they like.

Original post: https://community.software.sil.org/t/yiddish-keyboard-on-android/6416/5.

**Describe the solution you'd like**

We currently have an option to show and unshow underlying characters within Keyman Developer, but that's not something a user can easily toggle to suit their preferences. From within Keyman for Android/iOS Settings, can we have a menu for one to toggle this?

**Comment by mcdurdin** [comment] 2022-07-12 05:38
Duplicate of #4894.

**Closed by mcdurdin** 2022-07-12 05:38 UTC
Labels: duplicate, android/, ios/, feat, android/app/, ios/app/
