### ISSUE TITLE
bug(Windows): Share keyboard issue with a package of more than one keyboard

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#9458] opened 2023-08-14 04:02 UTC
### Describe the bug

`Galaxy Greek/Hebrew (Mnemonic) Keyboard Package` contains two keyboards and when trying to share the package, there is an issue with the QR codes. The first keyboard shows two QR codes, one on top of another; and the second keyboard does not show any QR code when clicking on the `Share keyboard` button. Please see the screen recording below.

https://github.com/keymanapp/keyman/assets/28331388/e797aa28-de8f-42ee-9921-2c3e4432e972

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [X] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0.141

### Operating system

Windows 11 Pro Version 21H2

### Device

VM

### Target application

Keyman for Windows

### Keyboard name

Galaxy Greek/Hebrew (Mnemonic) Keyboard

### Keyboard version

3.3

### Language name

Hebrew, Greek

**Comment by rc-swag** [comment] 2023-08-16 04:46
This issue was fixed in #9002 and a duplicate of #8909.

**Closed by rc-swag** 2023-08-16 04:46 UTC
Labels: bug, windows/, windows/config/
