### ISSUE TITLE
bug(web): Randomly touching the suggestion words freezes the highlight functionality in the Suggestion bar

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#9231] opened 2023-07-10 13:16 UTC
### Describe the bug

I noticed that while randomly touching the words in the suggestion banner stuck the highlight function at one point. 

### Reproduce the bug

1. Install Keyman 17.0.136-alpha build.
2. Open Keyman In-App.
3. Close the Get Started dialog. 
4. We may notice that the suggestion words appears in the suggestion bar. 
5. Touch the suggestion words repeatedly and quickly. 

I noticed that the highlight function stuck at one word and it does not disappear. Clearing the text does not close the highlight functionality. Seems to be an issue. 

I have attached the Screenshot as well as the video file for reference. 

..Highlight function stuck 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/a8fa433e-1c33-4afd-9502-999c14c3f575">

..Highlight function stuck - video

https://github.com/keymanapp/keyman/assets/19683143/4987339c-6b50-40e9-94f9-1e3e6046f24a

### Expected behavior

Randomly touching the suggestion words should not freeze the highlight function. 

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.136-alpha

### Operating system

Android 5.0, 9.0, 12.0

### Device

API 21, 28 and 31  Android Emulator, Redmi Note 8 Pro

**Comment by jahorton** [comment] 2023-07-11 01:39
Known Web limitation - the suggestion banner isn't particularly designed for multitouch, which "rapidly and quickly" is very likely to result in.

This will nigh-certainly happen for the iOS app too.

**Comment by mcdurdin** [comment] 2023-07-13 07:06
`s/limitation/bug/` :grin:

**Comment by darcywong00** [comment] 2023-09-27 00:50
Dupe of #7158

**Closed** 2023-09-27 23:40 UTC
Labels: bug, duplicate, web/
