### ISSUE TITLE
bug(android): longpress appears to be working inconsistently with start-of-sentence

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#6113] opened 2022-01-17 01:01 UTC
Pulling this out of #5963 in order to move that PR forward.

I have not managed to reproduce this longpress issue myself

## Test start-of-sentence detection   
- **ANDROID: FAILED** Longpress not working.
  * In-app:
    - It should set the keyboard to the Shift layer at the start of a text field, after full stop (`.`), exclamation (`!`) or question mark (`?`) and one or spaces (e.g. `. `).

      > OK, but the longpress keys are not working. The subkeys are not popped up.

     https://user-images.githubusercontent.com/28331388/146702344-0caad2d4-fe8f-4245-87f7-e9c7c5ca792e.mov

    - It should keep the keyboard in the numeric layer after typing a digit, but move back to base layer for all other symbols.

      > Working as expected. Note also that the longpress keys on this layer are not working. Subkeys don't pop up!

  * As a system keyboard:
    - It should set the keyboard to the Shift layer at the start of a text field, after full stop (`.`), exclamation (`!`) or question mark (`?`) and one or spaces (e.g. `. `).

      > The same behavior as in-app. The long press doesn't work either.

     https://user-images.githubusercontent.com/28331388/146702743-f3aed9ab-662a-4d40-ad8d-a32dbcad2217.mov

_Originally posted by @MakaraSok in https://github.com/keymanapp/keyman/issues/5963#issuecomment-997539315_

**Comment by darcywong00** [comment] 2022-03-15 04:08
Is this possibly a dupe of #5301?

**Comment by mcdurdin** [comment] 2022-03-15 04:12
Possibly, yes?

**Comment by darcywong00** [comment] 2022-03-15 04:23
I tried to repro the issue from the video. If I slightly move the mouse on "." before the longpress appears, the longpress will never appear. A solid longpress does generate the longpress keys

![longpress](https://user-images.githubusercontent.com/7358010/158306065-5a85afef-f0d3-4753-b992-d1b4b42e9580.png)

@MakaraSok can you repro either issue?

**Comment by darcywong00** [comment] 2022-03-28 02:08
Dupe of #5301 which is fixed by #6038

**Closed** 2022-03-28 02:17 UTC
Labels: bug, android/
