### ISSUE TITLE
bug(iOS): Using Physical Keyboard in iPhone Simulator always showing English Characters in the Text pane

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#7146] opened 2022-08-29 15:05 UTC
**Describe the bug**
Here, I noticed that If I use some other keyboards which are non-roman scripts, the text pane always shows English fonts instead of the corresponding non-roman characters. 

**To Reproduce**
1. Install Keyman 16.0.52 alpha build. 
2. Open Keyman In-app. 
3. Add one more language (eg., Khmer Angkor) using Settings. 
4. Open 'English - EuroLatin(SIL)' Keyboard. 
5. Type some texts using your Physical Keyboard. 
6. Click the globe key. 
7. Change the language into 'Khmer Angkor' .
8. Verify that the Keyboard has been changed into 'Khmer Angkor'
9. Type some texts using your Physical Keyboard. 
10. Here, I noticed that the texts appears in English instead of Khmer language. 

**Expected behavior**
Khmer font should appear when I type using the Physical keyboard. 

**Screenshots**

<img width="300" src="https://user-images.githubusercontent.com/19683143/187231953-de4f0ece-a53a-44ec-a4e3-eb708ee824c4.png">

**Keyman for iPhone/iPad:**
   Device:             iPhone 12 Pro Max Simulaltor, Physical Keyboard
 - OS:                 iOS 15.0 
 - Keyman version:    16.0.52-alpha 
 - Target Application: Keyman In-App

---

**Keyboard**
 - Keyboard name:    Khmer Angkor
 - Keyboard version: 1.3
 - Language name:    Khmer

**Additional context**
It is working fine If I am using the Touch Keyboard.

**Comment by mcdurdin** [comment] 2022-08-29 19:37
Thanks for the report. At present, iOS does not support mapping the hardware keyboard when we are using Keyman as a system keyboard. However, it would be possible to do this for the in-app keyboard, and I'd like to see that at some point.

I will go ahead and close this as a duplicate of #6768 😄.

**Closed by mcdurdin** 2022-08-29 19:37 UTC
Labels: bug
