### ISSUE TITLE
bug(ios): blank system keyboard on ios/ipados 17.2

### ISSUE THREAD

**Issue by DJ975** [keymanapp/keyman#10278] opened 2023-12-18 19:19 UTC
### Describe the bug

On ios/ipados 17.2, Keyman only behaves normally within the app. As a keyboard in other apps it shows up as blank.

### Keyman apps

- [ ] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0.144

### Operating system

iOS 17.2, iPadOS 17.2

### Device

iPhone 13 Pro, iPad Pro

### Target application

Notes

### Keyboard name

sil_euro_latin

### Keyboard version

2.0.4

### Language name

English

**Comment by jahorton** [comment] 2023-12-19 02:15
Do you have "Allow Full Access" enabled?  Please see #8566.

**Comment by darcywong00** [comment] 2023-12-19 06:39
The Keyman help documentation for allowing full access is here

https://help.keyman.com/knowledge-base/109

**Comment by sgschantz** [comment] 2024-01-08 06:08
Closing, without further information, assuming that this is due to disabling 'Allow Full Access': duplicate of #8566

**Closed by sgschantz** 2024-01-08 06:08 UTC
Labels: bug, ios/
