### ISSUE TITLE
bug(common): a trailing space should be removed when a punctuation is added

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#10834] opened 2024-02-26 03:19 UTC
### Describe the bug

A space got added when a word is picked from the suggestion banner. That is not the issue.

What troubles me is that when a punctuation is used the space does not get away.

Try and type "Ple" and then pick "Please" from the banner. Now press `.` to see the issue as shown below.
![image](https://github.com/keymanapp/keyman/assets/28331388/7fd621db-54f5-4aaf-abd9-619a7c2e9371)

### Expected behavior

It may be helpful to remove the space when a punctuation is pressed/added. The space can be both visible and invisible and they have to be removed.

### Keyman apps

- [X] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.275-beta

### Operating system

Android 10

### Device

Samsung Galaxy S9+

### Target application

Keyman

### Keyboard name

EuroLatin (SIL)

### Keyboard version

2.0.4

### Language name

English

**Comment by MakaraSok** [comment] 2024-02-26 03:21
https://github.com/keymanapp/keyman/issues/7163

**Comment by mcdurdin** [comment] 2024-02-26 03:22
Duplicate of #7163

**Closed by mcdurdin** 2024-02-26 03:22 UTC
Labels: bug, common/
