### ISSUE TITLE
bug(android): Flick Preview is not available for special characters in Android Tablet emulator

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#11167] opened 2024-04-04 10:55 UTC
### Describe the bug

I noticed that the flick preview was not available for special characters in Android Tablet and iPad Simulators. 

### Reproduce the bug

1. Install Keyman 17.0.300-beta.
2. Open the Keyman In-app.
3. Press the D key and then drag it straight downward.
4. Verify the special character "<"appears on the preview. 

I noticed that there is no preview when flicking to view the special characters. Seems to be a cosmetic issue. 

Note: It is reproducible only on Android tablets and iPad Simulators. 

I have attached the Screenshot for reference. 

..in Android Mobile emulator

<img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/40374998-6e81-400a-aa07-1d91104495a2">

..in Android Tablet emulator

<img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/72f19eea-267b-4d4e-892b-cd75bc14cf0a">

### Expected behavior

A flick preview should be available after pressing and then dragging a letter key to show the special characters.

### Keyman apps

- [X] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.300-1

### Operating system

Android 12, 13, iOS 17.4

### Device

Pixel Tablet API 30 emulator, iPad (9th generation) Simulator

**Comment by darcywong00** [comment] 2024-04-05 02:26
I could repro the issue in an Android tablet emulator (generic Android tablet) with 17.0.301 beta.
Sentry issue https://keyman.sentry.io/issues/5143688284/?project=5983524


The flick preview does appear for the web unminified test page (I edited to use sil_euro_latin.js keyboard).
![web unminified flick](https://github.com/keymanapp/keyman/assets/7358010/d65241c2-7c0b-4f36-97ba-161351e9c937)

**Comment by darcywong00** [comment] 2024-04-05 02:27
@bharanidharanj noted
> Note: It is reproducible only on Android tablets and iPad Simulators.

so assigning to @jahorton

**Comment by mcdurdin** [comment] 2024-04-05 02:35
Noting that we don't show key previews on tablets, so that may be related?

**Comment by jahorton** [comment] 2024-04-05 03:16
Exactly.  Look at the key-cap - that _is_ the preview.

For the tablet screenshot above, the D key is showing a `<`:

<img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/72f19eea-267b-4d4e-892b-cd75bc14cf0a">

When you release the key, it goes back to D, right?  It's temporarily there.

Tablet key-previews use the _actual key_ as the preview area.  Phone keys are too small for this, which is why they have key-tip style previews.

**Comment by jahorton** [comment] 2024-04-05 03:18
@bharanidharanj 

Can you verify that dragging down on the 'D' key as with your screenshot shows the flick-dragging animation _on the D key_?  If so, that's the currently-intended behavior.

I suppose there _is_ room for discussion on whether or not that should _stay_ as the intended behavior, if we want to take things that direction.

**Comment by darcywong00** [comment] 2024-04-05 06:47
Assuming we're not adding a UX change on tablet key previews this late in Beta.

I wonder we still don't want the Sentry crashes popping up (see above)

**Closed** 2024-04-05 07:32 UTC
Labels: bug, android/
