### ISSUE TITLE
bug(linux): After clicking the "Download Keyboard" button in the configuration window, a warning message is displayed in the terminal

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#9805] opened 2023-10-19 10:40 UTC
### Describe the bug

I observed that upon clicking the "Download Keyboard" button within the Keyman configuration window, a warning message is generated in the terminal.

### Reproduce the bug

1. Install Keyman 17.0.194-alpha build.
2. Open the Terminal window. 
3. Run the 'km-config' command.
4. In the Keyman Configuration dialog, Click the 'Download keyboard' button.

Here, I noticed that a warning message promptly appeared on the screen. 

Note: It is reproducible only with the following Linux Versions. 
1. Ubuntu 22.04 Jammy Linux OS
2. Ubuntu 23.04 Lunar Linux OS
3. Ubuntu 23.10 Mantic Linux OS

I have attached the Screenshot for reference. 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/1300d49c-5b59-4d20-8c80-8b08749fe868">

### Expected behavior

Clicking the "Download Keyboard" button in the Configuration window should not result in any warning messages.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [X] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.193-alpha

### Operating system

Ubuntu 22.04 Jammy, Ubuntu 23.04 Lunar Linux OS, Ubuntu 23.10 Mantic OS

**Comment by ermshiperete** [comment] 2023-10-25 13:17
This is basically a duplicate of #9411.

**Closed by ermshiperete** 2023-10-25 13:17 UTC
Labels: bug, linux/
