### ISSUE TITLE
bug(iOS): Get Started menu frequently appears on Screen after the Keyboard Swapping in iOS 12.4 / iPhone 8 Simulator 

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#6778] opened 2022-06-15 14:23 UTC
**Description**
The Get Started menu appears on the screen whenever the Keyboard swapping happens.

**To Reproduce**
1. Install the latest Keyman alpha build. 
2.  Open the Keyman In-app. 
3. Add one or more Keyboards using Settings option.
4. In the Keyboard view, Type some words using the OSK. 
5. Click the globe key. 
6. Change the Keyboard. 
7. We may notice that the Get Started menu appears on the Screen. 
8. Repeat Step 5 and Step 5. 

Here, the Get Started menu appears whenever the keyboard changes. Seems to be an issue. 

**Expected behavior**
The Get Started menu should not appear after the Keyboard changes - only once, when the app first starts.

**Screenshots**
<img width="300" src="https://user-images.githubusercontent.com/19683143/173852168-656c21c5-2772-413f-93de-e71351889e0c.png"> 

---

**Keyman for iPhone**
 - Device: iPhone 8 Simulator
 - OS: iOS 12.4
 - Keyman version 16.0.12-alpha
 - Target application: Keyman In-app

**Additional context**
I am not seeing this problem while using iOS 15.5 /  iPhone 13 Pro Simulator.

**Comment by sgschantz** [comment] 2022-10-24 03:42
@bharanidharanj Can this be reproduced in any later versions of iOS or on any other simulators besides the iPhone 8? (I'm installing the iOS 12.4 simulator, but this bug is less significant if this is the only combination to reproduce it.)

**Comment by sgschantz** [comment] 2022-10-24 07:52
@bharanidharanj I followed the above steps, but I have not been able to reproduce on the simulator with iOS 12.5 and iPhone 8

**Comment by mcdurdin** [comment] 2022-10-24 18:55
@sgschantz, @bharanidharanj, how are you dismissing the "Get Started" screen? I wonder if there is some difference there?

**Comment by sgschantz** [comment] 2022-10-25 02:01
@jahorton, when Get Started first appears, I tap on 'Add a Keyboard for your language' and add a keyboard. I can then type with different keyboards and switch between the repeatedly without seeing Get Started again.

I also did a clean install and tried to first tap Done and then going through the menus to install a keyboard. That works fine also.

I never enable 'Don't show again'. How is that switch supposed to work? I'm guessing it causes Get Started not to be shown when the user only uses the default keyboard and installs nothing else.

**Comment by jahorton** [comment] 2022-10-25 02:38
> How is that switch supposed to work? I'm guessing it causes Get Started not to be shown when the user only uses the default keyboard and installs nothing else.

https://github.com/keymanapp/keyman/blob/5321538d1d9785531e9a55c5484ad28732f832b4/ios/keyman/Keyman/Keyman/Classes/MainViewController/MainViewController.swift#L974-L1006

**Comment by sgschantz** [comment] 2022-10-27 06:39
Closing, unable to reproduce.

**Closed by sgschantz** 2022-10-27 06:39 UTC
Labels: bug, ios/
