### ISSUE TITLE
bug(common/lmlayer): Suggestion text broken

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#3616] opened 2020-09-24 16:18 UTC
**Describe the bug**
For Kannada text: When suggestion text is selected, keyman paste the entire stream of text before

**To Reproduce**
This was know bug resolved earlier. It has comeback again. I will try to find the old report

**iPhone/iPad/Android:**
 - Device: iPhone 11 Pro Max
 - OS: iOS 14
 - Keyman version 14.0.147
 - Target application: both Notes, Keyman

**Comment by mcdurdin** [comment] 2020-09-25 00:18
Thank you for this report. @jahorton has been doing a lot of work on suggestions, so this regression will hopefully be resolved shortly as a part of that effort.

**Comment by jahorton** [comment] 2021-01-14 05:45
My initial attempts to reproduce the bug on our current 14.0 beta version (14.0.221) aren't succeeding.  Is this something you are still experiencing?  If so, could you precisely describe one example where this occurred?

Something like:

1. I typed in the text "the quick brown fox jumped the lazy dog"
2. I deleted the word "dog" by backspacing.
3. I then typed "antel"
2. I then selected the 'angels' suggestion
3. A screenshot of the result, or the exact text that results from selecting it.

**Comment by MayuraVerma** [comment] 2021-01-14 07:39
Hello Joshua,

I have sent a PM in the forum. Please check

**Comment by jahorton** [comment] 2021-02-02 08:05
There's a chance that #4401 may address this.  I wasn't able to reproduce the exact effect you reported, but I did see related errors with backspacing that it will fix.

**Comment by jahorton** [comment] 2021-02-02 08:15
I don't see the exact bug you mentioned above in the video you sent with that PM.  The closest thing I see to this:

> **Describe the bug**
> For Kannada text: When suggestion text is selected, keyman paste the entire stream of text before

was for the second word, which just happens to closely resemble the first word.  Or did I miss something?  (Let me know if there's a timestamp I should examine!)

Later in that video, starting at the timestamp `00:38` through to the end, I saw that sometimes suggestions didn't display when they should have, which is likely related to a BKSP bug being addressed by #4401.

**Comment by MayuraVerma** [comment] 2021-02-12 05:40
Keyman 14.0.241 on iOS solved this issue completed. Now, Keyman updates the suggestion if we backspace the text.
However, there is still a bug.
Scenerio 1:
'kitchen s'
above text in the context
if delete 's' and ' ' (space)
suggestion updates to "kitchen" and kitchens
if you choose kitchens from the suggestion, it will be added to the text not replacing existing kitchen
so the end result is
'kitchen kitchens'
not as expected by users
'kitchens'

Scenario 2:
'kitchen s'
above text in the context
if delete 's', ' ' (space) and 'n'
suggestion updates to "kitchen" and kitchens
if you choose kitchens from the suggestion, keyman is replacing 'kitche' with 'kitchens'
so the end result is
'kitchens' as expected

The issue is, unless we delete a character from the existing word, keyman will not replace the word, instead add the suggestion to the context. This is wrong.

**Comment by jahorton** [comment] 2021-02-26 08:30
Some enhancements to predictive text have just been merged.  You may need to wait a day or two for them to be released in the next beta version, but I believe that they also fix that last issue you mentioned.

**Comment by jahorton** [comment] 2021-03-03 06:43
... looks like scenario 1 still occurs.  Can't close this quite yet, unfortunately.

**Closed** 2021-03-04 08:57 UTC
Labels: bug, common/, common/core/, common/core/web/, common/models/
