### ISSUE TITLE
[Mac] base character repeated when adding a diacritic

### ISSUE THREAD

**Issue by rik-shaw** [keymanapp/keyman#674] opened 2018-03-16 13:01 UTC
I was helping a user here in Ethiopia a few days ago get Keyman Beta 1.2.2 on macOS 10.13 "High Sierra".

All went well except that when using Keyman the "surrounding text" is not deleting (this was in both MS Word 2011 for Mac and LibreOffice 5.4).  So for example when wanting ǵ when using the SIL EL Ethiopian Latin keyboard, by typing g and then 1 the result is gǵ (the first g is not removed).

**Comment by tombogle** [comment] 2018-03-19 08:32
I find this report a bit confusing since that keyboard does not claim to be able to put an accent on a g. I tried several programs and in all cases, typing "g1" just resulted in "g1", which I think is the proper behavior for that keyboard. That said, I was able to do some testing with other key combinations, namely vowel + 1, for example: á, é, í, ó, ú (all of those were typed here using that keyboard).
I do not have Word 2011. It's entirely possible that it behaves differently, falling short of properly implementing some of the text input that macOS expects. On version 16.10 it seems to behave properly. I also tested it using Word online. I was not able to observe the reported problem there either. (Note: Word on-line does have some compatibility problems. It works to some extent in Safari and Chrome, but the best option is to use Firefox.)
Likewise, using the latest version of LibreOffice Vanilla (6.0.2.1), the keyboard seemed to work correctly as well.
I‘m suspicious that perhaps you are using a different version of the keyboard itself, which may be flawed and outdated. I tested using version 1.2.2, which is the current version, released in 2017. If you have an older version, please update and try again.

**Comment by rik-shaw** [comment] 2018-03-19 09:30
@tombogle thanks for the reply.  Sorry I should clean up the original report: g1 is an "upcoming" feature of the Ethiopian Latin keyboard (I am the developer of it), and you should see it for 1.3.1 (I have submitted a pull request for it).  So it isn't a good example but others that you note behaved the same way (the initial letter was "duplicated" instead of being "replaced").  I will have the user check more thoroughly on other applications to see if we can note where surrounding text is and isn't working and report back.  One possibility is that it works with composed characters but not with decomposed (the ones you mention are all composed).

**Comment by tombogle** [comment] 2018-03-20 09:10
Could it possibly be that you‘ve broken something in your updated keyboard implementation?
Here are some non-composed characters typed in directly here:
Ʌ́ʌ̂A̱B́c̕C̕a̱Ɛ́ɨ̌
Here are some from LibreOffice:
àâǎa̋ȁāa̱ä
ÁÀÂǍA̋ȀĀA̱
It also seems to work using Word on-line (Microsoft live), but I do see problems in my installed version of Word (just upgraded to 16.11.1). Most of the above characters do work, but none of the ʌ or Ʌ characters are able to accept the diacritics. It‘s not just a rendering/font problem, because I‘m able to paste them in just fine. It does _not_ duplicate the characters, however. It just fails to add the diacritic marks.

The Notes application in Mac seems to be very well behaved when working with input methods, so that is a good application to test in. If it doesn‘t work there, then it is almost certainly is a bug in Keyman or in the keyboard itself.

**Comment by rik-shaw** [comment] 2018-03-20 09:34
@tombogle I will need to test again with the user, sorry I don‘t have access to macOS to test myself.  I‘ll report back here on what I see.  The keyboard is working fine in Linux... I will also need to test Windows to confirm any findings.

**Comment by tombogle** [comment] 2018-04-24 03:28
Were you ever able to get back with the user to test this and see what was happening? We're in beta now, so this would be a good time to try to fix this if there is a real problem.

**Comment by tombogle** [comment] 2018-05-07 02:53
Since we have not been able to reproduce this and we haven't heard any more, I'm going to go ahead and close this. Please reopen if you're able to confirm that the problem still exists.

**Closed by tombogle** 2018-05-07 02:53 UTC
Labels: bug, mac
