### ISSUE TITLE
bug(windows): Amharic keyboard not shown in the keyboard menu of the Windows taskbar

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4207] opened 2020-12-23 03:10 UTC
**Describe the bug**

Install gff_amharic keyboard to see the error from the Keyman icon on the Windows taskbar. For some reason, the keyboard is nowhere to be found on the keyboard menu.

![image](https://user-images.githubusercontent.com/28331388/102953670-6dd82680-4504-11eb-957e-b40be7e4f9d2.png)

**To Reproduce**

1. Install 'gff_amharic'
2. Click on Keyman icon on the Windows taskbar
3. See error

**Expected behavior**

The keyboard should be shown on the keyboard menu of the Windows taskbar.

---

**Keyman for Windows/macOS/Linux:**
 - OS: Windows 10 Pro 20H2 x64
 - Keyman version: 14.0.215-beta
 - Target Application: keyboard menu on the taskbar

---

**Keyboard**
 - Keyboard name: gff_amharic
 - Keyboard version: 2.0
 - Language name: Amharic (am-ET)

**Additional context**

Note that gff_amharic cannot be found on keyman.com (see the screenshot below). @dyacob Has the keyboard been removed from keyman.com?

![image](https://user-images.githubusercontent.com/28331388/102954521-366a7980-4506-11eb-98f2-fb8e64a818a2.png)

I can still see the keyboard when install gff_amharic from the Configuration. Here is how it's shown when search for:

![image](https://user-images.githubusercontent.com/28331388/102954849-0ff90e00-4507-11eb-85f2-8c31da734698.png)

Here is the permalink to the keyboard: https://keyman.com/keyboards/gff_amharic

**Comment by mcdurdin** [comment] 2020-12-23 04:41
Can you check that you don't have too many transient languages installed in the Windows Language Settings (and expand the Amharic keyboard entry to show the list of associated languages in Keyman Configuration)?

**Comment by dyacob** [comment] 2020-12-23 12:39
This is issue https://github.com/keymanapp/keyman/issues/297 and appears for all GFF keyboard icons.  The .ico file contains a number of internal images in different sizes that are recommended for various contexts in windows (16x16, 20x20, 24x24, 32x32, 40x40, 48x48, 64x64, 256x256).

The dialog is using the wrong internal image, perhaps a default.  Please check if the APIs have an optional parameter to specify a size.

**Comment by dyacob** [comment] 2020-12-25 12:38
I just checked the website and also don't see the gff_amharic keyboard listed. Maybe something broke this week when gff_amharic_classic was introduced. I'm without a guess, all keyboard identifiers were changed to the best of my knowledge.

**Comment by mcdurdin** [comment] 2020-12-27 19:51
> I just checked the website and also don't see the gff_amharic keyboard listed. Maybe something broke this week when gff_amharic_classic was introduced. I'm without a guess, all keyboard identifiers were changed to the best of my knowledge.

Looks like you hit a bug in our keyboard search! The keyboard should not be marked as 'deprecated' as it is only 'related', but it is being marked as deprecated in the search. I'll look into that.

**Comment by mcdurdin** [comment] 2020-12-27 20:05
> This is issue #297 and appears for all GFF keyboard icons. The .ico file contains a number of internal images in different sizes that are recommended for various contexts in windows (16x16, 20x20, 24x24, 32x32, 40x40, 48x48, 64x64, 256x256).

I don't think the icon size problem is related to this issue.

**Comment by mcdurdin** [comment] 2021-01-27 04:45
@MakaraSok Can you still reproduce this problem? Please note, when you take a screenshot of Keyman Configuration, please expand the keyboard details so I can see which language is associated.

**Comment by MakaraSok** [comment] 2021-01-27 06:23
`gff_amharic` is now visible on keyman.com together its classic version `gff_amharic_classis`:
![image](https://user-images.githubusercontent.com/28331388/105951236-4bf13700-60a2-11eb-95d7-c142be17d485.png)

And the keyboard is now shown in the keyboard menu of the Windows taskbar right after it's installed. The associated language is Geez `gez-Ethi-ET`.
Here is what is shown in the Configuration:
![image](https://user-images.githubusercontent.com/28331388/105951364-7e9b2f80-60a2-11eb-9506-4a9fbf6924da.png)

Here is what is how in the keyboard menu on the taskbar:
![image](https://user-images.githubusercontent.com/28331388/105951454-9d99c180-60a2-11eb-8311-4893fd018ebf.png)

**Closed** 2021-01-27 22:07 UTC
Labels: bug, windows/, windows/config/
