### ISSUE TITLE
[iOS] Key preview is chopped off for top row of keyboard

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#2837] opened 2020-03-16 23:42 UTC
**Describe the bug**
The key preview is sometimes chopped off, looking somewhat incomplete, when on the top row of the keyboard.

**Screenshots**

Example:

![image](https://user-images.githubusercontent.com/4498365/76808465-f9b57780-683b-11ea-8927-bffc2e7f01e3.png)

What it should look like:
![image](https://user-images.githubusercontent.com/4498365/76808443-e99d9800-683b-11ea-80c8-0048a713e243.png)

---

**iPhone/iPad:**
 - Device: iPhone 7
 - OS: iOS 12.4.1 (iPhone 7)
 - Keyman version 13.0.104 (iPhone 7)
 - Target application: any (system keyboard, not tested on in-app)

**Comment by jahorton** [comment] 2020-11-18 03:28
This may have been inadvertently fixed by #2968 (Apr 25), when we were... well... forced to swap to native-Web popup keys due to a bug occurring in iOS 13.4+.  I cannot currently reproduce it.

![Nicely-bounded popup keys](https://user-images.githubusercontent.com/25213402/99479440-c148d900-2988-11eb-9801-5cb34e39a365.png)

**Closed** 2020-11-30 06:42 UTC
Labels: bug, ios/
