### ISSUE TITLE
bug(mac): no configuration or prompt allow access for Keyman on Catalina 

### ISSUE THREAD

**Issue by Meng-Heng** [keymanapp/keyman#12344] opened 2024-09-02 04:42 UTC
### Describe the bug

Topic: https://community.software.sil.org/t/keyman-isnt-working-with-macos-catalina/9096
> I have a Mac (Catalina) and I can’t get Keyman to work on my computer. I’ve installed the newest version and an older version of Keyman (16.0.13vb) as some other posts suggested and I still face the same issues.
> 
> There is no configure setting to click on after installing.
> It doesn’t show up in my input monitoring settings under the privacy setting.
> I was never promoted to allow access for Keyman during installation.
> I’ve tried manually moving Keyman into the input monitoring folder through Finder-- no changes.
> I’ve restarted my computer several times.

### Expected behavior

Show Keyman Configuration after installing Keyman for mac.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [X] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.328 & 16.0.13vb

### Operating system

macOS Catalina

**Comment by sgschantz** [comment] 2024-09-02 05:30
@Meng-Heng This appears to be a duplicate of #12295

**Closed** 2024-09-02 05:52 UTC
Labels: bug, mac/
