### ISSUE TITLE
bug(mac): Amharic keyboard ignoring context on the various places.

### ISSUE THREAD

**Issue by dinakaranr** [keymanapp/keyman#11415] opened 2024-05-10 11:55 UTC
### Describe the bug

I have seen this behaviour appears on the various place for macOS.(Termnial, LibreOffice, Google Docs, ATOM)

### Reproduce the bug

Steps to reproduce:

1. Install the latest version of Keyman 17.0.321-beta in macOS.
2. Download and install the gff_amharic keyboard using Keyman Configuration dialog.
3. Open the Chrome browser.
4. Switch to Amharic keyboard.
5. Type tt in the address bar or search box.
6. Mouse-clicking between the two ታ characters.
7. Type a.
Here, it is showing the wrong output.
Note: This same behaviour happens below mentioned areas
Chrome address bar, 
Chrome_Google_Docs,
ATOM Editor,
Safari_Google_Docs,
Terminal Window,
LibreOffice,
I have attached the Screenshots for above mentioned areas.
Chrome address bar, 
<img width=300 src="https://github.com/keymanapp/keyman/assets/19683059/45a5b134-aa1f-44ee-b615-d8ddf0d68aee">

Chrome_Google_Docs,
<img width=300 src="https://github.com/keymanapp/keyman/assets/19683059/a1633e4c-4a09-45b3-a852-f1adcb2e3095">

ATOM Editor,
<img width=300 src="https://github.com/keymanapp/keyman/assets/19683059/fed6da00-d6d1-41cd-a5e0-7ed2a83aa0ee">

Safari_Google_Docs,
<img width=300 src="https://github.com/keymanapp/keyman/assets/19683059/88577346-7f66-459a-817a-aeaf91b50714">

Terminal Window,
<img width=300 src="https://github.com/keymanapp/keyman/assets/19683059/10cc756b-743f-418d-81eb-cc1a93c60469">

LibreOffice,
<img width=300 src="https://github.com/keymanapp/keyman/assets/19683059/5506019f-5510-4e60-904d-b20178f4f457">

### Related issues

#10036

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [X] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Operating system

macOS

**Comment by sgschantz** [comment] 2024-05-13 03:09
@dinakaranr It is a not a bug for Keyman to behave this way when an application does not allow us to read the context.

After a user clicks somewhere on the screen, it is impossible for Keyman to know where the text insertion point is sitting in the text unless the application fully supports an API that reveals the location and selection length. The same is true for when the arrow keys are used.

There are several apps like this which we call non-compliant because they don't fully implement these text APIs. We must work around the non-compliant apps the best we can, but keyboards like Amharic will be limited. This is the same reason that I closed #10036.

Sometimes the non-compliance for a browser is due to a combination of the browser and the web application running in the browser, such as Google Docs or Facebook.

Looking at the apps you've listed, the only one that stands out to me is Terminal. In my testing, all apps provided by Apple have shown to be compliant. I can take a closer look at that one if you can consistently reproduce it.

**Comment by rc-swag** [comment] 2024-05-13 04:12
@sgschantz Thank you for the clarification here.  @dinakaranr  What we need to do is to make sure the test cases in Test Lodge reflect this understanding. Ideally, there shall be a test for a "compliant" app using that wording and naming a specific app to use, with the expected results. Then another test can be present for a "non-complaint" app naming a specific app we know is non-compliant, again specifying the expected results. I can help by looking at the test cases in Test Lodge I will probably consult @sgschantz  as well. I will close this Issue once I have done this, assigning the issue to myself for now.

**Comment by rc-swag** [comment] 2024-05-16 23:50
I have given two examples below of how I think the test cases should be updated one case for a compliant app and one for a non-compliant app. 
The key difference is the result for step 8 and step 12
As a side note long before you started the tests were also
on a wiki and I think in transferring to Test Lodge a "+" has been added to the steps. this is confusing because generally `+` with keystrokes indicating
pressing two keys at the same time. You have probably seen that in help menus and hotkey menus in the past. for example Ctrl+V.
I have removed the "+' from these steps. in github markdown, it is easier as we can wrap keys in <kbd>t</kbd><kbd>a</kbd> for example. For test lodge
I suggest just leaving a blank space or use a comma. So t t left-arrow a  OR t,t,left-arrow,a


Test NonCompliant App
TC128 Test case for Non-compliant LibreOffice Writer with Amharic
Setup Steps:
1. Install Keyman build.
2. Install Amharic keyboard.
3. Install LibreOffice 7.0 app.

Action Steps:
1. Click on the LibreOffice Writer icon from macOS Desktop.
2. Verify that the LibreOffice Writer Application opens.
3. Type t a
4. Verify it produces ታ
5. Type t left-arrow  a
6. Verify it produces አት
7. Type t t left-arrow a
8. Verify it produces ትአት
9. Type t t
10. Mouse-clicking between the two ታ characters.
11. Type a
12. Verify it produces ትአት
13. Verify in last three cases, the insertion point should end up before the final ት character.

Cleanup Steps:
1. Uninstall Keyman build on the device.
2. Uninstall Amharic keyboard.
3. Uninstall LibreOffice 7.0 app.

Test Compliant App
TC-125 Test case for Compliant Notes_APP with Amharic
Test steps
Setup Steps:
1. Install Keyman build.
2. Install Amharic keyboard.
3. Install Notes App.
Action Steps:
1. Click on the Notes App icon from macOS Desktop.
2. Verify that the Notes Application opens.
3. Type t a
4. Verify it produces ታ
5. Type t left-arrow  a
6. Verify it produces አት
7. Type t t left-arrow  a
8. Verify it produces ታት
9. Type t t
10. Mouse-clicking between the two ታ characters.
11. Type a
12. Verify it produces ታት
13. Verify in each of the last three cases, the insertion point should end up before the final ት character.

Cleanup Steps:
1. Uninstall Keyman build on the device.
2. Uninstall Amharic keyboard.
3. Uninstall Notes App.

@sgschantz  can you please verify I have updated these correctly.

I will leave it to you to update the other test cases. Note @sgschantz  has mentioned that for non-compliant they will all fail to read the context but the behaviour as a result can vary. 
From Slack so not lost. 

 ```
Apple Pages, Notes, Stickies (and likely almost all other Apple apps) are compliant
Non-compliant apps include Google Docs running under Chrome, Adobe apps, Atom, OpenOffice
behavior can vary somewhat among non-compliant apps, but they all fail to read the context
```

**Comment by rc-swag** [comment] 2024-05-23 02:42
@dinakaranr has updated test lodge to reflect the changes.

**Closed by rc-swag** 2024-05-23 02:42 UTC
Labels: bug, mac/
