### ISSUE TITLE
Keyman and bluetooth keyboards for mobile evices

### ISSUE THREAD

**Issue by soosistvangithub** [keymanapp/keyman#7827] opened 2022-11-27 18:19 UTC
Is it possible, that keyman can work with phisical bluetooth keyboard for mobile devices (tablets) ?

**Comment by mcdurdin** [comment] 2022-11-28 02:54
Duplicate of #6768.

On Android, Keyman fully supports Bluetooth and other external keyboards.

On iPad, we are constrained, because iPadOS/iOS do not allow keyboard extensions to remap the external keyboard. We are tracking this in #6768.

**Closed by mcdurdin** 2022-11-28 02:54 UTC
Labels: duplicate
