### ISSUE TITLE
bug(linux): Khmer Angkor Keyboard is not working in Jammy Jellyfish with Wayland 22.04 Linux OS

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#6824] opened 2022-06-22 09:45 UTC
**Describe the bug**
Reordering of Characters does not working with Jammy Jellyfish with Wayland 22.04 Linux OS

**To Reproduce**
1. Install the latest Keyman Alpha build. 
2. Download and install Khmer Angkor Keyboard. 
3. Open Libreoffice Writer. 
4. Open LibreOffice Writer, go to Tools/Options, Language Settings/Languages tab. Under "Default Languages for Documents" check the box for Complex text layout and select Khmer as language.
5. Also change the default style: go to Styles/Manage Styles, right-click on "Default Paragraph Style" and select Modify. Go to the Font tab. For CTL Font, select Family "Khmer Mondulkiri" and Language "Khmer".
6. Restart LibreOffice Writer. 
7. Open Khmer Angkor Keyboard. 
8. Type 'xEjmr' in the Document. 
9. Open Text Editor. 
10. Type 'xEjmr' in the Notepad. 

I noticed that it does not show up the expected output. (Please, see the attached Screenshot).

**Expected behavior**
Typing 'xEjmr' should show ខ្មែរ in the document page. 

**Screenshots**
<img width="300" src="https://user-images.githubusercontent.com/19683143/174998402-00d83aa8-0556-4111-8c4a-652616c86ee5.PNG"> 

---

**Keyman for Linux:**
 - OS:  Ubuntu 22.04 Jammy Jellyfish with Wayland
 - Keyman version: 16.0.15 - alpha
 - Target Application: LibreOffice Writer 

---

**Keyboard**
 - Keyboard name:  khmer_angkor 
 - Keyboard version: 1.0.1 
 - Language name:  Khmer

**Additional context**
1. I am not seeing this issue in Jammy Jellyfish 22.04 with Xorg environment.

**Comment by ermshiperete** [comment] 2022-06-23 09:39
See also #4273.

**Comment by ermshiperete** [comment] 2022-09-20 16:04
Closing as duplicate of #4273.

**Closed by ermshiperete** 2022-09-20 16:05 UTC
Labels: bug, linux/
