### ISSUE TITLE
bug(ios): iOS sticky popup keys

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#10440] opened 2024-01-18 19:40 UTC
### Describe the bug

Keyboards with double tap and gestures. The preview key for double tap is slow to fly-out and close back. It almost feels like sticky keys. 

### Keyman apps

- [ ] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.246

### Operating system

iOS 17.2.1

### Device

iPhone 13 pro max

**Comment by mcdurdin** [comment] 2024-01-18 23:29
Can you provide a bit more detail on the issue? If possible, a screen capture to illustrate the problem?

**Comment by jahorton** [comment] 2024-01-19 05:40
Also, if this is within the Keyman app:  we've noticed that things get "sticky" if you restore the app from a background state, but that usually clears if you open and use the keyboard picker, even if just re-selecting the same keyboard.

If the issue still occurs after 'resetting' the keyboard in this manner, we'd certainly like to know.

**Comment by MayuraVerma** [comment] 2024-01-19 06:36
It’s in OSK.

I will upload the keyboard, screenshots and video in a day

**Comment by jahorton** [comment] 2024-01-30 05:00
> It’s in OSK.
> 
> I will upload the keyboard, screenshots and video in a day

Pinging as a reminder; it would be quite helpful to have this data and that video in order to proceed.

**Comment by jahorton** [comment] 2024-02-06 03:44
I'm closing this one as a duplicate of #10440, which has a video and more data about the same error.  The underlying engine here is the same for both Android and iOS.

**Closed by jahorton** 2024-02-06 03:44 UTC
Labels: bug, ios/

**Comment by MayuraVerma** [comment] 2024-02-06 15:09
I was travelling last week. I could not get to this. I will anyways create video.
