### ISSUE TITLE
bug(mac): Keyman menu options were missing after switching to a Keyman keyboard in macOS Big Sur

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#11180] opened 2024-04-05 08:29 UTC
### Describe the bug

The Keyman menu options were not visible in the menu after switching to a Keyman keyboard in macOS Big Sur. This issue is also reproducible in macOS Catalina.

### Reproduce the bug

1. Install Keyman 17.0.302-beta build .
2. Click the Taskbar. 
3. Switch to Keyman Keyboard. 
4. Click once again the Taskbar. 

Here, I noticed that the Keyman menu options(Configuration, On-Screen Keyboard and About options etc.,) were missing in the Keyman menu list.

5. Check the Keyman app appears in Files and Folders and Input Monitoring folders. 

I noticed that the Keyman app was in disabled stated in File and Folders and it does not appear in Input Monitoring folder. Seems to be an issue. 

Note: In macOS Sonoma, the Keyman app appears in the Input Monitoring folder. And the Keyman menu list appear while switching to Keyman Keyboard view. 

I have attached the Screenshot for reference. 

..Keyman menu options appear in macOS Sonoma

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/32abdbda-82a7-4267-96f8-145adb22bd37">

..Keyman menu options are missing in macOS Catalina and macOS Big Sur

   <img width="600" src="https://github.com/keymanapp/keyman/assets/19683143/9b4285fe-0171-457a-bb03-b12c0ce9fd6c">

### Expected behavior

The Keyman menu options should appear in the menu after switching to a Keyman Keyboard.

### Related issues

#9060

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [X] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.302-beta

### Operating system

macOS Big Sur, macOS Catalina

### Device

Virtual Machine

**Comment by sgschantz** [comment] 2024-04-12 02:40
@bharanidharanj Is this a duplicate of #10217?

And is #10217 a duplicate of #9060?

If so, all three of these issues can be combined into one issue that is occuring for both Catalina and Big Sur (which were sequential OS releases).

**Comment by mcdurdin** [comment] 2024-04-17 03:56
These three look like duplicates. Closing in favour of #9060.

**Closed by mcdurdin** 2024-04-17 03:56 UTC
Labels: bug, duplicate, mac/
