### ISSUE TITLE
bug(ios): backspacing for a long time seems to block longpress and/or leave key preview visible

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#6544] opened 2022-04-18 20:49 UTC
Note: this may be an issue in web rather than ios, but tracking here for now.

_All tests were done in-app using `15.0.235-beta-test-6535`build via TestFlight (`15.0.235 (0.6535.6145)`) on iPod touch 7th gen running `iOS 15.3.1`._

...

There is a catch though if the backspace is pressed for a while to clear the text (including white spaces), the subkeys are no longer available (nothing shown on the keys with subkeys) and the preview key stay longer than usual or won't even disappear at times.

https://user-images.githubusercontent.com/28331388/163746256-d8bb913e-0d71-4247-805a-bc3fc40d5aa8.mov

_Originally posted by @MakaraSok in https://github.com/keymanapp/keyman/issues/6494#issuecomment-1101044208_

**Comment by jahorton** [comment] 2022-04-19 02:38
Note:  should be very highly related to #6494 and its underlying issue #6489.
Very important note: was not tested on #6494's branch or on a PR that branched off after it.  This should **absolutely** be tested first.

**Comment by mcdurdin** [comment] 2022-04-19 02:43
Check with @MakaraSok. The issue was reported on testing #6494 but it looks like his notes say he was testing on a different build, which doesn't seem right.

**Comment by sgschantz** [comment] 2022-10-24 06:45
@bharanidharanj @MakaraSok: Unable to reproduce with the following configurations:

TestFlight with iOS 16.02 on iPhone 13 mini
Keyman 16.0.87

TestFlight with iOS 15.4.1 on iPhone 11 Pro
Keyman 16.0.85(0.7498.7159)

If you can reproduce with a recent build, please provide detailed instructions of exactly how to reproduce:
How many keys do I need to tap?
Can I just press and hold the delete button to reproduce?
I'm wondering if I'm missing an important step here.

**Comment by sgschantz** [comment] 2022-10-27 06:40
Closing, unable to reproduce.

**Closed by sgschantz** 2022-10-27 06:40 UTC
Labels: bug, ios/
