### ISSUE TITLE
Exception when selecting subkey of Shift

### ISSUE THREAD

**Issue by gabrielwong** [keymanapp/keyman#501] opened 2017-12-18 05:41 UTC
To reproduce:
1. Switch to the French keyboard and select the shift layer
2. Longpress shift and select one of the subkeys

The following error is thrown from `kmwosk.js` in `osk.release`.
```
Exception with thrown value: TypeError: null is not an object (evaluating 'osk.popupBaseKey.id')
```

**Comment by jahorton** [comment] 2018-02-13 01:35
We are unable to reproduce this error, and there has been recent significant work addressing highly related code.  We're marking this as fixed for now, though we are willing to re-address it if additional details can be provided to help replicate it.

**Closed by jahorton** 2018-02-13 01:35 UTC
Labels: bug, web
