### ISSUE TITLE
bug(linux): Authentication error message appears in the terminal window in Lunar Linux 23.04 (Ubuntu on Xorg)

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#8916] opened 2023-06-02 10:55 UTC
### Describe the bug

I noticed that after clicking the Install keyboard button there is an authentication error message appears in the terminal window. It happens only on Ubuntu 23.04 Lunar Linux (Ubuntu on Xorg) Version. 

### Reproduce the bug

1. Install Keyman 17.0.115-alpha build in Lunar Linux 23.04 (Ubuntu on Xorg) . 
2. Enter 'km-config' in the terminal window. 
3. We may notice that the Keyman Configuration dialog opens. 
4. Click Download Keyboard button. 

I noticed that the there is an warning message 'libEGL warning: DRI2: failed to authenticate' appears on the terminal window. 

Note: It is only reproducible in Lunar Linux 23.04 (Ubuntu on Xorg) 

I have attached the Screenshot for reference. 

..Authentication error message

   <img width="500" src="https://github.com/keymanapp/keyman/assets/19683143/7e36f643-af4f-4bd8-b82f-d8c005fc1c2b">

### Expected behavior

Authentication error message should not appear during any keyboard installation. 

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [X] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.115-alpha

### Operating system

Ubuntu 23.04 Lunar Linux (Ubuntu on Xorg)

**Comment by mcdurdin** [comment] 2023-06-04 21:17
Probably low priority if it doesn't impact functionality.

**Comment by ermshiperete** [comment] 2023-06-05 08:44
This is just a warning message from the system, so it can be ignored. But I'll check if there's anything we can do so that it doesn't show up.

**Comment by ermshiperete** [comment] 2023-06-06 16:23
@bharanidharanj Can you please reproduce this error, then open the "Downloads" dialog and while that is still open, open a second terminal window and run these commands:

```
pid=$(ps -C km-config -o pid= | sed 's/ //g') && sudo awk '/\.so/{print $6}' "/proc/$pid/maps" | \
sort -u | tee /tmp/libs.txt
```

This will create a file `/tmp/libs.txt` - please attach this to this issue.

Also run

```
pid=$(ps -C km-config -o pid= | sed 's/ //g') && sudo awk '/\.so/{print $6}' "/proc/$pid/maps" | sort -u | grep -i egl
```

and post the output.

**Comment by bharanidharanj** [comment] 2023-06-12 09:55
> @bharanidharanj Can you please reproduce this error, then open the "Downloads" dialog in km-config and while that is still open, open a second terminal window and run these commands:
> 
> ```
> pid=$(ps -C km-config -o pid= | sed 's/ //g') && sudo awk '/\.so/{print $6}' "/proc/$pid/maps" | \
> sort -u | tee /tmp/libs.txt
> ```
> 
> This will create a file `/tmp/libs.txt` - please attach this to this issue.
> 
> Also run
> 
> ```
> pid=$(ps -C km-config -o pid= | sed 's/ //g') && sudo awk '/\.so/{print $6}' "/proc/$pid/maps" | sort -u | grep -i egl
> ```
> 
> and post the output.

Sure, I will do it.

**Comment by bharanidharanj** [comment] 2023-06-12 10:18
@ermshiperete Retested with Keyman 17.0.120-alpha build in Ubuntu 23.04 Linux OS (VM) and here is my observation: 1. I was not able to reproduce this issue with the recent build. 2. However, as per your suggestion I run the above two commands in the terminal window and  attached the libs.txt file and the screenshot for your reference. 

[libs.txt](https://github.com/keymanapp/keyman/files/11721233/libs.txt)

..output
   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/ae243562-e66e-4838-a7bc-2e906d7cd0f1">

**Comment by ermshiperete** [comment] 2023-06-12 14:42
Closing this issue since I can't reproduce it and it's no longer happening for @bharanidharanj either. We can re-open if it happens again.

**Closed by ermshiperete** 2023-06-12 14:42 UTC
Labels: bug, linux/
