### ISSUE TITLE
bug(mac): The Keyman configuration menu doesn't open on Big Sur after installing the 17.0.227 build

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#10217] opened 2023-12-11 10:51 UTC
### Describe the bug

After installing Keyman 17.0.227 on macOS Big Sur, I observed that the Keyman menu did not function properly, failing to open.

### Reproduce the bug

1. Install Keyman 17.0.227-alpha build on macOS Big Sur. 
2. Open System Preferences / Security & Privacy option. 
3. Select 'Full Disk Access' option from the Security & Privacy dialog. 
4. Enable 'Install Keyman app'. 
5. Click the 'Accessibility' option. 

Here, I noticed that the 'Keyman app' option was missing in the right pane. 

6. Restart the system. 
7. Set 'Keyman' keyboard from the Task bar. 

Here, I noticed that the Keyman Configuration menu was missing. Seems to be an issue. 

Note: The Keyman Configuration menu is working fine on Keyman 17.0.190 build. 

..Keyman Configuration menu displays in Keyman 17.0.190-alpha 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/163d51b9-7334-41d1-bcd3-d4a28c5302ee">

..Keyman Configuration menu is missing in Keyman 17.0.227-alpha 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/2317d0dd-0b75-4021-ae13-8a1926ab8ee5">

### Expected behavior

The Keyman Configuration menu should appear after clicking the 'Keyman' option from the task bar. 

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [X] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.227-alpha

### Operating system

macOS Big Sur 11.0.1

**Comment by mcdurdin** [comment] 2023-12-12 06:01
Could this be related to https://community.software.sil.org/t/keyman-configuration-not-available/8185

@sgschantz any ideas?

**Comment by sgschantz** [comment] 2023-12-14 02:09
I suspect that most of these issues with the Keyman menu not being fully available are due to access to the Documents Folder not being enabled in Privacy and Security. (Even if it looks like it is enabled, it may help to toggle it off and on again.)

The experience may vary slightly depending on the version of macOS, but see related issues #9060 and #181. The reason for this is that the keyboards are currently stored in the Documents folder, and they are accessed to build the keyboards list when the menu is displayed .

Toggling access to the Documents Folder can be done in the Security & Privacy dialog as shown here:
![image](https://github.com/keymanapp/keyman/assets/89134789/b5b88832-133c-49b9-8296-d5aef40aa081)

When changing this setting, the user is given the option to restart Keyman (at least for recent versions of macOS) for the change to take effect without restarting.

It is hard to say if this is the only cause of this issue because we have never had definite steps on how to reproduce. If it is the cause, then fixing #2542 will be the ultimate fix as the Keyman keyboards should not be stored in the Documents folder.

**Comment by bharanidharanj** [comment] 2023-12-21 13:52
1. I was able to reproduce this issue with the latest Keyman 17.0.234-alpha build. 2. Followed Shawn's comment to enable the Keyman app option from Files and Folders. 3. But, this option is disabled by default in the Files and Folders view. 4. Seems to be an issue. 

..Keyman App was enabled in Full Disk Access View

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/74038343-e79f-4184-abe0-7aa70ab448d0">

..Keyman App was disabled by default in the Files and Folders View

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/5d0effbb-0a94-4ca3-b282-c428e280a3fe">

**Comment by mcdurdin** [comment] 2024-04-17 03:56
Closing in favour of #9060.

**Closed by mcdurdin** 2024-04-17 03:56 UTC
Labels: bug, duplicate, mac/
