### ISSUE TITLE
The Linux ibus cannot output correctly

### ISSUE THREAD

**Issue by bbyykk** [keymanapp/keyman#3005] opened 2020-04-18 22:39 UTC
**Describe the bug**
The ibus cannot output correctly with PhahTaigi POJ keyboard.
It would keep the last few characters of input before the output characters

**To Reproduce**
1. Install the PhahTaigi POJ keyboard with keyman for Linux
2. Click on any applications, like gnome-terminal or Google chrome to any place to input text
3. Switch to "nan" with "Super + Space"
4. Type "iunn",  the output is "iunⁿ".
     Type "iunn5", the output is "iunⁿiûⁿ" 
     Type the Backspace key and it does nothing

**Expected behavior**
Type "iunn5", the correct ouput is "iuⁿ
Type "iunn5", the correct ouput is "iûⁿ
The Backspace key should delete the key before the cursor

---
**Keyman for Linux:**
 - OS: [Ubuntu 19.10]
 - Keyman version: [13.0.103-1]
  
**Additional context**
Running in Gnome Shell but not Unity desktop

**Comment by darcywong00** [comment] 2020-04-19 04:48
On Ubuntu 18.04 I see the following behavior in the shells (terminal or Terminator)

> Type "iunn~5~", the correct output is "iuⁿ"

I consistently see the expected result.

> Type "iunn5", the correct output is "iûⁿ"

I get different output depending how "soon" I type the final `5`. Sounds like a race condition somewhere

`iiû`
`iûⁿ` 
`iui`

> Type the Backspace key and it does nothing

In all my scenarios, the backspace key is removing the final character

Note: typing in the Google Chrome omnibar tends to interfere with the keyboard processing.

**Comment by mcdurdin** [comment] 2020-04-19 20:56
@darcywong00 can you repro in 19.10?

**Comment by darcywong00** [comment] 2020-04-20 05:46
I can repro in 19.10

In the terminal:
`iunn` produces `iunⁿ`
`iunn5` produces `iunⁿiûⁿ`
Backspace deletes at the end OK
But left arrow to the middle of the context, and backspace takes a few hits to start responding

gedit behaves fine though:
`iunn` produces `iuⁿ`
`iunn5` produces `iûⁿ`
Backspace also behaves fine 

I believe this issue is a duplicate of #1489

**Closed** 2020-04-20 05:49 UTC
Labels: bug, compatibility, linux

**Comment by loulou921222** [comment] 2021-03-20 20:27
This is still the case in chrome, gnome's search, discord, and a few other apps. In gedit and libre office it's fine.

**Comment by ermshiperete** [comment] 2021-03-22 16:46
Duplicate of #1489
