### ISSUE TITLE
Keyman 10.0.138 fails to update khmer_angkor keyboard from 1.0.2 to 1.0.3

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#735] opened 2018-04-10 04:23 UTC
![Fail to update keyboard](https://user-images.githubusercontent.com/4498365/38536079-5a291b84-3cb1-11e8-83bd-db8d32f8f386.jpg)

This may have been fixed in 10.0.139 beta but I don't think so.

**Comment by mcdurdin** [comment] 2018-06-04 04:00
See also #824. Probably related.

**Comment by tombogle** [comment] 2018-06-06 14:21
Running Keyman on my physical iPad, I see Khmer in the **Add New Keyboard** list, with a right arrow giving me two options: NiDA Khmer and Khmer Angkor. I _am_ able to reproduce this error on my iPad. But when I run it in the simulator, only NiDA Khmer is returned. So when the code attempts to looks for an update for Khmer Angkor, it doesn't find it. Therefore it never makes the "Update" button visible.

**Comment by tombogle** [comment] 2018-06-06 16:17
The reason for the different results coming back from the API is that Xcode builds Keyman using a hard-coded version number in the project file: 2.5.2, and that gets used to determine which version to send to the API. Since khmer_angkor requires version 10, it doesn't get returned.

**Comment by tombogle** [comment] 2018-06-06 19:02
I _think_ I see the problem, but I'm not sure what the solution is. When we use the API to retrieve all the keyboards, it gets them all, including khmer_angkor. But the API returns a separate element for every keyboard/language pair. Then the code constructs a Dictionary of unique languages by name, which correctly contains both Khmer keyboards for "khm". Finally, it attempts to construct a Dictionary of keyboard Ids with a single keyboard object whose list of language IDs includes the full list of all languages that keyboard works with. Here, it falls down because neither of the Khmer keyboards lists any languages, and somehow the logic that builds up this Dictionary seems to exclude any keyboards for which there are no languages at all.

**Comment by tombogle** [comment] 2018-06-06 19:10
Looks like the real problem is maybe "khm" vs. "km" If I execute the code to grab the keyboard using "khm" instead of "km", that succeeds.

**Comment by tombogle** [comment] 2018-06-07 02:20
Keyman 10 should be using the new version of the API that gets BCP-47 language IDs. When we look for updates, we should ignore the language ID and only look up based on keyboard ID.

**Comment by tombogle** [comment] 2018-06-18 17:28
This was actually finished in P3S5. Just forgot to close it.

**Closed by tombogle** 2018-06-18 17:28 UTC
Labels: bug, ios
