### ISSUE TITLE
bug(android): Keyboard Stuck and Displaying Error Message While Rapidly Typing on Text Input Screen

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#10592] opened 2024-02-01 08:02 UTC
### Describe the bug

I noticed that keyboard stuck at on point and displaying error message on the screen. 

### Reproduce the bug

1. Install Keyman 17.0.257-alpha build. 
2. Open Keyman In-App.
3. Dismiss the "Get Started" dialog. 
4. Start typing rapidly with the OSK. (use the globe key and space bar during the process)

Here, I noticed that the keyboard key was stuck at one point and displayed a keyboard error message on the screen. Seems to be an issue. 

I have attached the Screenshot as well as the Video file for reference. 

..Key Stuck

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/c8a71f4d-d6b6-4f68-abdb-9b821cad90ce">

..Key stuck with a Keyboard error message

https://github.com/keymanapp/keyman/assets/19683143/56658baa-292c-48bc-9230-cacb1012428b

### Expected behavior

Keys should work smoothly without getting stuck or showing error messages when typing quickly.

### Related issues

#10286 

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.257

### Operating system

Android 13

### Device

Samsung Galaxy A23 5G Mobile

### Keyboard name

English - EuroLatin (SIL) Keyboard

### Keyboard version

2.0.4

### Language name

English

**Comment by jahorton** [comment] 2024-02-06 03:43
Is likely related to #10440 - this certainly appears to be the same underlying error, and is more informative about it.

**Comment by jahorton** [comment] 2024-02-06 03:56
> ..Key stuck with a Keyboard error message
>
> https://github.com/keymanapp/keyman/assets/19683143/56658baa-292c-48bc-9230-cacb1012428b

----

There's some odd behavior leading up to the reported error.  In sequence:

![image](https://github.com/keymanapp/keyman/assets/25213402/7880960e-bc75-495e-b17e-9ffcafc633dd)

![image](https://github.com/keymanapp/keyman/assets/25213402/25a4d667-73b1-483b-80a8-b9ec6b13be66)

It appears as if the spacebar may have stuck highlighting here, which would be in line with #10640 - the spacebar doesn't have subkeys.

![image](https://github.com/keymanapp/keyman/assets/25213402/aaf36636-5144-42d7-9272-2a02c9830f33)

Note:  no key preview ever appeared for the `M` key.  The transition from shift layer (finally) appearing to the `M` key being output makes me suspect that things _actually_ broke on the SHIFT, but that got hidden thanks to gesture-recognizer robustness ensuring that the shift layer still appeared due to the _new_ touch on the M before the M was processed.

The reported error triggers around 0:41:

![image](https://github.com/keymanapp/keyman/assets/25213402/72944094-bbef-4dec-9279-47cb86db3601)

**Comment by jahorton** [comment] 2024-02-08 07:53
I'm curious as to if #10641 mitigates and/or fixes this issue, as components of the sequence above should be fixed by that PR.  I've added a user test there for further investigation; I'll try to resume on this issue once its results are in.

**Comment by jahorton** [comment] 2024-02-13 05:35
> [...] and predictive texts intermittently [...]

Hmm.  Possible relation to #10642 and/or #10694?   It _would_ explain the error-notification.  That said, I'm not getting a sticky key-preview when doing this.

**Comment by jahorton** [comment] 2024-02-13 07:29
This does appear to reproduce fairly easily with an old SM-T350 (Galaxy Tab A) tablet.  It's older and slower, enough so that it lags during rapid typing.  Granted, I haven't gotten the error message part yet, but odd sticky behaviors are happening:

- often, multiple keys experience stuck highlighting if typing rapidly
    - if the issue is _just_ highlighting, tapping the key is enough to unstick it.
- a tablet-style key preview gets 'stuck' with some regularity
    - When the latter occurs, it only gets 'unstuck' when I switch layers and then type a key... or few.  The layer-swap does appear necessary, though.
    - Power-mashing the same key over and over can eventually trigger a key-preview stick... but this only appears to trigger after several keypresses.

**Comment by jahorton** [comment] 2024-02-14 05:30
> I'm curious as to if #10641 mitigates and/or fixes this issue, as components of the sequence above should be fixed by that PR. I've added a user test there for further investigation; I'll try to resume on this issue once its results are in.

... and it turns out that #10707 is additionally needed to fully fix the underlying issue.

#10707 does not resolve the issues noted in the prior comment, though.

**Comment by jahorton** [comment] 2024-02-14 05:47
Extra 'fun' note:  doing a key-mash on a single key that results in a key-preview stick... tends to also somehow result in a context-desync scenario when backspacing to the end of the key-mash.  For example, if I key-mash the `j` key until it sticks, unstick it, and then type an `l`... backspacing through that `l` (and any other keys used to "unstick it") will replace the final post-`j` output text with an extra `j`.  I've observed that there is an `android-host.js` `resetContext()` call that occurs in this scenario, which triggers a `new context` group call after both the standard key-event rules and the post-keystroke rules.

**Comment by jahorton** [comment] 2024-02-20 01:52
> Extra 'fun' note: doing a key-mash on a single key that results in a key-preview stick... tends to also somehow result in a context-desync scenario when backspacing to the end of the key-mash. For example, if I key-mash the `j` key until it sticks, unstick it, and then type an `l`... backspacing through that `l` (and any other keys used to "unstick it") will replace the final post-`j` output text with an extra `j`. I've observed that there is an `android-host.js` `resetContext()` call that occurs in this scenario, which triggers a `new context` group call after both the standard key-event rules and the post-keystroke rules.

I have now confirmed that this is a completely separate issue - I can reproduce it by copying and pasting the text I get from a key mash, _without the need to even type it_ to trigger the error.  Refer to #10776.

**Comment by jahorton** [comment] 2024-02-20 02:59
> This does appear to reproduce fairly easily with an old SM-T350 (Galaxy Tab A) tablet. It's older and slower, enough so that it lags during rapid typing. Granted, I haven't gotten the error message part yet, but odd sticky behaviors are happening:
> 
>     * often, multiple keys experience stuck highlighting if typing rapidly
>       
>       * if the issue is _just_ highlighting, tapping the key is enough to unstick it.
> 
>     * a tablet-style key preview gets 'stuck' with some regularity
>       
>       * When the latter occurs, it only gets 'unstuck' when I switch layers and then type a key... or few.  The layer-swap does appear necessary, though.
>       * Power-mashing the same key over and over can eventually trigger a key-preview stick... but this only appears to trigger after several keypresses.

At this point, I think I've about figured out the stuck-preview part... but then there's the matter of stuck key highlighting.

The _highlighting_ part seems to reproduce with some reliability if I do the following:  
1. Hover three separate fingers over the following keys: <kbd>w</kbd> <kbd>r</kbd> <kbd>y</kbd>.  (The key spacing helps me ensure I touch the center of each key accurately.)
2. In _very rapid succession_ type each key, from left to right with as fast (yet firm) of a tap as possible.

The repro isn't 100% consistent, but it is "consistent enough" to use for investigations while keeping the related events (and thus, any related investigation-logging) to a minimal number.

It gets even more consistent if I repeat step 2 an extra time immediately after completing it... with extra logging details, of course.

Also, while not _at all_ consistent, I have seen a stuck longpress arise from this repro one time.

**Closed** 2024-04-03 08:42 UTC
Labels: bug, android/
