### ISSUE TITLE
chore(linux): Linux artifacts missing from PRs

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#10602] opened 2024-02-02 02:30 UTC
e.g. https://github.com/keymanapp/keyman/pull/10585

![image](https://github.com/keymanapp/keyman/assets/4498365/85ba963a-57ef-4e6d-a847-0eb40c9bf8a4)

![image](https://github.com/keymanapp/keyman/assets/4498365/29793657-33dc-4b98-bbcb-1a90a4e0d222)

**Comment by ermshiperete** [comment] 2024-02-02 10:12
The test bot should add Linux artifacts in the artifact links comment regardless of failed package build. For other failed builds it adds "build failed" instead of a link to the artifacts. Moreover, in a lot of cases the artifacts are still available in the Debian Packaging check even if the total result of the check is "failed".

So the question is why does the bot ignore the Linux artifacts?

**Comment by ermshiperete** [comment] 2024-02-02 10:28
Caused by #10577 which renamed the artifacts.

**Comment by ermshiperete** [comment] 2024-02-02 11:30
Will be fixed by keymanapp/status.keyman.com#422.

**Closed** 2024-02-02 22:27 UTC
Labels: linux/, chore, ci
