### ISSUE TITLE
bug(developer/ide): Ctrl + Z switches from portrait to landscape mode in Touch Layout

### ISSUE THREAD

**Issue by alex-larkin** [keymanapp/keyman#11208] opened 2024-04-11 03:32 UTC
### Describe the bug

When I am in the touch layout and viewing the device in portrait mode, hitting Ctrl + Z (or going to Edit>Undo) causes the device to switch back to landscape mode (in addition to undoign the last action.)

Here is a screen recording where I demonstrate: 
https://drive.google.com/file/d/1q1LIHnL80Xc_Slh8LxPX2r5eDVIH1uGH/view?usp=sharing

### Reproduce the bug

(See above)

### Expected behavior

I expect that Ctrl + Z will undue the last action without changing the orientation of my device. 

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0.147

### Operating system

Windows 10 Pro

### Device

Asus Laptop

### Keyboard name

teclado_quechua

### Language name

Quechua (que)

**Comment by darcywong00** [comment] 2024-04-11 09:37
Hi @alex-larkin 

This is a duplicate of #7852 and fixed in 17.0.204 alpha in PR #9914.

In your video, you mentioned preferring the portrait orientation in Keyman developer.
For most keyboard developers, we'd recommend reducing the layouts and keeping one - (phone - portrait) should suffice.
This avoids a common mistake of changing a key in landscape-tablet and not seeing it in phone-portrait.

**Closed by darcywong00** 2024-04-11 09:37 UTC
Labels: bug, developer/, developer/ide/

**Comment by alex-larkin** [comment] 2024-04-11 13:26
Thanks Darcy!

I searched for existing bug reports but missed that one, I guess because it
had already been closed.

Is KD's default behavior to have two layouts?

Do you know if my project came with two layouts because I imported the
Latin American keyboard?

Thanks again!

Alex

**Comment by alex-larkin** [comment] 2024-04-11 17:24
To answer my own aformentioned questions, In KD 17.0.305-beta I created two new test projects. 

One with the option "Keyman Keyboard" and in the other "Import Windows Keyboard"

In "Keyman Keyboard", it only had a phone layout, and included both portrait and landscape views. 

In "Import Windows Keyboard", it only had a tablet layout, and included both portrait and landscape views.

So I have no more questions in this regard.

**Comment by mcdurdin** [comment] 2024-04-17 04:51
Note that portrait and landscape are just different presentations of the same data -- they have no functional difference.

**Comment by alex-larkin** [comment] 2024-04-17 11:27
Thanks Marc! I think in my last message I meant to ask about Platforms instead of Layouts. Sorry for the confusion!
