### ISSUE TITLE
bug(developer): Uninstall button is still working if there is no keyboard available in the Keyman Configuration dialog

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#8937] opened 2023-06-06 09:31 UTC
### Describe the bug

I noticed that even though there is no keyboard available in the Keyman configuration dialog, the Uninstall button in the Build tab is still enabled state. 

### Reproduce the bug

1. Install Keyman Developer 17.0.118-alpha build in a clean machine. 
2. Open a Keyman project. (eg., sil_cameroon_qwerty.kpj)
3. Click the Build tab. 

Here, I noticed that the Uninstall button is in enabled state. (FYI, I did not install any keyboard)

4. Click the Uninstall button. 

I got a message 'Keyboard uninstalled successfully'  on the screen. 

Note: It is showing this message even though there is no keyboard available on the Keyman Configuration dialog. 

I have attached the Screenshot for reference. 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/6aedc296-d760-419a-bf1d-1f29f4681318">

### Expected behavior

The Uninstall button in the build view should be in disabled state if there are no keyboards available in the Keyman Configuration dialog. 

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [X] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.117-alpha build

### Operating system

Windows 11 OS (VM)

### Device

Windows Desktop

**Comment by mcdurdin** [comment] 2023-06-12 07:22
This is 'by design' -- Keyman Developer allows the keyboard developer to attempt to uninstall the keyboard again, which can be necessary if there is a broken configuration from testing earlier. Closing :grin:

**Closed by mcdurdin** 2023-06-12 07:22 UTC
Labels: bug, developer/, developer/ide/
