### ISSUE TITLE
bug(windows): Not able to add a removed language using Add / remove language option in Keyboard Layouts view

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#9264] opened 2023-07-13 14:36 UTC
### Describe the bug

I noticed that I was not able to add a removed language using Add/remove language option. 

### Reproduce the bug

1. Install Keyman 17.0.138-alpha build. 
2. Open Keyman Configuration dialog. 
3. Download and install Khmer Angkor Keyboard. 
4. Click on the Khmer Angkor keyboard blue bar to expand. 
5. Click Add/remove language button. 
6. Click the (X) button to uninstall the language. 
7. We may notice that Khmer Angkor language is removed from the Add/remove language pane. 
8. Click 'Add language' button. 
9. We may notice that 'Central Khmer..' language is selected by default. 
10. Click the OK button. 

Here, I noticed that a warning message appears 'Unable to install keyboard language;...' on the screen. 

11. Click the OK button to close the dialog. 
12. Click the OK button once again on the Add Language to Keyboard dialog. 

Again, I am getting the same warning message. It seems that it is not possible to add a removed language. 

I have attached the Screenshots for reference. 

..Warning Message 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/5b871cbe-fd57-4b3d-9d88-664d3738659a">

..Empty Add/Remove language dialog

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/883537b1-5a75-454f-acb8-470f2d0f1c48">

### Expected behavior

By using the Add language button it should be possible to add a removed language. 

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [X] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.138-alpha

### Operating system

Windows 10 OS, Windows 11 OS (VM)

### Keyboard name

khmer_angkor

### Keyboard version

1.3

### Language name

Khmer

**Comment by rc-swag** [comment] 2023-08-04 03:53
I was not able to reproduce this problem. It seems to be a bug around transient language limits.

**Comment by rc-swag** [comment] 2023-08-11 06:12
@bharanidharanj Do you remember if this was windows 10 or Windows 11?

**Comment by rc-swag** [comment] 2023-08-17 04:26
@bharanidharanj  Can I get you to try to reproduce this again? I think it might be a low-occurrence error and it could be which could be a issue when applications are loaded using languages that are being installed or uninstalled. It will also be mitigated by implementing increasing the number of transient language support as per this issue #9422

**Comment by rc-swag** [comment] 2023-08-30 03:35
This second example posted its working as expected when you reach the limit for transient languages on the Windows operating system.  The first example above was strange the steps adding and removing the same language. 

I am going to close this issue it can be raised again if it occurs in the original report. Even then the transient language issue is a limitation of the operating system.  By implementing  #9422 it will at least reduce the opportunity for this case to occur.

**Closed** 2023-08-30 03:36 UTC
Labels: bug, windows/, windows/config/
