### ISSUE TITLE
[Developer] The links to keyboard on the welcome screen do not work

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#2670] opened 2020-02-18 02:47 UTC
**Describe the bug**
When opening the Developer for the first time after the installation is completed, the links to keyboards at the bottom of the screen do not take the user to the keyboard project. It seems in responsive to click.

![image](https://user-images.githubusercontent.com/28331388/74626695-f8345900-5182-11ea-9602-f865d718fcfd.png)

**To Reproduce**
1. Install Keyman Developer afresh
2. Open it from the Start menu
3. See the welcome screen and most like see some keyboard links at the bottom of the page
4. Click on one of the keyboard link and See error

**Expected behavior**
The keyboard project should be opened once the link is clicked on.

---
 
**Keyman Developer:**
 - OS: [Windows 10 Pro 1909
 - Keyman Developer version: 13.0.74
---

**Additional context**
You may have to have some keyboards that you have been working on before so that you can see the link at the bottom of the welcome page.

**Comment by mcdurdin** [comment] 2020-02-18 02:50
Duplicate of #2667.

**Closed by mcdurdin** 2020-02-18 02:50 UTC
Labels: bug, developer
