### ISSUE TITLE
bug(linux): German - EuroLatin Keyboard is missing in the system tray after the installation 

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#9114] opened 2023-06-27 13:05 UTC
### Describe the bug

I noticed that after installing German - EuroLatin keyboard, the keyboard name is missing on the system tray. 

### Reproduce the bug

1. Install Keyman 17.0.130-alpha build
2. Open Keyman Configuration dialog.
3. Type 'German ' in the Keyboard search bar. 
4. Click EuroLatin (SIL) (German language) link. 
5. Install German - EuroLatin Keyboard. 

Here, I noticed that the installed German-EuroLatin keyboard does not appear in the System taskbar. 

Note: I tried the same steps in Wasta 20.04 Linux OS and it is working fine. (Not working in Ubuntu Focal 20.04, Jammy Jelly  22.04 and Lunar 23.04 Linux OS) 

I have attached the Screenshot for reference. 

..German-EuroLatin keyboard missing in the system tray.

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/9c3f55f8-9d62-4d6c-8a54-11fd21c8f2b4">

..appears in Wasta 20.04 Linux OS

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/8112747f-f7cb-4e20-917e-1549830559bd">

### Expected behavior

After installing German - EuroLatin keyboard, the keyboard should appear in the system tray. 

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [X] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.130-alpha build

### Operating system

Ubuntu 20.04 Focal, Ubuntu 22.04 Jammy and Ubuntu 23.04 Lunar Linux OS

**Comment by ermshiperete** [comment] 2023-06-28 18:07
Thanks @bharanidharanj! I can reproduce this issue. Can you please go to the system settings, Keyboard tab and attach a screenshot of "Input Sources"? Thanks!

**Comment by ermshiperete** [comment] 2023-06-28 19:23
Similar problem happens on Windows: when searching for "German" and clicking on "EuroLatin (SIL) (German language)" the keyboard language "Plautdietsch" gets selected in the "Install Keyboard/Package" dialog.

**Comment by mcdurdin** [comment] 2023-06-30 08:37
So I think the fact that a `pdt` keyboard doesn't appear is maybe a separate problem?

**Comment by ermshiperete** [comment] 2023-06-30 09:55
I think `pdt` not showing will be fixed by #9027 (The problem is that we currently install it with `pdt-Latn`)

**Comment by bharanidharanj** [comment] 2023-06-30 10:01
> Thanks @bharanidharanj! I can reproduce this issue. Can you please go to the system settings, Keyboard tab and attach a screenshot of "Input Sources"? Thanks!

Sure @ermshiperete . I will do it.

**Comment by bharanidharanj** [comment] 2023-06-30 10:14
@ermshiperete  Retested in Ubuntu 20.04 Focal Linux OS and here is my observation: 1. Installed German -EuroLatin Keyboard via Keyman Configuration dialog. 2. Noticed that the German - EuroLatin Keyboard is missing in the system tray. But it appears under Input Sources pane. 

I have attached the Screenshot for reference. 

<img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/2ea8a933-e46e-4a8a-8ce8-51f8c7335e1f">

**Comment by ermshiperete** [comment] 2023-07-05 12:58
This should be fixed with https://github.com/keymanapp/api.keyman.com/pull/198. 

@bharanidharanj Can you re-test please?

**Comment by bharanidharanj** [comment] 2023-07-06 06:21
> This should be fixed with [keymanapp/api.keyman.com#198](https://github.com/keymanapp/api.keyman.com/pull/198).
> 
> @bharanidharanj Can you re-test please?

Okay @ermshiperete I will retest it.

**Comment by bharanidharanj** [comment] 2023-07-06 07:36
@ermshiperete Retested with the latest Keyman 17.0.134-alpha build in Ubuntu 22.04 Linux OS and here is my observation: 1. Installed German - EuroLatin(SIL) keyboard using Keyman Configuration dialog. 2. Able to see the German EuroLatin(SIL) icon on the system tray. Seems to be fixed and working fine. Thanks. 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/604dff0a-409b-4bd7-b54e-fe87a6e1ae03">

**Closed** 2023-07-10 06:37 UTC
Labels: bug, linux/, user-test-required
