### ISSUE TITLE
[Android] Obsolete API in use

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#3460] opened 2020-08-05 20:06 UTC
**Describe the bug**

Following warning appears during build of FV Keyboards:

```
WARNING: API 'variantOutput.getPackageApplication()' is obsolete and has been replaced with 'variant.getPackageApplicationProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getPackageApplication(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
```

---

**Android:**
 - Keyman version 14.0.123

**Comment by darcywong00** [comment] 2020-08-07 04:55
Similar warning during build of MAPro
```
WARNING: API 'variant.getMappingFile()' is obsolete and has been replaced with 'variant.getMappingFileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
```

This is caused by our current version of sentry-android-gradle-plugin and fixed in 1.7.32

**Closed** 2020-08-09 23:22 UTC
Labels: android/, chore
